### ISSUE TITLE
Add proper error handling to lightweight dynamic server

### ISSUE THREAD

**Issue by toolness** [mozilla/learning.mozilla.org#1007]
Currently we don't have any formal way of handling errors, and we should.

Need to figure out what the best way to log 500s so we can be notified of them is. (Actually, this also applies to `teach-api` for that matter.)

**Comment by Pomax** [comment]
based on the build work we want to do in 2016, this issue may or may not stay relevant. Leaving open for now.

**Comment by alicoding** [comment]
@Pomax should we close and revisit?

**Comment by Pomax** [comment]
close - the "lightweight dynamic server" no longer exists, it's just app.js now
