### ISSUE TITLE
Lightweight dynamic server should generate sitemap.xml

### ISSUE THREAD

**Issue by toolness** [mozilla/learning.mozilla.org#1008]
This will take a bit of work, since the existing sitemap is generated by crawling all the `index.html` files of the static site, which isn't feasible for the dynamic server.

**Comment by Pomax** [comment]
based on the build work we want to do in 2016, this issue may or may not stay relevant. Leaving open for now.

**Comment by Pomax** [comment]
this issue is no longer relevant.
