### ISSUE TITLE
Lightweight dynamic server should serve compressed static files

### ISSUE THREAD

**Issue by toolness** [mozilla/learning.mozilla.org#1009]
At least in production, we should gzip the static files we serve.

(Alternatively, we could store all the static files on S3 via CloudFront, but it seems like we want even a lot of our dynamic content to be aggressively cached by a reverse proxy of some sort.)

**Comment by Pomax** [comment]
based on the build work we want to do in 2016, this issue may or may not stay relevant. Leaving open for now.

**Comment by alicoding** [comment]
I think we can close this since our cloudfront should have dealt with these.
