### ISSUE TITLE
Lightweight dynamic server should serve relevant content with cache headers

### ISSUE THREAD

**Issue by toolness** [mozilla/learning.mozilla.org#1010]
At least in production, we want to be able to place a [reverse proxy](http://en.wikipedia.org/wiki/Reverse_proxy) in front of the server that uses the headers to aggressively cache content that doesn't change often.

**Comment by Pomax** [comment]
based on the build work we want to do in 2016, this issue may or may not stay relevant. Leaving open for now.

**Comment by alicoding** [comment]
This should be okay to close
