### ISSUE TITLE
Lightweight dynamic server should serve security headers

### ISSUE THREAD

**Issue by toolness** [mozilla/learning.mozilla.org#1011]
Pretty straightforward, we need to at least provide headers for:

- [ ] Content Security Policy (CSP).
- [ ] Strict Transport Security (STS)
- [ ] [`X-Frame-Options: DENY`](https://developer.mozilla.org/en-US/docs/Web/HTTP/X-Frame-Options) (Clickjacking protection)
- [ ] [`X-Content-Type-Options: nosniff`](http://blogs.msdn.com/b/ie/archive/2008/09/02/ie8-security-part-vi-beta-2-update.aspx)

**Comment by Pomax** [comment]
based on the build work we want to do in 2016, this issue may or may not stay relevant. Leaving open for now.

**Comment by alicoding** [comment]
We have these implemented.
