### ISSUE TITLE
Document how to update ENV VARS 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/learning.mozilla.org#1058]
@toolness your https://github.com/mozilla/teach.webmaker.org/issues/892#issuecomment-101746372 was very useful and I think we should find a place for it to live... maybe somewhere in README.md?
>
- Update the `README.md` to document the new environment variable.
- Mention the environment variable as an added feature in `CHANGELOG.md`.
- Add the environment variable to the list of vars exported to the client-side browser code in `webpack.config.js`.
- Set the environment variable to its appropriate values for prod and staging in `TRAVIS_BRANCH_CONFIGS` in [`lib/travis.js`](https://github.com/mozilla/teach.webmaker.org/blob/develop/lib/travis.js).

I introduced 2 new env vars in [this commit](https://github.com/mozilla/teach.webmaker.org/commit/4c7b4ba1dd6d6e7204ba67c82006cbe4b57bbac6) and apparently I failed to add them properly.  Your checklist above will definitely help the same thing from happening again :relaxed: 

Gonna assign this ticket to you if you don't mind :dancers:

**Comment by toolness** [comment]
Ahh gotcha, makes sense! Thanks for fixing your stuff in #1059... I wish there was a way we could programmatically verify this, but I can't think of any easy ways to do it.

**Comment by alicoding** [comment]
Feels like we have bunch of these env documented.
