### ISSUE TITLE
Clubs Map: user-reported error selecting "Athens, Greece"

### ISSUE THREAD

**Issue by thornet** [mozilla/learning.mozilla.org#1155]
via a user: 

> I registered a Mozilla Club called Girls Go Coding, but I couldn't add "Athens, Greece" as the location, so I added Athens, Georgia. Could you please correct it when you process the application?

Is it possible for us to look into this and see if there's anything we should fix on our end?

**Comment by hannahkane** [comment]
Thanks, @thornet. Putting it in the next milestone, and noting that this is very complicated problem, and not limited to Athens.

**Comment by hannahkane** [comment]
Removing this from August 28 milestone due to other priorities

**Comment by mmmavis** [comment]
I think it's worth investigating how Mapbox loads it location data.  I'm gonna putting this in this heartbeat.

**Comment by hannahkane** [comment]
Putting this in a January milestone as a P2. Don't want to forget about it, but may become unnecessary if we change how Clubs are managed.

**Comment by mmmavis** [comment]
I just tested it on [Mapbox's site](https://www.mapbox.com/mapbox.js/example/v1.0.0/geocoding-auto/), it seems like Mapbox's dataset doesn't have good coverage for Greece (also re: coverage chart on https://www.mapbox.com/developers/api/geocoding/). :frowning:

**Comment by mmmavis** [comment]
Mapbox says [we can upload map data to our account](https://www.mapbox.com/help/#work-with-data-and-imagery).  Wondering if we can utilize it to expand the dataset coverage?

**Comment by hannahkane** [comment]
Closing in light of pan-Mozilla Clubs platform project
