### ISSUE TITLE
As an admin, I can view a queue of outstanding badge applications, and review them

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#1193]
Acceptance criteria
 * I should see counts of outstanding badge applications
 * I should be able to filter applications by badge type, and sort by submission date
 * I should be able to filter by "partner organization" (see related requirement of #1192)
 * I should be able to see the badge criteria while I'm reviewing the applicant's evidence
 * I should be able to easily access the applicant's profile from the application
 * I should be able to approve or deny the application, and edit an email template that will be sent to the applicant

Phases of work:
 - [ ] Write default email templates for approval and denial
 - [ ] Wireframe workflow (#1240)
 - [ ] Implement workflow

**Comment by Pomax** [comment]
We need to check if credly already offers this through their own UI. If so, we don't need to work on that, if it doesn't, we don't need to do any work here.
