### ISSUE TITLE
add habitat for .env loading

### ISSUE THREAD

**Issue by Pomax** [mozilla/learning.mozilla.org#1203]
We should not need to `source env`, with a different solution on Windows - [habitat](https://www.npmjs.com/package/habitat) can do the enviroment loading cross-platform.

**Comment by mmmavis** [comment]
this looks like something we can tackle this heartbeat! :grin:

**Comment by mmmavis** [comment]
@Pomax this seems to be fixed! Let's close this ticket? 😉

**Comment by Pomax** [comment]
hah, almost a year old. Good call! We totally have that already these days.
