### ISSUE TITLE
make ImageTag (and HiveLink) explicit about their x1, x2, xN sources

### ISSUE THREAD

**Issue by Pomax** [mozilla/learning.mozilla.org#1254]
Right now HiveLink has a `srcx1` attribute, which seems semantically a little odd. Based on https://github.com/mozilla/teach.webmaker.org/pull/1237#discussion_r39308989 it might make sense to examine whether we can easily update the `ImageTag` element to take its sources as an object with intentfully set source strings:
```
<ImageTag src={{
  x1: " ...",
  x2: "...",
  x4: "...",
  svg: "..."
}} .... />
```
with different resolutions for bitmaps and an `svg` indicator if we're passing in self-scaling content?

/cc @mmmavis

**Comment by mmmavis** [comment]
@Pomax want to take this one on?

**Comment by Pomax** [comment]
closing probably makes more sense, it's simply not been an actual since filing.
