### ISSUE TITLE
Collapse "user panel" when users navigate away from a page

### ISSUE THREAD

**Issue by mmmavis** [mozilla/learning.mozilla.org#1314]
This is what looks like when the user panel section is expanded:
<img width="354" alt="screen shot 2015-10-07 at 3 19 33 pm" src="https://cloud.githubusercontent.com/assets/2896608/10352880/e60355d4-6d06-11e5-8aee-371c82732e5b.png">

When users move away from a page to another we should probably auto collapse the user panel so it looks like
<img width="351" alt="screen shot 2015-10-07 at 3 19 51 pm" src="https://cloud.githubusercontent.com/assets/2896608/10352879/e6026584-6d06-11e5-8174-4bd2c1b2d7dd.png">

I could've done this in [PR#1306](https://github.com/mozilla/teach.mozilla.org/pull/1306) but since we are resigning the nav bar and our current code for sidebar doesn't make this an easy task, I think we should file an enhance ticket for it instead(so that's what this ticket is for :tada:  )!

**Comment by hannahkane** [comment]
@pomax - is this one you could do?

**Comment by hannahkane** [comment]
taking this out of the heartbeat, which is already quite full
