### ISSUE TITLE
Add Twitter Cards to teach.mozilla.org

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning.mozilla.org#1350]
With Twitter Cards, you can attach rich photos, videos and media experience to Tweets that drive traffic to our site. Simply add a few lines of HTML to a webpage, and users who Tweet links to the content will have a “Card” added to the Tweet that’s visible to all followers.

Find out more here: https://dev.twitter.com/cards/overview

TO DO:
Choose the card type we want for our site:

```
Summary Card: Title, description, thumbnail, and Twitter account attribution.
Summary Card with Large Image: Similar to a Summary Card, but with a prominently featured image.
```

Add code to each webpage of our site using Twitter's Get Started Guide here: https://dev.twitter.com/cards/getting-started

**Comment by KGorr** [comment]
@ldecoursy Feedback on the card type for each page? When we can, I think summary card with large image would be great. Not all pages have a great image to pull, however.

**Comment by ldecoursy** [comment]
I like the idea of the summary card with image.

**Comment by KGorr** [comment]
@hannahkane please let me know if you need any more information on this or if I can help in any way. Thanks!

**Comment by Pomax** [comment]
There is a fair bit of prep work that's going to have to be done before we can add twitter cards and other opengraph-style metas to the pages we generate, for which https://github.com/mozilla/teach.mozilla.org/issues/1630 has been filed. marking this as blocked for now.

**Comment by hannahkane** [comment]
@KGorr - what do you think of the suggested content below? Feel free to make edits.

- Title: Mozilla Learning 
  - url: teach.mozilla.org
 - description:
 - image:
- Teaching Activities
 - url: https://teach.mozilla.org/activities
 - description: Activities and lesson plans to get you teaching the Web
 - image: current header image on the page
- Leadership Opportunities
 - url: https://teach.mozilla.org/opportunities
 - description: Explore leadership opportunities in the movement towards a free and open Web.
 - image: current header image on the page
- Mozilla Clubs
 - url: https://teach.mozilla.org/clubs
 - description: Local groups teaching the Web around the world
 - image: current header image on the page
- Maker Party
 - url: https://teach.mozilla.org/events
 - description: Teach the Web by hosting a one-time event or workshop
 - image: current header image on the page
- Tools
 - url: https://teach.mozilla.org/tools
 - description: Open source software projects to teach and learn the Web
 - image: current header image on the page
- Community
 - url: https://teach.mozilla.org/community
 - description: Join a global community of people teaching the Web
 - image: current header image on the page

**Comment by KGorr** [comment]
Thanks, @hannahkane! This looks OK to me. For the main page, perhaps: 

description: A global community dedicated to helping people learn the most important skills of our age: the ability to read, write and participate in the digital world.
image: current header image on the page

Thoughts, @ldecoursy?
