### ISSUE TITLE
[photography] - style guide

### ISSUE THREAD

**Issue by kristinashu** [mozilla/learning.mozilla.org#1381]
**Problems:** 
Images don't have any art direction or consistent style. 

**Solutions:** 
Create a style guide for photography that determines content, layout, color, general quality of photograph; solutions for creative common random thumbnails that are present on teaching kits. Create a shot list for what we want on our site (tone, focal length, content, quality).

**Seen on:** all pages of [MLN] (teach.mozilla.org)

<img width="876" alt="screen shot 2015-10-22 at 9 38 22 am" src="https://cloud.githubusercontent.com/assets/1068783/10672551/bdce2c06-78a5-11e5-9d19-54fe36bd09a7.png">
<img width="897" alt="screen shot 2015-10-22 at 9 39 05 am" src="https://cloud.githubusercontent.com/assets/1068783/10672554/c11c1198-78a5-11e5-8ccd-37a8649c26e0.png">
<img width="811" alt="screen shot 2015-10-22 at 9 48 47 am" src="https://cloud.githubusercontent.com/assets/1068783/10672557/c2ad5ddc-78a5-11e5-8923-796bbe54397d.png">
<img width="745" alt="screen shot 2015-10-22 at 10 03 29 am" src="https://cloud.githubusercontent.com/assets/1068783/10672342/3cb1c14c-78a4-11e5-9113-2d6efe14d259.png">

**Related Issues:** #1260
**/CC:** @kristinashu @sabrinang

**Comment by sabrinang** [comment]
document photo decisions here from #1396

**Comment by cassiemc** [comment]
This work can be done in conjunction with the master style guide #1483

**Comment by kristinashu** [comment]
@sabrinang is this done and/or will it be covered by the user guide?

**Comment by kristinashu** [comment]
@sabrinang made a basic guide here https://github.com/mozilla/teach.mozilla.org/wiki/Photography
I think this is great! Sabrina, please feel free to close if you're happy with it.

**Comment by hannahkane** [comment]
Closing since the guide exists!
