### ISSUE TITLE
Async issues are preventing proper testing of form submission

### ISSUE THREAD

**Issue by Pomax** [mozilla/learning.mozilla.org#1497]
the modal-clubs.test.js file contains a "when form is submitted" test set that cannot run properly due to hitting a submission timeout. Looking at the code, there's a few levels of async that need to be fixed before these tests will *properly* run after dependency uplifting.

(see #1460)

**Comment by hannahkane** [comment]
@Pomax - is this still relevant?

**Comment by Pomax** [comment]
this is no longer relevant.
