### ISSUE TITLE
use the new mofo-style ESLint rc file

### ISSUE THREAD

**Issue by Pomax** [mozilla/learning.mozilla.org#1557]
with https://github.com/MozillaFoundation/javascript-style-guide/pull/24 landed, we should tap into this new and improved linting solution.

**Comment by Pomax** [comment]
A big problem here is that our new ESLINT rules are primed for "use ES6", which means that right now there are about 5000 errors pertaining it "please use arrow functions instead". 

As discussed with @simonwex, one way forward here may be if we can somehow selectively apply ESLINT only to files that are updated after we turn on ESLINT linting, but this is an unresolved issue at the moment.

**Comment by simonwex** [comment]
I'd like to talk through this during our next Engineering call. I've added it to that agenda.

**Comment by Pomax** [comment]
clearing the milestone here, because this is a very tricky problem, and is not happening without us figuring out how to do this for our entire app ecosystem.

**Comment by Pomax** [comment]
mostly done, finally. three rules remain, they're tracked in a newer issue.
