### ISSUE TITLE
Remove anchor links on Maker Party Resource page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/learning.mozilla.org#1604]
On https://teach.mozilla.org/events/resources/

<img width="1330" alt="screen shot 2016-01-28 at 12 32 27 pm" src="https://cloud.githubusercontent.com/assets/1068783/12658070/a71354ec-c5bb-11e5-9189-26e3f2ec9d31.png">

These anchor links are only used on this page and the page isn't actually that long. I don't think they are necessary so lets please remove them. 

This will help with some related audit ticket https://github.com/mozilla/teach.mozilla.org/issues/1393

cc @sabrinang @mmmavis

**Comment by Pomax** [comment]
do we still need to do this @hannahkane @kristinashu?

**Comment by hannahkane** [comment]
I'd say no, but, @kristinashu - what do you think?

**Comment by kristinashu** [comment]
I think we should still remove them. The functionality and style of them is only used here and I don't think they're necessary.

**Comment by hannahkane** [comment]
OK, that's fine with me. But I wouldn't call this a priority. Would rather address some of the issues assigned to a milestone. :)

**Comment by Pomax** [comment]
could I be devil's advocate here and point out that the page is long enough to need scrolling to sections, which the links solve? If I want to link someone to event support I can give them https://teach.mozilla.org/events/resources/#event-support which I will not be able to find if there are jump links at the top of the document.

**Comment by kristinashu** [comment]
I'd say this page is fairly average length for the teach site and none of the other pages have these anchors. I'm still for removing but yes, definitely not a priority.
