### ISSUE TITLE
link new curriculum template with Web Literacy 2.0 map

### ISSUE THREAD

**Issue by anmechung** [mozilla/learning.mozilla.org#1610]
@hannahkane @flukeout @sabrinang When @chadsansing and I were talking today creating links from the new web literacy 2.0 map to Web Basic I and II curriculum, it occured to us that something similar should happen for the new curriculum template as well. Make sense?  and also that the color palate for the template (as well as the 2.0 map) should be visually accessible.

**Comment by hannahkane** [comment]
Makes sense. Going to table this until Web Lit map is up and running. Plan is to finish design phase this heartbeat, and implement the following heartbeat.

**Comment by hannahkane** [comment]
closing, part of curriculum db work
