### ISSUE TITLE
 Subitems disappearing from sidebar when JS is disabled

### ISSUE THREAD

**Issue by mmmavis** [mozilla/learning.mozilla.org#1643]
Follow-up ticket for PR https://github.com/mozilla/teach.mozilla.org/pull/1641

issue 
> Works with JS enabled, but with JS disabled it looks like the subitems still disappear if you navigate to a subitem's page. We can land this and file a followup to look at why with JS disabled the generated HTML is not showing us those subitems.

**Comment by Pomax** [comment]
no longer relevant.
