### ISSUE TITLE
[ teach-api ] pushing to Heroku doesn't trigger db migration

### ISSUE THREAD

**Issue by mmmavis** [mozilla/learning.mozilla.org#1648]
... We should fix that so https://github.com/mozilla/teach-api/pull/26 can work properly on staging and production.

Not sure how we can trigger the [`makemigrations` and `migrate` commands](https://docs.djangoproject.com/en/1.9/topics/migrations/#the-commands) though... Via `.travis.yml`? `Procfile`?

Teach API repo: https://github.com/mozilla/teach-api

**Comment by mmmavis** [comment]
cc @Pomax @simonwex

**Comment by hannahkane** [comment]
Is this still an outstanding issue?

**Comment by Pomax** [comment]
nope.
