### ISSUE TITLE
Add license to the curriculum template

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning.mozilla.org#1654]
Bottom of aside/nav?

**Comment by hannahkane** [comment]
@flukeout - assigning to you. Can you decide whether this should go in the current milestone or the next, based on your availability?

**Comment by flukeout** [comment]
Looking into it!

**Comment by hannahkane** [comment]
@flukeout - is this covered in the recent work you've done on the template?

**Comment by flukeout** [comment]
Yeah, the blank template has a link to a licencense, so I think we're good.

<img width="587" alt="image" src="https://cloud.githubusercontent.com/assets/25212/19132875/6a7dcea8-8b0a-11e6-8675-1db99f716e1f.png">
