### ISSUE TITLE
Add next activity button to the curriculum template

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning.mozilla.org#1655]
To append to the bottom of the body of the last step in an activity?

**Comment by hannahkane** [comment]
@flukeout - assigning to you. Can you decide whether this should go in the current milestone or the next, based on your availability?

**Comment by flukeout** [comment]
Checking into this now - I thought we'd already added this one.

**Comment by chadsansing** [comment]
@flukeout - remind me of the class/treatment?

**Comment by hannahkane** [comment]
@flukeout - is this covered in recent changes?

**Comment by flukeout** [comment]
Yes, covered in most recent work. Visible on the bottom of the page here in the blank template...

* https://mozilla.github.io/curriculum-final/blank-template/#step-3
