### ISSUE TITLE
Link or embed code for newsletter signup

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/learning.mozilla.org#1664]
Hi @mmmavis, do you know if there is a link, or can you share the embed code, for the Mozilla Learning newsletter signup? It's the one found at the bottom of this page? https://teach.mozilla.org/community

Asking bc we might want to add links to that signup from our individual Hive sites. 

cc @KGorr @stephaniemcv

**Comment by mmmavis** [comment]
Hi @ldecoursy ,

Currently there's no direct link to the form nor any embed code.  Currently we are using BSD as the backend destination and we built that form from scratch on the Teach site. Would adding an anchor to that form help? e.g., https://teach.mozilla.org/community#signup

**Comment by ldecoursy** [comment]
OK - but we're sending the newsletter from Exact Target so I wonder if the list needs to be re-imported from BSD? Or if we need to adjust the backend to Exact Target. 

In any case, I think an anchor link would help as a short-term solution.

**Comment by ldecoursy** [comment]
Just realized in #1530 it looks like @alicoding is going to switch this to Exact Target. :D

**Comment by ldecoursy** [comment]
Checking back with @alicoding, is there a new embed code for the updated email sign-up link on teach.mozilla.org that we can also potentially use on Hive sites?

**Comment by alicoding** [comment]
Hi @ldecoursy sorry for late reply on this. I don't know if embed is possible with EactTarget but setting up newsletter now is easier than what it used to be with BSD for dev to work on. The only thing we need to make sure is setup is the mailing list on exact Target
