### ISSUE TITLE
Request updated Thimble links from community members' projects featured on /activities

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/learning.mozilla.org#1669]
Several links to community-generated teaching kits on teach.mozilla.org/activities link to old webmaker links. I'm planning to reach out to ask if they can provide new Thimble links if they'd still like to be featured on the page. 

Perhaps as part of that we can share some basic traffic data - see https://github.com/mozilla/teach.mozilla.org/issues/1463

**Comment by hannahkane** [comment]
@ldecoursy - can we close this ticket?

**Comment by ldecoursy** [comment]
We can and shall
