### ISSUE TITLE
[maps] - Align colours and styles

### ISSUE THREAD

**Issue by sabrinang** [mozilla/learning.mozilla.org#1671]
**Problems:** 
We can update the current map so it looks more visually aligned with the teach style guide. I believe we are using the default Mapbox style and can further explore how to customize for on this API and on our current plan.

**Solutions:** 
We achieve this by using our own sprites, typography and colours.

**Seen on:** 
[Clubs Page](https://teach.mozilla.org/clubs)
<img width="1019" alt="screen shot 2016-02-26 at 3 45 10 pm" src="https://cloud.githubusercontent.com/assets/2492510/13368521/ffd2fcea-dc9f-11e5-9daf-5094fa70a9d5.png">

**Related Issues:** #1545 
**/CC:** @mmmavis @kristinashu @sabrinang

**Comment by hannahkane** [comment]
Closing in light of upcoming pan-Mozilla clubs platform
