### ISSUE TITLE
Don't crash server on React errors when developing locally.

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#1681]
It seems that if you have a markup error in your ``.jsx`` files, as soon as you save the file you're working on the server crashes and won't restart until you fix the problem. A couple of instances where I've noticed this happening...

* React component wasn't enclosed in one tag
* Mismatched opening and closing tags

Can we show errors in the server log / terminal without crashing? That would make working on the site a lot more pleasant.

cc @Pomax @mmmavis

**Comment by Pomax** [comment]
this *should* now be fixed.
