### ISSUE TITLE
Create initiative landing page for Letters to the Next President

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/learning.mozilla.org#1682]
We'll need a landing page that we can point people to based on our content, events, etc. related to our involvement in NWP's [Letters to the Next President](http://letters2president.org/) campaign. 

**Deadline**
* End of April (so we have it ready for May Curriculum Workshop)

**Content**
* Partner logo - find campaign logos here https://www.dropbox.com/sh/1xat5jzm23eqak2/AABBmue-PFmLbiz2KnKwa2q5a?dl=0
* Title
* Intro text
* Thumbnails and links to 3+ activities
* List and links to up to 3 upcoming/related events (this section would eventually be removed - after the election)
* Gallery of remixes (this would be a "nice to have")

I know this may still be a consideration for a CMS template - let me know if you need further details.

cc @chadsansing

**Comment by hannahkane** [comment]
@flukeout, @vazquez — this is a specific use case for the ["Header Image with CTAs" layout](https://github.com/mozilla/mozmaker-templates/issues/6), in case you want to reference it when we get to that ticket.

**Comment by ldecoursy** [comment]
Almost filed a new ticket but I see this is still open. Can we create a landing page for this on /activities within the next week so we can start promoting in Sept? 

See content doc here: https://docs.google.com/document/d/1nfEqS2sA6rythfd5RYNgF8938G0SIe4gE8UF4V1eL1I/edit#

Note we don't need a special page to link to events or a gallery of remixes - can keep it simple just to have a single page with our four activities related to this campaign. 

cc @chadsansing

**Comment by hannahkane** [comment]
Thanks for the reminder, @ldecoursy.  I'll work on this this week.
