### ISSUE TITLE
Update email validation regex with Exact Target's pattern

### ISSUE THREAD

**Issue by mmmavis** [mozilla/learning.mozilla.org#1740]
@stephaniemcv reported that our client side email validation for the newsletter signup form doesn't accept emails with plus sign (+) in them. We should probably update [the regex](https://github.com/mozilla/teach.mozilla.org/blob/develop/lib/util.js) so that it matches ET's pattern.

@stephaniemcv @alicoding do you by any chance know what pattern ET(or Basket) uses?

Note the client side validation is the fallback for browsers that don't support HTML5 form validation. For server side submission failure handling see https://github.com/mozilla/teach.mozilla.org/issues/1676

/cc @Pomax

**Comment by alicoding** [comment]
@mmmavis can you just do `encodeURIComponent(email); before sending that to `Basket` ? I've tested that with curl and it worked

```
$ curl --data "lang=pt-BR&newsletters=network&email=value2%2B2%40a.ca" https://basket-dev.allizom.org/news/subscribe/
{"status": "ok"}%
```

**Comment by Pomax** [comment]
that sounds like a nice solution to me.

**Comment by mmmavis** [comment]
@alicoding @Pomax i think the problem here isn't about the encoding. It's [our regex here](https://github.com/mozilla/teach.mozilla.org/blob/develop/lib/util.js#L3) doesn't like "+" nor "%".

I'm gonna update it to (regex copied from http://stackoverflow.com/a/46181)
```js
var regex = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
```

**Comment by alicoding** [comment]
I don't know if that's the only thing too @mmmavis? I tried curl with + and it fails to submit to ET, but not when I encoded that.

**Comment by mmmavis** [comment]
curl with + doesn't work but I think `superagent` takes care of it when we `POST` to `basket`

In https://github.com/mozilla/teach.mozilla.org/blob/f9e0abfa1d78bef5556d61f57ff34a0f18ba9dc2/components/newsletter-signup/SignupForm.jsx#L37, `type` is set to `form`, which sets `Content-Type` to `application/x-www-form-urlencoded`, see https://visionmedia.github.io/superagent/#post-/-put-requests for deatils (search for `.type('form')`). I tried passing a hardcoded email that contains "+" in it and got `status` 200 back. :grin:

**Comment by Pomax** [comment]
we need unit tests for this, so we're not testing this "by hand", but just automate it against a set of known good and a set of known bad email address. Going down that path, we should also probably be using a node module that was designed for email validation, rather than fixing our regexp by writing another regexp =)

**Comment by mmmavis** [comment]
another related issue: https://github.com/mozilla/learning-networks/issues/416

**Comment by mmmavis** [comment]
Closing this PR now as my other [PR](https://github.com/mozilla/learning.mozilla.org/pull/1911) covers the fix for this.

**Comment by mmmavis** [comment]
oops re-opened. 

thought this "ticket" was a "PR" 😉

**Comment by mmmavis** [comment]
Gonna close this ticket now. 

Talked to pmac on this just now and we think doing a super simple email check front end and relying on Basket for a more thorough check would provide less maintenance burden. Since Basket is still being actively developed and probably so is Salesforce, it's really tricky for us to keep our front end regex check always and 100% aligned with *both* Basket's and Salesforce's. **Solution:** stick with simple email check front end and let Basket worry about matching with Salesforce's pattern. We should display error message to users if Basket isn't happy about the email users put (https://github.com/mozilla/learning.mozilla.org/issues/1676 should cover this).
