### ISSUE TITLE
Explore & document calypso collaboration features

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#1741]
This is a follow-up to the collaboration survey from #1620. We'll want to identify and explore which collaboration features are built in to calypso. This will help us...

* See how these features map to the needs expressed by the survey respondents
* Identify any key features that might be missing (and start planning on solutions & timelines)
* Produce & training resources for new users

Beyond the actual features, I'd like to also assess how easy contribution is for someone who isn't very familiar with Calypso. Barriers like technical or UX complexity or need for an account might deter collaborators from participating.

In addition, if our system allows it, we can see about leveraging any existing Wordpress plugins or add-ons that could help make collaboration easier.

@hannahkane Anything else to add?

**Comment by hannahkane** [comment]
Nothing to add. :)
