### ISSUE TITLE
Explore & map out different collaboration pathways.

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#1742]
In our survey on collaboration #1620, we mostly focused on the experiences and needs of a document "owner" and didn't spend much time on collaborators who came to help at the request of the owner.

I'd like to map out some different paths and flows for these different types of contributors. This might help us identify some UX or feature gaps & needs.

**For example**
* What does is the flow for being invited to edit or comment on a document
* What is the flow for making a suggestion to edit a document & getting that suggestion approved or rejected, etc.

**Comment by hannahkane** [comment]
I'm interested in this ticket, but also want to suggest keeping it low priority until the CMS has been in use for awhile and we can see if this need emerges.
