### ISSUE TITLE
Set up some administrative users for testing the flow

### ISSUE THREAD

**Issue by Pomax** [mozilla/learning.mozilla.org#1772]
Specifically, can we authorize users as admins, badge creators, badge approvers without edit rights, etc.

**Comment by Pomax** [comment]
it does, although how we can do this through the Credly website still needs some investigating.

**Comment by Pomax** [comment]
based on the information in http://support.credly.com/knowledgebase/articles/866265-how-can-i-add-managers-to-my-organizational-accoun we can easily add managers with full badge control, as well as reporters (who can see stats and metrics but not administer badges) but there is nothing in between the two, so there is no dedicated user profile that allows for a user that can review and reward/decline, but not create/edit, badges.

**Comment by hannahkane** [comment]
Given our focus on awarding badges to people who directly participate in Mozilla programs/trainings, this is likely not a problem for us. We can limit badge administrators to highly trusted people. (Though it does seem like a feature Credly might want to implement at some point.)

**Comment by Pomax** [comment]
after further talks with Credly, we can also maintain whitelists of users that we authorize to award/decline badge applications on a badge-by-badge basis, giving use several levels of users:

- owner: this account is effectively the holder of mozilla's registration with Credly
- managers: these accounts can perform full badge administration (create, update, delete, award/decline)
- reviewers: these are accounts that we, on a per-badge basis, mark as being able to award/decline badge applications, but do not have administrative abilities around the badges themselves
- reporters: these are accounts that have access to the badge statistics only
- users: these are accounts that can apply for badges
