### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by mmmavis** [mozilla/learning.mozilla.org#1797]
Let's remove "static site generator" and S3 related bits from the README.md since they are no longer relevant :wink: 

/cc @alicoding

**Comment by alicoding** [comment]
S3 is removed I believe, but static site generator would be awesome to remove

**Comment by Pomax** [comment]
S3 can be removed, but we can't remove the mention of the static generator until we actually remove those bits of gulp task, and tests, too.

**Comment by Pomax** [comment]
readme's been updated after the build rewrite
