### ISSUE TITLE
Migrate localized Web Lit Basics I modules to new template

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#1801]
I can't assign this due to a current github bug, but this ticket is for @soapdog. :)

See https://github.com/mozilla/teach.mozilla.org/issues/1538 for new template

**Comment by soapdog** [comment]
I am also taking the time to add L10N support for the template so that we don't need to rework it later.

**Comment by hannahkane** [comment]
@soapdog - just curious if you've made any progress on this. Do you need any support?

**Comment by soapdog** [comment]
I think I will need support on this one. Let me post what I have and where I am facing difficulties and then we can see how can you help. 🐹

**Comment by hannahkane** [comment]
OK, let me know. :)

**Comment by hannahkane** [comment]
hey @soapdog - how's this coming? 

I'm moving this to a later milestone to continue tracking.

**Comment by soapdog** [comment]
@hannahkane we'll need help from the localizers, there is extra content such as "headlines" which are needed and not present. I just arrived back from the all-hands, will have them up on Monday.
