### ISSUE TITLE
implement the moz badges on the Credly side

### ISSUE THREAD

**Issue by Pomax** [mozilla/learning.mozilla.org#1811]
Based on https://docs.google.com/document/d/1u9j28HqV8QMsk-foS1r0N-tVtmcLTLsGz9m7eKcT_eU, with the badge images from https://github.com/mozilla/teach.mozilla.org/issues/1337

**Comment by Pomax** [comment]
It turns out Credly only allows 128 characters for a badge description, and 500 characters for evidence requirements, so we're going to have to rework the four skills in terms of those restrictions. @anmechung @hannahkane

**Comment by hannahkane** [comment]
Thoughts on this, @anmechung? 
This feels quite limited, though I understand why they might have made this decision—it's certainly a simpler user experience.

We *could* use the space to link to an external document with more details, but that feels pretty janky.

An-Me, what do you think?

**Comment by anmechung** [comment]
Hannah - agreed on limitation. May be check boxes later will be helpful,
but in the meantime, +1 to your solution.

**Comment by Pomax** [comment]
We could do a shortlink with a (literal) summary explanation, but given that these are our badges we could also house that information on the teach site itself. In which case, we can present our badges with lots of details on the site, while using the short form on Credly.

Thinking out loud, one thing to consider is that most badges seem to be about "a thing", with a few requirements, so something like our 21st century skill badge with (effectively) 18 requirements feels like those should be 18 badges (one per requirement) and a master badge that you're awarded when you've earned X our of 18 badges, with a "gold badge" or something if you've achieved all of them.

**Comment by Pomax** [comment]
marking as blocked by https://github.com/mozilla/teach.mozilla.org/issues/1771 in terms of the "real" badges.

For staging, this issue should not be blocked.

**Comment by anmechung** [comment]
Thinking out aloud - should there be a way of letting people keep track of which requirements/competencies they have added evidence for? And when they have all the evidence in place for the badge alerting us that all the evidence is ready to review?  Or should they not upload all the evidence until they are ready to have the badge assessed and awarded?

**Comment by Pomax** [comment]
After talks with Credly, we have the following limitations:

- short description: 128 characters limit (think subtitle, not true description)
- description text: 1200 characters limit
- evidence requirements text: 1200 characters limit
- evidence submitted by users for their badge: 20MB limit

**Comment by hannahkane** [comment]
So, @Pomax - what's the next step here? Can we set up @anmechung as an administrator and have her test out the process of creating new badges?
