### ISSUE TITLE
Sidebar on /clubs should be in dark blue

### ISSUE THREAD

**Issue by mmmavis** [mozilla/learning.mozilla.org#1827]
<img width="1000" alt="screen shot 2016-04-19 at 5 00 40 pm" src="https://cloud.githubusercontent.com/assets/2896608/14659371/4b774424-0650-11e6-9d2e-e30e1bbe99c6.png">

but it should use the same shades as what we have for the `/opportunities` page
<img width="334" alt="screen shot 2016-04-19 at 5 01 13 pm" src="https://cloud.githubusercontent.com/assets/2896608/14659376/59e6c642-0650-11e6-9c01-1044f10b7838.png">

**Comment by mmmavis** [comment]
this is probably due to `hoc/with-teach-api.jsx` not carrying over properties in `Component's` statics: https://github.com/mozilla/teach.mozilla.org/blob/develop/hoc/with-teach-api.jsx#L38-L44 Properties like `pageClassName` and `pageTitle` etc are missing and hence creates issues.

**Comment by kristinashu** [comment]
Thanks for filing this!

**Comment by kristinashu** [comment]
Clubs page is also pulling the banner image from the home page, which isn't right. Wondering if it's related?

**Comment by mmmavis** [comment]
> Clubs page is also pulling the banner image from the home page, which isn't right. Wondering if it's related? 
good eye! and yup this is related to the failing to apply `pageClassName` to the page

**Comment by hannahkane** [comment]
I believe this is duped by #1884, so closing.
