### ISSUE TITLE
Share Style Guide

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#1835]
[Placeholder ticket since this work is ticketed elsewhere. Keeping here as well to keep the Board accurate.]

 - [ ] Share style guide with stakeholders
 - [ ] Small iterations if needed
 - [ ] Get design team to contribute new info

**Comment by sabrinang** [comment]
related to ticket https://github.com/MozillaFoundation/Design/issues/159

**Comment by hannahkane** [comment]
@sabrinang - is it useful to have this ticket? I'm thinking the ticket in the Design repo will suffice.

**Comment by hannahkane** [comment]
@sabrinang - I'm closing this since it's really a dupe.
