### ISSUE TITLE
Infrastructure for localizing Web Lit Map 

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#1847]
We've had a handful of people ask about localizing the Web Lit Map, and @soapdog has reported that the lack of localization is a significant blocker for adoption and use. 

Wondering about the work and effort required to set up a process for engaging translators in this work.

Thoughts? @Pomax @ScottDowne

**Comment by hannahkane** [comment]
cc @KGorr @anmechung @amirad @ldecoursy  - because they all interact with people who might be interested in localizing this content

**Comment by hannahkane** [comment]
cc @simonwex

**Comment by ScottDowne** [comment]
Is any of teach localized?

**Comment by hannahkane** [comment]
Nope, not yet.

**Comment by amirad** [comment]
+1 to @soapdog and the deep need for localized content for our mutli-lingual clubs. Web Lit is a good place to start but overall teach site and curriculum are biggest blockers.

**Comment by hannahkane** [comment]
@amirad  - what other content on the Teach site should we focus on localizing? The Clubs page and Captain application flow? (Are we able to provide multi-lingual support for Club Captains?)

**Comment by ScottDowne** [comment]
There is some heavy dev lifting that has to happen to make the site localizable, before we can start using localized content. That doesn't get harder or easier based on the number of things we want to localize, it's a one time cost though.

The url needs to support the `/en-US/` value in it, it needs to enable strings to be swapped out based on the locale value in the url, we need to filter out supported locales, and redirect to the browser defined locale, and if that failed, redirect to a default. There are other smaller internal infrastructure things that need to happen that are fairly abstract.

I don't intend to discourage :) just wanted to setup expectations of the cost for this, what's involved, and why it needs to happen.

**Comment by ScottDowne** [comment]
I also want to point out once the site has the foundation for localization, actually plugging in content and getting it translated in something like pontoon is actually a fairly painless and quick process compared to laying the foundation.

As an example, in donate, a whole new language can be enabled for the whole site in a day or two. Teach is probably a few multiples larger than donate, thought.

**Comment by hannahkane** [comment]
Thanks, @ScottDowne. This information is helpful (and, just to clarify, I'd hoped this ticket would be about assessing the work, not *doing* the work).

Was wondering if there's anything particular to the Web Lit Map that would affect localization. Given that it's an interactive visualization, I just wondered if there were extra considerations (separate from the baseline infrastructure we need to do to make content on Teach localizable.)

The reason I'm asking about specifics is not because of the amount of content to translate, but rather because I want to think through the implications of providing localized content. A lot of content on the Teach site is pointing to other things that aren't localized, or that I'm not sure we can provide multi-lingual support for. Things like the newsletter, our Twitter account, Goggles and Webmaker, Hive, MozFest, Gigabit, our virtual meetings (curriculum workshop and MLN community call). By translating all of the content around those things, I think we are potentially setting up the expectation that the linked content/services/tools/programs are also localized. Once we invest in building the infrastructure, I realize translating content will be relatively trivial (from a technical perspective), but I think there's a larger conversation to be had about *supporting* people in different locales in an ongoing way.

**Comment by ScottDowne** [comment]
I don't see any obvious reasons why the weblit map would be harder to translate than any  other static content. The third party content is probably a tricky issue. It'll take more time that's for sure. Before you get there, it'll be partially translated which can be frustrating.

Might help to know (but on a smaller scale), donate in German isn't linking out to a German version for all third party content, example, https://donate.mozilla.org/de/ has a link to https://wiki.mozilla.org/Donate which is English so might not be the worst to have some English links.

**Comment by alvarmaciel** [comment]
Hi to all,
I was involved in the localization to Spanish of the Web Lit Map and several resources derivated of this work. Now I'm woking on mozilla clubs in Argentina, It is really essential have these pages in spanish. how I can help?

**Comment by hannahkane** [comment]
Hi @alvarmaciel! Thanks for your comment and for your previous localization work. We've just kicked off a process to plan and estimate the work involved in building the localization infrastructure for the website, including the Web Lit Map. We'll report more soon.

cc @Pomax @alicoding @cadecairos

**Comment by hannahkane** [comment]
@alicoding @cadecairos @pomax - is it okay to close this? I'm assuming it will be covered in upcoming Learning localization work.

**Comment by alicoding** [comment]
Closing this one and will file an issue when we kick off our l10n work for the learning site.
