### ISSUE TITLE
Design review of Club Captain training certificate

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#1849]
Upon completion of the Club Captain training module, successful participants will receive a certificate.

@Carotejada has a version of the certificate ready to go, but it needs a design review (it was created back when we were using a fox image that we no longer want to use).

https://www.dropbox.com/s/tqxxqi7f81isxcb/certificate.ai?dl=0

**Comment by hannahkane** [comment]
Tentatively putting in the current milestone, but pending availability of @sabrinang or @flukeout

**Comment by hannahkane** [comment]
Moving this to May 20 milestone bc we're not going to get to it this heartbeat.

**Comment by hannahkane** [comment]
@sabrinang or @flukeout - do either of you have time to look at this? Should not be something you spend a big chunk of time on, but would be nice to do a quick review and provide suggestions for Caro. 

cc @xmatthewx

**Comment by flukeout** [comment]
I'm on it @hannahkane

**Comment by flukeout** [comment]
Here's an updated design...
![image](https://cloud.githubusercontent.com/assets/25212/15370762/2df28d42-1ced-11e6-975d-fca900844785.png)


And a redpen for comments https://redpen.io/hj8d05a3a98550f734

Once we finalize, I'll provide the editable file.

**Comment by flukeout** [comment]
cc @carotejada @amirad

**Comment by Carotejada** [comment]
Thanks @flukeout it matches the Platform look 👍

**Comment by flukeout** [comment]
I need to add a seal to this still, will work on it tomorrow.

**Comment by amirad** [comment]
Oh nice!!! Looks great. 
We should probably change the website at the bottom to now be learning.mozilla.org

Also ccing @chrislarry33 so he knows what his name is being signed to :)

**Comment by hannahkane** [comment]
good call on the url, @amirad. 

@ldecoursy and @KGorr - are we also changing the Twitter handle soon?

**Comment by hannahkane** [comment]
also, nice job on this @flukeout. :) Looks great!

**Comment by KGorr** [comment]
@hannahkane, yes it will be changing soon. We're just waiting on a couple of people to review the plan before implementing it. I'll keep you posted! (Also just granted you access to the planning doc)

**Comment by flukeout** [comment]
Updating this today - any news on the twitter handle @Kgorr?

I'll share the working file anyway so you can udate it as long as you have illlustrator, do you?

**Comment by amirad** [comment]
It changed! It's now @MozLearn

**Comment by KGorr** [comment]
Heya @flukeout, sorry, I told Hannah but didn't post it here. Yes, we are now @MozLearn! I don't have illustrator, but I'm not sure that I'll be the one handling these - @amirad?

**Comment by flukeout** [comment]
Updated with the new Twitter handle and a new fox seal.

![image](https://cloud.githubusercontent.com/assets/25212/15593237/312ab3b8-235f-11e6-84a2-046d71864757.png)

Let me know if you need any other changes. I'll attach the final, editable, AI file.

**Comment by KGorr** [comment]
Hey @flukeout - can you change teach.mozilla.org or learning.mozilla.org?

**Comment by xmatthewx** [comment]
Flagging that Luke is on extended PTO. He could fix it while we're in London, or we can identify another design to do this. cc @hannahkane

**Comment by hannahkane** [comment]
Hmm...I don't think @flukeout attached the file. @xmatthewx - do we know where it is? If it's an AI file, I can make the change.

**Comment by xmatthewx** [comment]
I don't see the file in google drive unfortunately. I will ping Luke in other channels.

**Comment by hannahkane** [comment]
I put an updated version here: https://www.dropbox.com/s/6zx3pznl4bf6yxh/certificate.ai?dl=0

@xmatthewx - should I put it in Drive somewhere?

**Comment by xmatthewx** [comment]
Here's the design assets [Clubs folder](https://drive.google.com/drive/u/0/folders/0B4Q8pzCpDS_eWTl3eDhpOHVSWHM).

**Comment by hannahkane** [comment]
Cool. Uploaded it there, too.

Closing this ticket!
