### ISSUE TITLE
Review curriculum template design changes.

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#1850]
I made quite a few updates to the curriculum template...
http://flukeout.github.io/curriculum-testing/intermediate-web-lit-two-updates/session01-buttons-and-alerts.html#overview

* Header styling
  * Treatment of modules & submodules
* Treatment of activity progress, ex ``Activity 1 of 8``
* Treatment of activity summary
* Treatment of 21C skills & Web Lit skills
  * No more "tags" - just links
* Added a 'fancy' style for lists
  * Example is on the Preparation section of the linked content
* Treatment for "up next" section
  * Also at end of Preparation step
* Made the default bullets discs instead of circles
* Made the base font of the curriculum a little bolder and easier to read

cc @chadsansing Can you look over these changes, weigh in on them, and suggest any others that you might like to see?

**Comment by chadsansing** [comment]
The color-blocking on lists of instructions, sequencing, and timing works for me. I do think we should color-block lists as a matter of course. Let's just color-block ol items for instructions - I think most ul lists are short enough to go without the treatment.

I also like the lighter-touch linked treatment of the web literacy skills and 21st C skills.

Can we test styling the code tag with the same treatment we gave the lists?

**Comment by flukeout** [comment]
**I updated some styling**
* Code tag now has the pink treament
* Added some borders between 'regular' list items too

I think we should still have the option to include both of the list types, just depends how we structure the classnames. We could make it so that...
* The fancy pink list is the default
* The plain lists need a ``class='plain'`` 

Your call @chadsansing

**Comment by chadsansing** [comment]
@flukeout - yes to the options.

**Comment by flukeout** [comment]
@chadsansing How are we doing in this ticket here, I've lost track a bit. We now have two ways to do list styling, regular and ``.fancy`` - can you review the changes within the link I posted in the first comment and let me know if there is additional work to be done?

**Comment by chadsansing** [comment]
I'll test on a lesson, ask for feedback from @Animaltinez, and we can go from there with new work or closing. Sound right, @flukeout?

**Comment by hannahkane** [comment]
Just a note: once this template is finalized, we should do a few things:
 - [ ] put a final template into a new Mozilla-owned repo
 - [ ] migrate existing "official" curriculum to that template and that repo
 - [ ] have a conversation with @soapdog about migrating already-localized content to the new template

**Comment by flukeout** [comment]
@chadsansing Cool, so there are some changes to the CSS and JS, and the files that are powering the link above are here. See if you can get these integrated with your template and ping if you need help.

* JS https://github.com/flukeout/curriculum-testing/blob/gh-pages/intermediate-web-lit-two-updates/scripts/session-script.js
* CSS https://github.com/flukeout/curriculum-testing/blob/gh-pages/intermediate-web-lit-two-updates/styles/session-style.css

**Comment by chadsansing** [comment]
@Animaltinez, do these lessons look and read better to you, style-wise? Content will remain tricky as we balance the amount  of text with users' needs for explicit, step-by-step instructions.

- [Buttons and Alerts](http://flukeout.github.io/curriculum-testing/intermediate-web-lit-two-updates/session01-buttons-and-alerts.html#overview)
- [Storytelling with Pictures](http://chadsansing.github.io/curriculum-testing/updated-template-testing/updated-session04-storytelling-with-pictures.html#step-5)

If these look better, we can implement the changes on the other lessons using the same template.

cc @omnignorant, @jgmac1106

**Comment by soapdog** [comment]
I would be really happy to be able to incorporate those changes into our current localized material. =)

**Comment by chadsansing** [comment]
@flukeout, can you make the strong tage inside the fancy list class match the normal font color (pink) instead of black?

**Comment by chadsansing** [comment]
@flukeout, can you make the blockquote treatment similar to the fancy list class treatment?

**Comment by flukeout** [comment]
@chadsansing I made the changes, you can see the result on this page...
http://flukeout.github.io/curriculum-testing/intermediate-web-lit-two-updates/session01-buttons-and-alerts.html#step-1

Let me know what else.

**Comment by hannahkane** [comment]
@chadsansing - how are you feeling about all of this? Are we good to close this thread?

**Comment by chadsansing** [comment]
@hannahkane, @flukeout - let's close for now.
