### ISSUE TITLE
Update Learning blog URL

### ISSUE THREAD

**Issue by kristinashu** [mozilla/learning.mozilla.org#1855]
The url http://blog.webmaker.org/ isn't reflective of the current brand. We should update it. Perhaps to http://learning.mozilla.org/blog

Although the blog is not currently a sub page of learning.mozilla.org we should think about eventually adding it. Updating the URL could be first step.

Styling of the blog is covered in https://github.com/MozillaFoundation/plan/issues/687

cc @hannahkane @sabrinang

**Comment by hannahkane** [comment]
I think we can do this as soon as devops is able. @ldecoursy @KGorr @KevZawacki @xmatthewx @simonwex  @mcdermott415 - any reason to hold off?

**Comment by KGorr** [comment]
@hannahkane - No reason on my end!

**Comment by cadecairos** [comment]
@hannahkane @KGorr 

Should we get this rolling again?

**Comment by KGorr** [comment]
No reason on my end to wait, but I can't speak to the technical issues involved.

**Comment by hannahkane** [comment]
I think we likely need to hold off at least for a little bit. Am in the midst of conversations with @mcdermott415 and @kaythaney about next steps on the Learning hub site > might impact this.

**Comment by hannahkane** [comment]
OK, we are good to go on moving the blog to learning.mozilla.org/blog. @cadecairos - feel free to prioritize as you see fit.

**Comment by cadecairos** [comment]
I'm checking with WPEngine support to see if setting it up like that (learning.mozilla.org/blog) is possible.

**Comment by cadecairos** [comment]
@KGorr @hannahkane The Learning blog is now abailable from https://learning.mozilla.org/blog

Things linking to blog.webmaker.org continue to load, but links on those pages will bring people to the new URL. When I get a 👍 I'll turn blog.webmaker.org into a direct redirect to `learning.mozilla.org/blog`

**Comment by hannahkane** [comment]
@cadecairos - woohoo! Thanks.

What do we need to test to make sure this is working properly?

**Comment by cadecairos** [comment]
@hannahkane 

Assuming the only links on the blog are to posts, and once I put a redirect in place, the best QA would be to confirm links to `blog.webmaker.org/{post}` redirect to the corresponding post on `learning.mozilla.org/blog/ {post}`

**Comment by hannahkane** [comment]
Thanks. Sorry, thought you were waiting for a 👍  from us, but sounds like you don't need anything from us just yet.

**Comment by cadecairos** [comment]
Yeah, I just wanted to make sure putting the redirect on blog.webmaker.org was 🚀 and not 👎 - it sounds like it's 🚀, so I'll try and get that done today, if all these meetings I'm in allow it!

**Comment by hannahkane** [comment]
Got it. Thanks for checking. 🚀

**Comment by cadecairos** [comment]
The blog is now live at https://learning.mozilla.org/blog/

There is an issue with post previewing, and it's due to the way things must be set up to have the blog served at `/blog/` I filed https://github.com/MozillaFoundation/mofo-devops/issues/423

I think we can consider this closed
