### ISSUE TITLE
Implement update to Club Captain application form

### ISSUE THREAD

**Issue by sabrinang** [mozilla/learning.mozilla.org#1857]
The design has been reviewed and finalized on https://github.com/mozilla/teach.mozilla.org/issues/1822 and the redpen mockups for the full width form can be found here: https://redpen.io/p/he4d93fc5a7a4e6b0b 

Form copy on page 8, 9 & 10 of https://docs.google.com/document/d/1Ds_uAJvuYa0ACLWmQfUukRHAyX5Stj_8AXGlPjTDW3Q/edit
<img width="1284" alt="screen shot 2016-05-05 at 1 33 20 pm" src="https://cloud.githubusercontent.com/assets/2492510/15056379/1cc5f756-12c6-11e6-8cc0-7907bab37a77.png">

**Comment by Pomax** [comment]
phrasing for "start a club": https://redpen.io/xk4479a493e5e366c6

**Comment by Pomax** [comment]
phrasing for "intergration...": https://redpen.io/cme3ec7caea6876211

**Comment by Pomax** [comment]
Looking at the comps we do not appear to have the SVG file for the clubs circle-with-gears, only that same logo with three markers attached to it. Do we have the "base" image somewhere?

**Comment by Pomax** [comment]
Looking at the "thanks for applying" last comp on https://cloud.githubusercontent.com/assets/2492510/15056379/1cc5f756-12c6-11e6-8cc0-7907bab37a77.png, we don't seem to be already using the icons indicated there, do we have those available somewhere?

**Comment by Pomax** [comment]
which link should be used for the "share your story" icon/text panel?

**Comment by sabrinang** [comment]
.svg file of cirlce line art: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eUkdVZF9vQ2prWVU/view?usp=sharing

We will be using links seen on https://learning.mozilla.org/clubs instread of mockup as they are more applicable links for clubs that what is seen on mockup (initally taken from community page)

**Comment by Pomax** [comment]
+1, added the changed into the `clubforms` branch

**Comment by Pomax** [comment]
@sabrinang @hannahkane do we want to keep the apply link in the sidebar nav menu, or should that be hidden and only reachable through the club page itself?

**Comment by sabrinang** [comment]
@pomax It could be a sub page from clubs but we do not have that level of navigation in the sidebar menu so it is probably only reachable through the club page itself

**Comment by Pomax** [comment]
@sabrinang looks like we don't have a comp for when a user tries to apply without being logged in, right now I have it implemented as an "obvious" but clearly suboptimal "please sign in" page, but if you have some good ideas around the design of that landing page I'll be happy to implement it.

![screenshot 321](https://cloud.githubusercontent.com/assets/177243/15692423/1e647f92-2743-11e6-82ac-15834eb147cd.png)

**Comment by Pomax** [comment]
@sabrinang the old (current) clubform has a website field, which I don't see anywhere in the new form, do we still want to add that a an optional URL field?

**Comment by sabrinang** [comment]
@pomax I have two ideas for the landing page if they are not signed in:
<img width="1266" alt="screen shot 2016-06-21 at 3 36 44 pm" src="https://cloud.githubusercontent.com/assets/2492510/16248746/004fe724-37c6-11e6-9266-578d37862b5d.png">
We can show the two options to log-in or create account buttons (https://redpen.io/vo22da3e4f1f7eef84)
We can surface the fields on the page itself to sign in directly so we don't redirect them off it but is this to complicated to do if we are still using id.webmaker.org system? (it still isn't an optimal experience seeing the webmaker login page) (https://redpen.io/tb1037839ba0c4a0e2)

**Comment by Pomax** [comment]
We can't really go with the right of the two options, since the login process is controlled by id.webmaker.org (we can only redirect users there with a callback argument so they end up back on the page they were on when they left).

**Comment by sabrinang** [comment]
Ok, we can go with the redirect option on the left then. I cleaned up the copy and made the create an account less prominent. https://redpen.io/vo22da3e4f1f7eef84
<img width="1102" alt="screen shot 2016-06-21 at 4 46 27 pm" src="https://cloud.githubusercontent.com/assets/2492510/16250311/3cf924be-37d1-11e6-8bcf-f537b00d0a6f.png">

**Comment by Pomax** [comment]
added into the PR

**Comment by hannahkane** [comment]
@Pomax - can you please provide an update on where this is going to be end of day today? Thanks!

**Comment by Pomax** [comment]
missed this message - we ran into setup issues a week ago, and Mavis was on PTO most of this week, so we're effectively still where we were in terms of schema change for the Teach API, although the outstanding design issues were solved; the "when not yet signed in" comp has been implemented and we're now adding a website field at the end of the second page of the form, but only when you're choosing the integrate your existing club, because you're likely to have one. A second person is required for testing though, especially with the parts of the Teach-API

**Comment by Pomax** [comment]
@sabrina we were missing a "description" field, which the current schema uses to pull as "what to show the user" for the clubs on the map and in the club listing. I'll add this into the second page, under the "what is your club name" field, as a textarea with the same restriction as the "reason to host a club" first page field, so that we have the same data available at least, and then we can decide whether to keep that in the form or add new functionality that lets users do club administration themselves later on.

**Comment by Pomax** [comment]
This work was merged in, with follow-ups filed for the (unsurprisingly!) follow-ups that we should now work on.
