### ISSUE TITLE
CMS related, what's the plan to avoid the flash of unrendered content

### ISSUE THREAD

**Issue by mmmavis** [mozilla/learning.mozilla.org#1863]
Currently if you visit a WP-powered page (for example, [this](http://teach-cms-enabled.herokuapp.com/3-column)) you will see a "loading" message while we are fetching data from WordPress.  @davidascher raised a good point that this breaks the illusion that this is a static website.

I'm filing this ticket so we can track our discussion. What are the way to narrow the gaps between WP-powered pages vs all other pages on the MLN site so they don't look "second class".

/cc @davidascher @Pomax

**Comment by davidascher** [comment]
I'll state an ideal scenario from my PoV:

A central endpoint finds out of any new or changed slugs from wordpress, based on (ideally) push signals and worse case scenario based on periodic pinging, and the rendering is done based on a non-WP-hosted API endpoint but an S3/cloudfront endpoint that we can optimize.  AKA: Pre-populate the cache, and invalidate on author edit based on wordpress signals.
