### ISSUE TITLE
Change the blurb at the top of the Mozilla Curriculum Workshop landing page

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning.mozilla.org#1864]
On the [MCW landing page](https://learning.mozilla.org/community/curriculum-workshop/), change

> Join us on the second Tuesday of each month at 8 PM ET!

to 

> Join us on the second Tuesday of each month!

Sound right, @KGorr?

**Comment by hannahkane** [comment]
Also on archived pages

**Comment by KGorr** [comment]
+1
