### ISSUE TITLE
Request for Hi-res Web Literacy Map file [for print]

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning.mozilla.org#1865]
We received this request from a web/print shop manager at Central Valley School District.

"I have a teacher/librarian who would like to print your Web Literacy wheel as a 24x36 poster to hang in the school library. Do we have permission to do that – and if so, do you have it a file format that will print well at that size?"

Any help is appreciated!

**Comment by jgmac1106** [comment]
Be pretty cool if it was an interactive pop up. Like if she could assemble
it so the skills.....I mean competencies....pull out from behind the
competencies...oops skills.

Snark aside, a printable puzzle would be a nifty idea.

**Comment by hannahkane** [comment]
That is a cool idea, @jgmac1106, but we likely don't have the capacity to prioritize it right now, unless a community member wants to volunteer for it.

@sabrinang - could we provide a high res version of the map for printing?

**Comment by jgmac1106** [comment]
Yeah but even a static will take some design resources as the competencies
don't show up unless you click on the skill...or you just print the circle
of skills.

@hannahkane might be something to throw to the design community group that
was spun up. Not sure if that is still a thing.

**Comment by hannahkane** [comment]
That's a good clarifying question for the requester. @KGorr—do you know if they were expecting to see all of the competencies as part of the poster?

I don't know much about the design community group. Will flag for @xmatthewx when he returns from PTO.

**Comment by KGorr** [comment]
Very good question. I just responded to the requester and will let you know what I find out.

**Comment by KGorr** [comment]
That was a fast response....she just wants what is in this screenshot. 
![screen-shot-2016-04-04-at-4 12 34-pm-600x317](https://cloud.githubusercontent.com/assets/14793388/15130376/c93ec5ec-15fc-11e6-9bfc-02df63a46955.png)

**Comment by hannahkane** [comment]
@sabrinang - do you think you'll be able to do this this week? If it's not a simple task, please let me know, and we can re-triage.

**Comment by sabrinang** [comment]
@hannahkane I shared the redpen on design crit today: https://redpen.io/p/hn2cc28e334ad1cc6e
I have some minor adjustments to revise it but it is a simple task. 
@KGorr Let me know if you have any feedback on the redpen as well!

**Comment by KGorr** [comment]
Looks great to me. Thanks!

**Comment by KGorr** [comment]
I imagine that a request for a PDF version of the map makes sense to be linked to this request: https://twitter.com/rjmama/status/734551599620722688 Let me know if I should file a separate ticket.

**Comment by hannahkane** [comment]
We should also add a link to /web-literacy on the Learning site as well.

**Comment by KGorr** [comment]
Hello! Any progress to share here? The person who requested the print file has asked for an update. :)

**Comment by sabrinang** [comment]
The 24 x 36 inch poster is exported as a .pdf and .png here: https://drive.google.com/a/mozilla.com/folderview?id=0B4Q8pzCpDS_eT1ZpcE56dmxDX3M&usp=sharing
<img width="711" alt="screen shot 2016-05-31 at 9 55 39 am" src="https://cloud.githubusercontent.com/assets/2492510/15683174/dfce64f0-2715-11e6-9be6-bddf491080fc.png">

**Comment by KGorr** [comment]
Perfect - thank you!

**Comment by anmechung** [comment]
Looks great - I think @chadsansing and I can use this at some upcoming web literacy trainings too.

**Comment by chadsansing** [comment]
#yesindeed

**Comment by hannahkane** [comment]
Cool. Thanks, @sabrinang! Closing this, and opened a [separate ticket](https://github.com/mozilla/learning.mozilla.org/issues/1885) about adding a link to the site.
