### ISSUE TITLE
Email sign up text needs updated

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning.mozilla.org#1871]
When you sign up for the newsletter via https://learning.mozilla.org using the "get email updates" box, it prompts you to share on Twitter after you've signed up. The suggested text in the tweet uses teach.mozilla.org.

Also, on the community page, the email sign up call out references "MLN Community Newsletter" and should be “Mozilla Learning Newsletter”. Right, @ldecoursy? (I can move this to a seperate ticket if these need to be filed as two to-dos.

**Comment by ldecoursy** [comment]
Correct on point two!

Good catch on both :)
