### ISSUE TITLE
Broken Links on the Clubs page

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning.mozilla.org#1872]
I know the Clubs page is getting a refresh, but I found these issues and thought I should report to the team:

http://mozilla.github.io/learning-networks/clubs

* Under “For Club Captains”, the “writing a blog post,” “PR guide,” and Social media guide” hyperlinks are duplicated and thus not working
* Under “For Regional Coordinators,” “Regional Coordinator Community Calls” link is not working (not sure what issue is on this one)

**Comment by hannahkane** [comment]
Thanks for noticing, @KGorr.

I fixed the three under "For Club Captains," but I don't know what the link should be for Regional Coordinator Community calls. @amirad @carotejada - can either of you provide the link?

**Comment by KGorr** [comment]
Thanks so much @hannahkane! I found the RC comm call etherpad: https://public.etherpad-mozilla.org/p/teach.clubs-rccalls

**Comment by hannahkane** [comment]
Thanks, @KGorr. Fixed.
