### ISSUE TITLE
Interim l10n solution: Club Guides and Activities

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#1873]
Localizing the Learning site (or at least major parts of it) is a priority for H2, but we'll need time to build the infrastructure.

In the meantime, we already have linked content that's been localized—specifically, we have Club guides and Teaching Activities. Let's brainstorm some possible interim solutions for making this content discoverable.

Background:
 * The EN Club Guides are currently accessed via this [github page](http://mozilla.github.io/learning-networks/clubs/), which is linked to from learning.mozilla.org/clubs. However, we expect to retire that github page shortly, and instead link to the Guides directly from learning.mozilla.org/clubs (see design work in progress [here](https://github.com/mozilla/learning.mozilla.org/issues/1605)). Our interim solution should be reflective of the upcoming changes.
 * Teaching Activities are github pages, and, where we have localized versions, they are accessible from the page itself. See [Kraken the Code](https://mozilla.github.io/mozilla-club-activity-kraken-the-code/#en) as an example—look in the top right corner. (Note: we know we need to update the page layout to match the [most recent iterations on the template](https://github.com/mozilla/learning.mozilla.org/issues/1850)).

So the challenge is to figure out how to make people aware of localized content where we have it. I don't think ideas need to be limited to on-site changes. 

Thoughts? @sabrinang @flukeout @Pomax @xmatthewx @simonwex @soapdog @amirad @carotejada @chadsansing

**Comment by chadsansing** [comment]
Perhaps develop a second 'educators toolkit' to send to the same list @KGorr compiled for the original and blast this one throughout Clubs channels, as well.

**Comment by amirad** [comment]
For the new club resources page that will have other language tabs, can the translated resources and curriculum live there?

**Comment by hannahkane** [comment]
@chadsansing - I'm not sure I understand your comment. What would the purpose of the educators' toolkit be?

@amirad -  in the [latest design](https://redpen.io/nw7e55e75c539e6e9f) there aren't tabs for additional languages. That is one possible solution, but I'm not sure it's adequate. I'm not totally sure about the use case. Will the person browsing the page be an English reader? If so, that could work. But, if not, why are they on the page in the first place? Maybe this idea when coupled with a multi-lingual email campaign could work?

**Comment by KGorr** [comment]
@hannahkane, I think Chad is suggested that we create a "find localized resources" kit (similiar to the web lit kit) that will provide an overview of what is available in various languages and how to find it. I personally like the idea, as it puts the info in one place and makes it easy to distribute broadly. I would be happy to help if that is a direction the team wants to go.

**Comment by Carotejada** [comment]
@hannahkane @amira when planning this resources sub-page @sabrinang and I talked about including a searching option with filters. This is ideal since we have a growing number of guides and resources in different languages. Are we still considering this option?

**Comment by chadsansing** [comment]
@hannahkane - what @KGorr said :)

**Comment by hannahkane** [comment]
I'm going to suggest we talk about this in person in London, as part of a larger conversation about solving problems for CCs and RCs. Stay tuned for more info!

In the meantime, would love to hear more about the "find localized resources" kit idea. Would that be about finding Mofo-specific resources—sort of a regularly updated index of content we produce? Or would it be tips for finding web literacy-related resources in your language/locale, more generally?

**Comment by KGorr** [comment]
@hannahkane - my thoughts are that it would be most effective to have both the general tips for finding web literacy-related resources in your language/locale AND instructions for finding localized Mozilla's resources. For the former, perhaps we could reach out to those that we know use our localized content/are involved in the process with us, and see what tips they can share. @soapdog is probably a great person to help with this too.

**Comment by soapdog** [comment]
Hey friends, I believe that kits such as "find localized resources" are only useful if done in a non-English language by a native speaker of that language and has links to localized content beyond what we offer in our sites. 

It is my opinion that the L10N offers on our sites should not require a guide to find, if they do, then we're doing something wrong with our navigation. If a CC goes to our site hoping to find localized material and need a guide to do so then I believe they will simply leave. We have great examples of L10N enabled sites at mozilla such as MDN where language detection already drives the user towards localized material whenever possible while also allowing explicit choices from dropdowns on all pages.

Still a guide that summarizes it all while also pointing to potential useful resources on that language from partner or similar organizations might be a good idea.

**Comment by soapdog** [comment]
I would love for us to discuss L10N in London too.

**Comment by KGorr** [comment]
Hi @soapdog - so I think you are saying that if we do a kit, it needs to be in multiple languages and tailored to each culture. Is that correct? If so, I agree 100%, and wonder if our team creating one in english will be a good jumping off point for volunteers to localize/customize the kit for their specific language/country/culture.

RE: our website nav, as an example, a kit/guide would address the thimble localization as well as curriculum localization resources. Right now, localized thimble doesn't point to localized curriculum, which a kit/guide could help with. In general, I'm thinking this kit/guide could be a first-time user document only - not something that needs consulted every time our site is used to find localized content.

My two pennies :)

**Comment by hannahkane** [comment]
Thanks for the brainstorm everyone! I think we've identified at least a few possible solutions. 1) Provide a resource to help people source local content. 2) Have a good on-site solution based on browser locale detection + language selector. 3) Add localized curriculum to localized Thimble. 

I'm going to close this ticket and open tickets for #2 and #3 above. I'll leave it to others to decide whether to open a ticket for #1.

Anyone who's interested in this topic should feel free to join the "Scaling On-the-Ground Impact" group during the MLN Production Breakout Group sessions on the Wednesday in London. Stop by any time between 11am and 2:30pm on that day. Localization is one of a few key topics we'll be discussing.
