### ISSUE TITLE
June update to Curriculum Workshop page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#1874]
### Info needed

 - [ ] Confirm accuracy of: 
 * June 14, 2016 - 10am PT / 1pm ET / 5pm GMT
 * Summer Learning
 * Join co-hosts Amira Dhalla and Chad Sansing broadcasting live from Mozilla's all-hands work week. Invited guests and drop-in Mozillians will talk shop about summer learning and curriculum development for the web.
 - [ ] Guest names
 - [ ] YT embed
 - [ ] Etherpad link
 - [ ] July title, date, time, and description if known

**Comment by hannahkane** [comment]
@chadsansing @amirad

**Comment by amirad** [comment]
@chadsansing did we confirm that time or is it going to be during the elective times instead?

**Comment by chadsansing** [comment]
Working on landing the copy, embeds, etc. next week, @hannahkane. Thanks for the ticket!

We have changed the time to 5-6 PM local, 4-5 PM GMT on Thursday the 16th since no MoFos have to run electives during that block.
