### ISSUE TITLE
Design 14 Open Leadership Diagrams

### ISSUE THREAD

**Issue by sabrinang** [mozilla/learning.mozilla.org#1875]
Create 14 diagrams before London all-hands based on drafts:
6 Diagrams for [Github Set Up](https://docs.google.com/document/d/1qB9JuJ3a2f-fsLX8s8m6uzhi1RHg-WkcstnUJ1UtP0c/edit)
6 Diagrams for [Github for Collaboration](https://docs.google.com/document/d/17xwoJRaFEe6VYI2dm9c1grVy4OzJduyVBz0_f0RBzI4/edit)
2 Diagrams for [Convening an Open Event](https://docs.google.com/document/d/17OsBDxSg2f5LURCmp3OSchVy0uLegC8pWVbZMcGpFk4/edit)

These diagrams will be created by:
- establishing set of colours, image proportions and illustrative style to make it stand out from text
- using yellow as highlight, annotation and call out elements
- keeping as much text on template rather than images so captions are searchable, localizable etc.
- thinking about potential foxes to be kept in sidebar area
- reviewing that the visual content itself is understandable and appropriate

These diagrams are a good example of how we can incorporate new style features in the template itself and [think about a diagram system](https://docs.google.com/presentation/d/1hwaiFbJr9ow5WbrAiooK1hGoV4q7hyw5AgngfWVw7hg/edit#slide=id.g140e8379f1_0_5) afterwards while keeping a unified, repeatable approach in mind.

cc/ @chadsansing @zee-moz @hannahkane

**Comment by sabrinang** [comment]
Using unified palette, simple figures and [icons](http://linea.io/) to create first set of ideas for 6 diagrams for Github Set Up. See redpen: https://redpen.io/hn4718496d3a350e50

**Comment by hannahkane** [comment]
I know you'll review these at design crit, but just wanted to say I think these are really cute! @sabrinang - do you want specific feedback from anyone at this point?

**Comment by sabrinang** [comment]
@hannahkane Yes, everyone feel free to leave comments on the redpen for design or content etc.

**Comment by hannahkane** [comment]
cc @chadsansing @zee-moz

**Comment by chadsansing** [comment]
My email and password reset are not playing nicely redpen, but my only additional suggestion right now would be to add sequential markers (like arrows) in the illustrations that show sequences instead of 3 different things/states.

**Comment by sabrinang** [comment]
I updated more diagram ideas on the redpen: https://redpen.io/p/xc69d2dc74df0c96c3

@chadsansing Can you explain a bit more where to add the sequential arrows? I'm a bit confused where to add them

**Comment by chadsansing** [comment]
I think illustrations 2 could use something to indicate the user is drilling down from folder to editing to seeing tracked changes. I think illustration 4 could use some indication of sequencing, even though you can go backwards, as well as forwards, and I think illustration 6 need to indicate who does what when - I think the GitHub circle timeline marker is too abstract for new users on its own.

**Comment by chadsansing** [comment]
I dig the map illustrations in design 3 muchly; maybe make the person a fox to match the other illustrations?

**Comment by sabrinang** [comment]
Revised Redpen Iterations: https://redpen.io/p/xc69d2dc74df0c96c3

Exported Diagrams here: https://drive.google.com/open?id=0B4Q8pzCpDS_eOGxtQzJRMDgzczA

Illustrator file here: https://drive.google.com/open?id=0B4Q8pzCpDS_eWXVwV1lPQTlxS0E

For Set 2, there are some variations in the layout that I didn't know which one was the best to export but let me know if you have feedback in the redpen and the illustrator file includes all iterations to export from as well.

(Note: I'll be away on PTO next week)

**Comment by hannahkane** [comment]
@chadsansing @zee-moz - are you happy with the diagrams? Do you need any additional follow-up on this ticket, or can we close?

**Comment by zee-moz** [comment]
I think they are great! Done for this heartbeat.

**Comment by chadsansing** [comment]
Ditto.

**Comment by hannahkane** [comment]
Fantastic! Thanks, all.
