### ISSUE TITLE
(on or after May 23) Update @MozTeach reference in Learning site footer

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning.mozilla.org#1877]
After the twitter handle change has been made on Monday, May 23, @MozTeach references (https://twitter.com/MozTeach)  needs to be changed to @MozLearn (https://twitter.com/MozLearn) on the learning site.

**Comment by KGorr** [comment]
@hannahkane, the switch to @mozlearn has been made, so the footer can change at any time. Thanks!

**Comment by hannahkane** [comment]
@Pomax - is this something I can do? Does it just require changing TWITTER_LINK and TWITTER_HANDLE in the config.js file?

**Comment by Pomax** [comment]
Yep, that should be sufficient - if you do update config.js it would be useful to also alphabetically order the export fields so that future updates are a little easier.
