### ISSUE TITLE
Kraken the Code tip sheet - 404

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning.mozilla.org#1878]
[This tweet](https://twitter.com/whistlerlisa/status/734529897318649856) came in over the weekend.

The Kraken the Code [tip sheet](https://mozilla.github.io/mozilla-club-activity-kraken-the-code/legit-o-meter.html) isn't working. It's link is found in the 2nd paragraph under "Kraken the Code: Hunt" section.

**Comment by hannahkane** [comment]
Anyone know where the tip sheet actually is? @chadsansing @soapdog @amirad?

**Comment by soapdog** [comment]
Merged! :D
