### ISSUE TITLE
Review and Edits for guide on How to encourage a collaborative approach to running your club

### ISSUE THREAD

**Issue by soapdog** [mozilla/learning.mozilla.org#1879]
# Description
There is a new guide on collaborative techniques for running clubs. This content is great for CCs as it give them tools and frameworks for running clubs in a collaborative way.

This guide is being written by Hélène Petry, the collaborative techniques expert from Rio. I believe it has reached the point where it can benefit from @KGorr edits and review. It is not complete yet but we already have a lot of content.

URL: https://docs.google.com/document/d/1v4Rn7MVTMUtR40Ye_SUAXfxzdVPZpHgSma7PSAV3m3s/edit?usp=sharing

**Comment by soapdog** [comment]
cc @amirad

**Comment by amirad** [comment]
Will wait until @KGorr is done before giving it a look over!

**Comment by KGorr** [comment]
Thanks, @soapdog. Happy to help. I've put it on my list of things to do this week and will let you know once I've taken a look.

**Comment by KGorr** [comment]
@soapdog - OK, finally got through it all. I left a lot of comments, take them or leave them! :) Hopefully they are helpful.

**Comment by soapdog** [comment]
@KGorr thanks a lot for the comments! Hélène will check them out as she is the expert writing this, I am also commenting 🐹

**Comment by hannahkane** [comment]
@KGorr - any thoughts on what to do with this ticket?

**Comment by KGorr** [comment]
@hannahkane - I never received confirmation that it the content was finished, but I know it was close. @jvallera - did you discuss his open club guides with @soapdog before he left as staff? I think there were a few of them. I'm happy to help put them into our guide template if needed. Thanks!

**Comment by jvallera** [comment]
I did not talk to @soapdog about this before he left. It looks pretty complete to me. what do you think @KGorr? If so, would love to move it into a guide template.

**Comment by soapdog** [comment]
@soapdog is a mention away! I believe the content is ready to be moved into the template. I can find the pictures to match the text and send a pull request later. What do you think?

**Comment by jvallera** [comment]
Yay! @soapdog that sounds great! Do you think is easiest to just put the pictures directly into the google doc where they should go? I am not sure I would know where they fit in with the text.

**Comment by soapdog** [comment]
I think it is better to move it into the template first and then spice it up with pics as needed. Moving photos out of google docs is kinda funky.

**Comment by jvallera** [comment]
ok, that makes sense @soapdog. @KGorr do you have time to move into a guide template? If not I will put it on my list for early September.

**Comment by KGorr** [comment]
@jvallera, I should have bandwidth. I'll add it to my list and will let you know if anything changes. Thanks!

**Comment by KGorr** [comment]
Guide is put into template here: http://mozilla.github.io/learning-networks/clubs/collaborative-learning/index.html I'm having trouble pulling the images from the word doc, so just wanting on those to be sent to me via gdrive. Closing this ticket since the content is ready to go.

**Comment by jvallera** [comment]
Thanks @KGorr ! I will add it to the website once the backend is ready for us to add guides (soon!).
