### ISSUE TITLE
Final @MozTeach reference updates

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning.mozilla.org#1880]
These few resources need to be updated with @MozLearn, https://twitter.com/MozLearn:

- [x] https://support.mozilla.org/en-US/kb/how-can-i-get-help-my-thimble-project
- [x] https://support.mozilla.org/en-US/kb/how-can-i-get-help-my-x-ray-goggles-project
- [x] http://mozilla.github.io/learning-networks/clubs (footer)
- [x] http://mozilla.github.io/learning-networks/clubs/regional-coordinator.html (footer)

@hannahkane

**Comment by hannahkane** [comment]
done

**Comment by KGorr** [comment]
Whoops - sorry @hannahkane! Forgot to include the biggie - the main https://learning.mozilla.org footer (affects multiple pages)

**Comment by KGorr** [comment]
OOOOohhhhhhh wait. I opened a different ticket for that. (face palm). Sorry! :) Closing again.
