### ISSUE TITLE
Replace homebanner banner with MozFest call for proposals

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#1892]
It's time to replace the ENCRYPT banner on the homepage with a banner promoting the MozFest call for proposals. 

@edrushka @Saallen @xmatthewx - do you think it would be alright to use the same banner as last year? https://github.com/mozilla/learning.mozilla.org/issues/1099

Would you want to change the wording at all? Perhaps to call attention to the multi-lingual submission process?

Banner CTA should link to https://mozillafestival.org/proposals

**Comment by xmatthewx** [comment]
@hannahkane - works for me. Any opinions on the [red banner design](https://github.com/mozilla/learning.mozilla.org/issues/1099#issuecomment-125786770) @kristinashu @sabrinang? Still work well?

**Comment by Saallen** [comment]
Hey @hannahkane , last years banner works for me. 
Can we update the wording this year to 
*The world’s leading event for and by the open Internet movement.
Join us to build, debate, and explore the future of our lives online.

**Comment by kristinashu** [comment]
Last years banner looks good to be. I would just recommend using the more muted red #E12526 that is on the MozFest site and the schedule app.

**Comment by hannahkane** [comment]
Thanks, @xmatthewx @Saallen and @kristinashu. I'm going to assign @sabrinang to make these modifications soon after London.

**Comment by sabrinang** [comment]
Redpen here: https://redpen.io/p/gh4cff083bea92a46a
It includes a version with colours of the current 2016 colours seen on https://mozillafestival.org/ (purple/pink gradient) or a version with unified red colour (#D24735)

**Comment by hannahkane** [comment]
Thanks, @sabrinang.

I like the gradient. @xmatthewx - what do you think?

**Comment by xmatthewx** [comment]
I've got feedback on two levels. 

#### Get it done
If we just want to get this done and move onto the next thing...
 - The gray background seems slightly out of sync. Not critical, but you might try the light blue used further down the page.
 - The paragraph is aligned to the top of the logo, but floats oddly. Try alignment with "mozilla" or "festival" instead. Optically, alignment with x-height might look better than top of the tall characters. 
 - There's too much copy for internet eyeballs 👀. Try a shorter more catchy statement in larger type.  
  -  ~~The world's leading event for and by the open internet movement. Join us to build, debate, and explore the future of our lives online.~~
  - The world's leading event to build, debate, and explore the future of our lives online. 
  - Join us to build, debate, and explore the open internet movement.   

#### Make it sing
The current and new banner ad look like part of the site, and might be confusing to new visitors who haven't read the about text. 
 - Consider a margin around the background color to make it look more like a banner ad (and less padding on top and bottom)
 - Consider placing it below the About Us block

**Comment by hannahkane** [comment]
I think we need to get this done and move on, so I'd suggest we make the minor changes @xmatthewx recommends and push it live.

**Comment by sabrinang** [comment]
Updated redpen: https://redpen.io/tg854590662134c6f8 
I think we we're leaning towards a neutral grey shade in the UI (seen on newer unified properties) so the logos can be whatever colours above it so I think instead  updating the light blue shade below would fix the out of sync feeling. I aligned the text to match "mozilla" baseline and used shorter text "The world's leading event to build, debate, and explore the future of our lives online."

https://redpen.io/of1e49bdfdc83b0a20 If it is placed below the "About Us" section it feels more integrated into the site and it feels like it breaks up flow of learning content.

**Comment by hannahkane** [comment]
Nice!

**Comment by Saallen** [comment]
Hey, thanks for the update @sabrinang - one thing I noticed when looking at the two redpens was that when the MozFest banner was above the ABout us, I though the About was referencing MozFest-

**Comment by sabrinang** [comment]
Updated redpen: https://redpen.io/zcd9175df07bdc2b9e

<img width="967" alt="screen shot 2016-07-04 at 1 46 35 pm" src="https://cloud.githubusercontent.com/assets/2492510/16569657/c9aa7586-41ed-11e6-995c-1ed79b78e553.png">

- fixed alignment of banner as well as about us section and cta buttons on homepage
- placed below about us and included margin around the grey bg to make it look more like a promo ad

**Comment by xmatthewx** [comment]
Great iteration. I think if we vertically center the paragraph with the logo and gray box, this is good to go.

**Comment by sabrinang** [comment]
Updated redpen: https://redpen.io/zcd9175df07bdc2b9e with vertically centered paragraph

**Comment by hannahkane** [comment]
Thanks, @sabrinang. I think it looks really good.

If you're happy with this, could you please file an implementation ticket with the design assets?

**Comment by sabrinang** [comment]
Closing this issue and implementation ticket opened (#1924)
