### ISSUE TITLE
Move legal language above the Newsletter sign-up box

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#1894]
On the community newsletter page (https://learning.mozilla.org/community), the line “I’m okay with you handling this info as you explain in your privacy policy” needs to be above the text box, for legal reasons.

Also, the "privacy policy" font seems to have gotten unnecessarily large.
![screen shot 2016-06-08 at 9 13 39 pm](https://cloud.githubusercontent.com/assets/8389648/15918673/118a2386-2dbe-11e6-8e0f-921a51b6568b.png)

**Comment by hannahkane** [comment]
@kristinashu points out we should also change this on the homepage lightbox

**Comment by mmmavis** [comment]
Hey @Pomax I don't have badges set up on my machine otherwise I would fix it myself. Do you mind fixing the location of the privacy policy notes on `CredlyLinkForm.jsx`? 😄

**Comment by hannahkane** [comment]
This is done.
