### ISSUE TITLE
Mozilla Clubs Updates

### ISSUE THREAD

**Issue by sabrinang** [mozilla/learning.mozilla.org#1904]
We are updating learning.mozilla.org/clubs and this issue is to keep track of questions and ideas.

**Design**
Is Mofo Bootstrap implemented when we redesign the whole learning site? or can we start integrating some united mofo styles as we update clubs?

**Development**
How do we build the pages so resources (Running your Club) are easily updatable by staff?
~~How can we build the testimonial slideshow?~~
How can we build featured updates so it is showcasing new content dynamically?

**Club Captain Application Form**
~~The form is in progress of being implemented https://github.com/mozilla/learning.mozilla.org/issues/1857~~
Can we improve the sign in experience? (still isn’t optimal via id.webmaker.org system)

**Clubs Map & List**
How can we showcase clubs in a useful way? (perhaps search, filter etc.)
How can we unify this system with other hubs? (study groups for science etc.)
How do we display the list when it is separate page on the navigation? (reconsider site IA)

**To Do**
When this page is live, how do we sunset or clean up resources found in other locations? (factsheet http://mozilla.github.io/learning-networks/clubs/)
Do we have a clubs email or do we need to create one for inquiries?

This issue can turn into actionable items as questions are discussed and planned out.

**Comment by hannahkane** [comment]
Fantastic ticket. Thanks, @sabrinang.

**Comment by hannahkane** [comment]
Design work is here: https://redpen.io/p/rb14e4c0eb3594f430

**Comment by hannahkane** [comment]
Removing this ticket from the milestone, since we've released the relevant work for this heartbeat. Ticket has useful questions/TODOs in it, though, so preserving for future iterations.

**Comment by hannahkane** [comment]
Closing this, as we won't be working on Clubs anymore until we have a plan for the pan-Mozilla Clubs platform.
