### ISSUE TITLE
Enable /codemoji

### ISSUE THREAD

**Issue by mmmavis** [mozilla/learning.mozilla.org#1913]
<img width="671" alt="screen shot 2016-06-28 at 12 48 38 pm" src="https://cloud.githubusercontent.com/assets/2896608/16430117/e827e962-3d2e-11e6-9169-27dbbf754967.png">

This currently gives 404. We should enable that route on learning.mozilla.org soon.

/cc @hannahkane

**Comment by cadecairos** [comment]
This was turned off using cloudfront - we're actively working on a bug fix right now, and will bring it back online ASAP
