### ISSUE TITLE
Update Gigabit T&C and Application Template 

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#1922]
Two tasks:

1. Update the [Mozilla Gigabit Community Fund Rules, Terms and Conditions](https://www.mozilla.org/en-US/gigabit/terms/ to reflect current terms) page to reflect the [latest draft](https://docs.google.com/document/d/1wxUa68ynmhCoWELIkYSkhE1QwUG0M7jPVK7kRM2O6LA/edit#heading=h.r1todfl5yrnf)
2. Change the link to "Handy Template" in the "How to Apply" section of [this page](https://www.mozilla.org/en-US/gigabit/apply/) to [this pdf](https://drive.google.com/file/d/0B9NqWPTRsfNXNjlKT0tMVlcySlhfZmVlQTBINXVrN0FSVlI0/view)

cc @jenntbeard @LindseyFrost

**Comment by alanmoo** [comment]
Where can I find the diff on the terms?

**Comment by hannahkane** [comment]
Whoops. Forgot they weren't actually attached. Just emailed to you, @alanmoo.

**Comment by alanmoo** [comment]
@jenntbeard - for the header, should it remain 2 lines as it is, just removing the word "Rules"? Or should it become one line?

**Comment by alanmoo** [comment]
Tracking in https://github.com/mozilla/bedrock/pull/4219
