### ISSUE TITLE
Implement homepage promotion banner: MozFest call for proposals

### ISSUE THREAD

**Issue by sabrinang** [mozilla/learning.mozilla.org#1924]
Replace the ENCRYPT banner on the homepage with a banner promoting the MozFest call for proposals. 
<img width="1295" alt="screen shot 2016-07-07 at 3 37 35 pm" src="https://cloud.githubusercontent.com/assets/2492510/16672111/c454bfa2-4458-11e6-8604-323060a62687.png">

See redpen: https://redpen.io/zcd9175df07bdc2b9e

**Copy:** The world's leading event to build, debate, and explore the future of our lives online. 
**Copy CTA:** Learn more
**CTA Link:** https://mozillafestival.org/proposals
**MozFest wordmark:** https://drive.google.com/a/mozillafoundation.org/folderview?id=0B4Q8pzCpDS_eelFIZWxzb05CdlU&usp=drive_web&ddrp=1#
**Background Colour:** #f1f1f2 (unified light grey)

Based on copy and design updates from #1892

**Comment by mmmavis** [comment]
@sabrinang `#f1f1f2` isn't being used anywhere on the Learning site. Is this a new shade we like to introduce?

**Comment by mmmavis** [comment]
Other than replacing the promo banner with MozFest promo, does this ticket also include layout / alignment adjustment on the homepage?

**Comment by sabrinang** [comment]
Hey @mmmavis I believe the unified mofo palette is not used on the Learning site currently and that is where the shade is from. At this moment, we can use the existing grey that is live (used with current encryption banner) so we are not introducing another shade yet until we redo the colours of the site would be a better approach.

There are additional design tweaks made from the feedback as this banner was updated but the following are NOT blockers for this implementation ticket:
- for the quote section near the bottom, the shade of light blue is changed to light grey since they are close and going towards more neutral greys for bg colours 
- for the buttons, left and right margins are aligned to the rest of the page
- for the about us section, this can ignored as the image would be very large at 3-col width that takes up a lot of vertical height and the text would be short creating a gap

If you can make these design adjustments when you implement this that would be great but feel free to file a separate ticket for the design tweaks.

**Comment by mmmavis** [comment]
@sabrinang thanks that's helpful

can you provide the colour code of the background colour on the quotes section? Is it the same as what we used on the promo banner? ---> `rgba(77, 78, 83, 0.1)` which is `#4D4E53` with opacity set to 10%.

**Comment by sabrinang** [comment]
@mmmavis Yes, please change quotes section `background: #EBF2F5` to the grey seen on promo banner `background: rgba(77, 78, 83, 0.1)`

**Comment by mmmavis** [comment]
@sabrinang 👍

**Comment by hannahkane** [comment]
@mmmavis - do you have everything you need to land this?

**Comment by mmmavis** [comment]
hey @hannahkane I had a [PR](https://github.com/mozilla/learning.mozilla.org/pull/1963) up 2 weeks ago. Sorry just didn't know who to flag for review.

**Comment by mmmavis** [comment]
@hannahkane this has been pushed to staging. It will be live on the next push to production (not too sure who I should flag on this... @Pomax ? or someone else? )

**Comment by hannahkane** [comment]
thanks, @mmmavis/

@pomax @gvn @gideonthomas @flukeout - can we do a push to production soon?

**Comment by gideonthomas** [comment]
@hannahkane I can do one tomorrow

REMINDER: @gideonthomas

**Comment by hannahkane** [comment]
@mmmavis - so I'm afraid we've missed the window for the call for proposals. Can we change the link to just go to the MozFest website instead? I think the image can stay the same.

**Comment by mmmavis** [comment]
@hannahkane oops kk I've open a ticket for it: https://github.com/mozilla/learning.mozilla.org/issues/2034
