### ISSUE TITLE
Kick off Learning site localization project

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#1926]
This is a placeholder or parent ticket to track localization work. 

Specific tickets to be provided by team. :)

**Comment by Pomax** [comment]
do we want to do an initial blanket-copy of the issues identified in the https://etherpad.io/localecakes document?

**Comment by hannahkane** [comment]
Going to close this issue in lieu of an epic (zenhub ftw!). Will add the issues from the etherpad. Thanks!
