### ISSUE TITLE
Learning Site Localization

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#1927]
Specific tickets to file: 

- add react-intel to all files that are user-facing  - client/server
- add user controls (UI) for switching locales - client (server?)
- add a CTA to help localise for incomplete locales - client (server?), documentation, process
- document how to add localisation to code - documentation
- document pontoon usage - documentation
- determine how to deal with server-side rendered localised pages (to serve as static content) - client/server
  - document how to deal with server-side rendered localised pages (to serve as static content) - documentation
- determine where to host all the documentation - process
- load pontoon locale data into code files - client/server
- determine strategy (if any) for dealing with caching of localised pages - devops
  - user loads page with locale X, then later resumes with locale Y, (etc) what happens - process, documentation 
- add CSP rules for pontoon to communicate with the app for iframe related - server/devops
- add CSP rules for pontoon to communicate with django, if necessary - server/devops
- determine how (and how often) to grab pontoon locale data during dev building and testing - developer sanity
- add tests/test framework that can catch not-locale-based strings - server
- add localisation coverage testing - server
- email Moco's team to add the project to the list on Pontoon - process, moco-collab
- determine localisation effort in django - process, moco-collab
- determine locale model information for structured data - django
- determine whether we need any localsation for django views we use (if any) - process
- determine a locale priority ordering (which languages do we focus on first) - process, documentation
- determine how to localise activities (user-generated teaching activities etc) - process <- **(hannah) recommend removing from this project, and passing to Scaling Impact team to do as part of curriculum platform project**
  - which technologies can be used for this (django, custom code? unknown) - unknown
- determine how to user test localisations - process
  - document the user test requirements - documentation
- how to get locale data into staging - CI, process
- how to get locale data into production - CI, process
- determine when a locale is ready for "exposing to the world" on production  - process, documentation
- setting up CI testing for client/server 
- setting up CI testing for django server (if we do localzation there)

**Comment by alicoding** [comment]
Moving the meta ticket to the next heartbeat since the rest of the tickets here needs more work 👍

**Comment by hannahkane** [comment]
Closing, though two UI tickets will remain open
