### ISSUE TITLE
determine a locale priority ordering (which languages do we focus on first) - process, documentation

### ISSUE THREAD

**Issue by alanmoo** [mozilla/learning.mozilla.org#1935]

**Comment by alicoding** [comment]
At this point we don't have any final data as to what locale we want to focus on, but we might be testing with few locales that got most translation done on Pontoon and see how well we'll get feedback from our users.

**Comment by hannahkane** [comment]
Another note from the meeting yesterday - we could prioritize the same locales we focused on when we did the localization push for the Web Lit Basics module:

    Bengali / বাংলা
    Dutch / Nederlands
    Filipino / Pilipino
    German / Deutsch
    Gujarati / ગુજરાતી
    Hindi / हिन्दी
    Indonesian / Bahasa Indonesia
    Portuguese / Português
    Spanish / Español
    Swedish / Svenska

But I think for the light site translation, you're right that our best bet might be to gauge contributor interest in Pontoon. (As opposed to launching another coordinated outreach push to Mofo communities right now.)
