### ISSUE TITLE
determine how to localise activities (user-generated teaching activities etc) - process

### ISSUE THREAD

**Issue by alanmoo** [mozilla/learning.mozilla.org#1936]

**Comment by alicoding** [comment]
At this point it seems like we're going to let the people (contributors/staff/reps etc) to decide whatever platform they wanted to use to create their teaching activities, but the important part here is collecting them with its meta data (image, descriptions, title etc) and put them into some sort of DB or place like django to fetch them into the site.

**Comment by hannahkane** [comment]
+1 to this. A piece of meta data we should store is the locale, so we can show people relevant content. We should also consider using the Web Literacy Map skills/competencies as a canonical tagging system across all locales. That way, each locale can build up a directory of locale-specific activities linked to the various skills on the map, which is, aside from the Activities page on the site, the main way we currently offer to navigate teaching content. 

I wonder if the database should store information about the relationship between teaching activities in these ways: 
 1) Localization: Activity A is a Spanish translation of Activity B.
 2) Remix: Activity X is a "For ages 12-15" remix of Activity Y.

These would provide a useful discovery tool for users. 



Will just add that making it easier to create/publish teaching activities is on the Local Impact team's roadmap, and we will likely make localization a requirement for that work.

**Comment by alicoding** [comment]
We should carry our discussion regarding what should our database store information in the implementation ticket, so closing this one 👍
