### ISSUE TITLE
Load pontoon locale data into code files

### ISSUE THREAD

**Issue by alicoding** [mozilla/learning.mozilla.org#1951]
Pontoon data files are not react-intl compatible and we have to convert from `.properties` to `.json`. We have done it on donate.mozilla.org repo and probably can copy the code from there.

**Comment by alicoding** [comment]
https://github.com/mozilla/donate.mozilla.org/blob/master/scripts/properties2json.js

**Comment by alanmoo** [comment]
Happens during build step
