### ISSUE TITLE
Document the process for locale negotiation 

### ISSUE THREAD

**Issue by alicoding** [mozilla/learning.mozilla.org#1953]
user loads page with locale X, then later resumes with locale Y, (etc) what happens - process, documentation.

**Comment by alanmoo** [comment]
I'm not sure I understand the issue with changing locales- shouldn't it just load the page in the new locale?

**Comment by alicoding** [comment]
No issue here, but we want to document how we are dealing with this. Like, we are looking in their navigator.language and lookup in our supported locales etc.

**Comment by alanmoo** [comment]
Ah. I'd expect 2 things:

* If they don't have a locale in the URL, we direct them to one we deduce based on `navigator.language`
* If they do, show them that locale.

Possible future enhancement that we might want to flesh out: we do some checking, if it's either their first visit or if the locale doesn't match their set one, we let them know if we do offer their locale?

**Comment by alicoding** [comment]
After you have #1958 implemented this ticket is to document what was implemented there and I agree and expect these to happens in that implementation (sorry if I repeated what you've said above)

1. If no locale present in the URL, we will lookup in `navigator.languages` and redirect them to the proper locale. (Please note that we might be doing server side redirect instead if it makes more sense by using `headers['Accept-Language']` and also noted that we are going to be relying on `navigator.languages` and not `navigator.language` unless the browser does not support it (IE).

2. If the locale code present in the URL, but we do not support that locale then we want to follow the above process and redirect them to the same URL if they're trying to visit a page, for example https://learning.mozilla.org/<notsupport-LOCALE>/about and we will redirect them to https://learning.mozilla.org/<support-LOCALE>/about

3. If they have entered a locale, but in a wrong format, for example https://learning.mozilla.org/en-us/about which will result in 404, we might want to be forgiving in this case and redirect them to https://learning.mozilla.org/en-US/about

**Comment by alanmoo** [comment]
Added this to the wiki
