### ISSUE TITLE
Cursory snorkel around adding mofo-ui into Learning site

### ISSUE THREAD

**Issue by gvn** [mozilla/learning.mozilla.org#1959]
Perform a deeper investigation of what it would take to use Mofo UI on the Learning site.

Is there a way we can eliminate the Bootstrap 4 requirement? Can we reduce the architectural dependencies of legacy hubs that want to use it?

**Comment by hannahkane** [comment]
@gvn - can we close this now? Seems like you did this!

**Comment by gvn** [comment]
Yes!

**Comment by gvn** [comment]
Snorkel was successful.
