### ISSUE TITLE
Investigate options to allow Clubs team to update Club guides section

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#1965]
The new [Clubs Pages Designs](https://redpen.io/mn4cd1abc4840370be) include a Club Guides section that contains categorized links to a bunch of resources.

The current plan is to hard-code these links into the page, which would make process of updating them time consuming and requires the involvement of a dev. Originally, this section of the site was to be handled via the CMS, and since that won't happen, are there other options?

**Ideas**
* Use a similar setup to the Event Reporter tool
  * Links are stored in a Google Spreadsheet (editable by Clubs team)
  * Links sections is generated with some lightweight JS
* Iframe in a page hosted externally and is easy to edit for the Clubs team
  * Could be something hosted on Github? Is it iframe-able?
  * Could be a Thimble project
* ...other options?

cc @gvn @Pomax any ideas, feedback or concerns? Just brainstorming at this point.

**Comment by gvn** [comment]
Seems like a good use for Django since it looks like structured data.

**Comment by gideonthomas** [comment]
Here's a mock JSON schema that you can use for the time being that will probably look like what you will get from Django:

`GET /club-guides`
```js
[
  {
    "id": 1,
    "title": "Your First Month as a Club Captain",
    "url": "mozilla.github.io/clubs/guide/first-month.html",
    "description": "A guide to help you... ",
    "category": "Tips for Club Captains"
  },
  {
    "id": 2,
    "title": "Print a Flyer",
    "url": "mozilla.github.io/clubs/guide/print-flyer.html",
    "description": "Here's how you use a printer...",
    "category": "Marketing Your Club"
  },
  ...
]
```

and possibly we could do:
`GET /club-guides?format=category`
```js
{
  "Tips for Club Captains": [{
      "id": 1,
      "title": "Your First Month as a Club Captain",
      "url": "mozilla.github.io/clubs/guide/first-month.html",
      "description": "A guide to help you... "
    }, {
      "id": 7,
      "title": "Your First Month as a Club Captain (without RC)",
      "url": "mozilla.github.io/clubs/guide/first-month-without-rc.html",
      "description": "A guide to help you... "
    },
    ...
  ],
  "Marketing Your Club": [{
      "id": 2,
      "title": "Print a Flyer",
      "url": "mozilla.github.io/clubs/guide/print-flyer.html",
      "description": "Here's how you use a printer..."
    },
    ...
  ],
  ...
}
```

The work involved for this on Django is:
* Creating the Model
* Forming the URL pattern
* Adding the view(s)
* Serializing the data

**Comment by gideonthomas** [comment]
After chatting with @flukeout a more comprehensive approach seems to be needed.

The `GET /club-guides` route will remain the same.

The suggested changes to `GET /club-guides?format=category` is reflected below:
```js
[{
    "category": "Tips for Club Captains"
    "guides": [{
        "id": 1,
        "title": "Your First Month as a Club Captain",
        "url": "mozilla.github.io/clubs/guide/first-month.html",
        "description": "A guide to help you... "
      }, {
        "id": 7,
        "title": "Your First Month as a Club Captain (without RC)",
        "url": "mozilla.github.io/clubs/guide/first-month-without-rc.html",
        "description": "A guide to help you... "
      },
      ...
    ]
  }, {
    "category": "Marketing Your Club",
    "guides": [{
        "id": 2,
        "title": "Print a Flyer",
        "url": "mozilla.github.io/clubs/guide/print-flyer.html",
        "description": "Here's how you use a printer..."
      },
      ...
    ]
  },
  ...
]
```

This change implies two significant requirements from the schema implementation. Firstly, categories in the database should have an order associated with them. Secondly, guides should also have an order associated with them in the database that is relative to their own category.

Accordingly, the work to be done in Django changes to:
* Creating the Model
 * Category (include order that should be unique)
 * Guide (include custom validation that should make sure that order is unique within category)
* Forming the URL pattern
* Adding the view(s)
* Serializing the data
 * Ordering by category first and then by guide

The complexity of the work involved is reasonably substantial.

**Comment by flukeout** [comment]
Our github hosted JSON approach will be implemented in the next push to production, so closing.
