### ISSUE TITLE
Estimate & evaluate approaches to implement new Clubs Pages

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#1966]
Based on discussions in today's stand, let's evaluate and estimate a few approaches for implementing  the [New Clubs Pages](https://redpen.io/p/rb14e4c0eb3594f430) on the Learning site.

**Options**
* **The Big Kahuna** - implement all of the required components & styles in the unified design bootstrap theme and integrate it into the Learning site
* **The Half-stepper** - implement the new Clubs pages, but write all of the CSS and JS necessary for all of the components within the Learning site
  * We can extract them later into the unified theme
* **The Quick n' Dirty** - reduce the scope of the first phase to include _only_ adding the Clubs Guides links to the existing content in those pages
  * This part of the work is the most important to the Clubs team and gives us more time to do a big & robust implementation later

Let's discuss these in stand tomorrow. We can weight the pros and cons, and come up with some estimates that will help determine the most immediate course of action.

cc @gvn @hannahkane @Pomax

**Comment by gvn** [comment]
I propose we do Quick N' Dirty followed by The Big Kahuna (which can be done in parallel).

**Comment by gvn** [comment]
Also: Big Kahuna is more like using Bootstrap 3 + Mofo UI for Learning.

**Comment by flukeout** [comment]
Agreed, I'll look into the work involved to do the **QnD** and create a plan & estimate.

**Comment by jvallera** [comment]
Thanks @flukeout this looks great. I agree, the QnD approach is best for now, with Big Kahuna to follow (love these title selections). Here are some background deets about club resources that may help you:

1. They are all links that live online in various places (thimble, google, github, etc.) Here is the full list. https://docs.google.com/spreadsheets/d/1dpU02AiN2otBuN0W4Xt9cbIDMpBd3jKKLPs_1QsxeQo/edit?usp=sharing
2. You will see in the spreadsheet that they are categorized into guides, resources, blog posts/websites, Spanish guides and Portuguese guides. The guides are specific in that they use the github guide template. All the rest are links to other platforms. 
3. We include many of these resources into our communications with club participants. I don't have any way of knowing which ones are most frequently used, so if there were some way to incorporate that type of tracking (or times clicked) it would be great.
4. We encourage club captains and Regional coordinators to create resources that we can add to this list. They often use the tool of their choice. I wonder if we could have an "add a resource" button similar to how we have "add an event" on the event reporter. - I realize we included the option to include links (curriculum, blog posts, ext.) in the event reporter. This may be where some resources end up. Not sure best way to tie them together or to keep separate for now. 
5. It might also be good to offer a template for them to create a resource with....or we could direct them to remix one of the thimble pages we already have, but include a couple sentences on the top of the resources page with options for how to create a resource. 

Let me know if you have any questions. Happy to jump on a call.

**Comment by flukeout** [comment]
Thanks for the insight @jvallera - looking at the [current clubs page](https://learning.mozilla.org/clubs) gave me another idea. At the bottom of that page there is a **Get Help** link that is supposed to take you to resources. Unfortunately, that link is broken (filed in #1969) - but it could lead to a page hosted on the Clubs Github repo that would have a nicely formatted list of guides.

**Questions**
* What do you think of that solution?
* Did that link used to work, and if so, what did it lead to?

**Comment by jvallera** [comment]
@flukeout not sure what the help link use to point to, but guessing it may go to the club fact sheet which currently seems to be broken. http://mozilla.github.io/learning-networks/clubs/ trying figure out why. 

I would rather the guides be more up-front, like we plan to have them on the new site page...but I am ok with having them link to the help button for now if that is easiest.

**Comment by jvallera** [comment]
update, fact sheet is working, link seemed to be broken, not sure if that was the link for the help button, but will ask Amira next week. http://mozilla.github.io/learning-networks/clubs/facts

**Comment by hannahkane** [comment]
I can confirm that the Help link used to point to that fact sheet. It's also linked from the middle of the page ("If you’d like to get started on your own, check out these resources.")

It looks like the name of the file was changed 15 days ago, so this link has been broken since then.

**Comment by flukeout** [comment]
So, the way I see it, we've got two options for the Quick and Dirty

1. We include the expandable guides section within the current clubs page
2. We create a new Mozilla Clubs Guides section on the site that houses the guides

See below...

![image](https://cloud.githubusercontent.com/assets/25212/16887252/b5e68564-4a8d-11e6-9b5e-077b3157e320.png)

cc @sabrinang @jvallera What do you think?

**Comment by sabrinang** [comment]
@flukeout I think having option 2 with the indent will really help with the nav hierarchy. A separate page for these guides/resources will provide the flexibility for that page to be as long as it wants so we have the opportunity to showcase all the links and may not need to hide/collapse any content. It's also great to be able to link to that URL directly to share with club captains too.

**Comment by flukeout** [comment]
Thanks @sabrinang - that's my feeling too. I feel like the guides would be buries in the long page.

**Comment by sabrinang** [comment]
[Redpen](https://redpen.io/p/rb14e4c0eb3594f430) copy was revised from comments directly made on the redpen and from this [google doc](https://docs.google.com/a/mozilla.com/document/d/1yQgNldfjwGE_lT0JEeTDsgzNJTceWh58i6VsUyishAo/edit?usp=sharing)

**Comment by jvallera** [comment]
@hannahkane thanks for confirming. Can we update the get help link so it links to this: http://mozilla.github.io/learning-networks/clubs/facts not sure why/when it changed but this link will stay the same. 

@sabrinang and @flukeout I agree that option 2 seems like the best solution for now. Having a direct URL to guides will be very handy. Thanks!

**Comment by hannahkane** [comment]
@jvallera - yep. @flukeout filed #1969 and I submitted a PR. @flukeout - can you please review that when you have a minute (https://github.com/mozilla/learning.mozilla.org/pull/1970)?

**Comment by flukeout** [comment]
@hannahkane - will review the PR today.

**Comment by flukeout** [comment]
Currently there are two spots on the [Clubs Page](https://learning.mozilla.org/clubs) that link to the [Mozilla Clubs Fact Sheet](http://mozilla.github.io/learning-networks/clubs/facts)...

![image](https://cloud.githubusercontent.com/assets/25212/16933563/55ee8f4e-4d03-11e6-8435-cf161298512f.png)

and...

![image](https://cloud.githubusercontent.com/assets/25212/16933567/5cd35b5a-4d03-11e6-8949-cb192f47c760.png)

@jvallera Should we link them to the new Clubs Resources page instead?

**Comment by flukeout** [comment]
@sabrinang - I came up with a solution for showing translated versions of the guides. Could you have a look over and do a mini-crit?

![image](https://cloud.githubusercontent.com/assets/25212/16934240/1a058842-4d09-11e6-8f2d-1bcd62cb9aad.png)

**Comment by sabrinang** [comment]
@flukeout If there are not too many guides, instead of “also available in Spanish, French” you can consider just having the translated titles listed beneath it. 

For example:

- Teach open practices *(EN)*
  - enseñar a las prácticas abiertas *(ES)*
  - enseigner les pratiques ouvertes *(FR)*

or have it as "also available in español, français" if showcasing the other translated titles isn't possible

**Comment by jvallera** [comment]
@flukeout Good idea, but can we do it this way:

1. if you'd like to get started on your own, check out this Fact Sheet (link to fact sheet)
2. Get help can link to new clubs resources page.

love the addition of the translated resources and +1 @sabrinang

**Comment by flukeout** [comment]
Here are the translations loaded into the page from the JSON data. The _Customizing Your Club_ section has the most...

![image](https://cloud.githubusercontent.com/assets/25212/16958613/0f1e46b6-4d96-11e6-943f-06f9d8cde26f.png)
