### ISSUE TITLE
Broken "Get Help" link on Clubs page

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#1969]
On the https://learning.mozilla.org/clubs page, on the bottom right, the Get Help link is broken. It points to http://mozilla.github.io/learning-networks/clubs/ which is a broken link.

![image](https://cloud.githubusercontent.com/assets/25212/16884980/3d281b44-4a81-11e6-8760-c10b955643a3.png)

**Comment by hannahkane** [comment]
Target link was changed two weeks ago to http://mozilla.github.io/learning-networks/clubs/facts

Should also be updated above the map on the same page ("If you’d like to get started on your own, check out these resources.")
