### ISSUE TITLE
Request for hi-res image for Mozilla Learning feature opportunity

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning.mozilla.org#1975]
The mailbox.com has requested a hi-res image (to be sent by July 29) in order to feature Mozilla Learning in an upcoming _Learning_ magazine. It would be great to provide them with an image of the Mozilla Learning wordmark with some of the site icons, or a web lit map image with Mozilla branding.

Here are the requirements we've been sent:

> The image needs to be at least 3" tall or wide on its smallest side (preferably larger), ideally 300 dpi. Any common file type is fine. 
>  
> Your image may be published in Learning magazine and/or displayed on our website at TheMailbox.com, so the image must be owned by your organization. Any image you send needs to follow the terms of ownership. Go to this link http://www.themailbox.com/image-terms to read the terms.

**Comment by hannahkane** [comment]
cc @xmatthewx 

@KGorr - can you say more about how we're being featured? Is it a story about the Learning hub, or is it more like a list of resources, of which we're one? I'm trying to understand if a photograph of, say, a Mozilla Club in action is more appropriate than something logo- or wordmark-like. 

I don't believe we have a Mozilla Learning wordmark, though we could potentially create one. (I'm not sure if that's how we're referring to the Learning hub externally, though.) The Web Lit Map doesn't work well at a small size. The requirements say it should be 3" tall or wide, but preferably larger. Is there an upper size limit?

Is the feature about the Web Lit Map, or does it mention it? It seems like it could be a bit random to include the map graphic without context.

**Comment by KGorr** [comment]
Hi @hannahkane - thanks for checking in on this and great question.

From the requester:

"I don't have the text yet, but it will likely be the educational resource website in general because our mentions are fairly brief (a paragraph or so). I think the web literacy map could still work since it's an example of what's available. Or you could go with a logo or other more general image. "

@ldecoursy's suggestion is what's requested on this ticket: the image of the Mozilla Learning wordmark with some of the site icons, or a web lit map image with Mozilla branding - but we're open to ideas. :)

**Comment by hannahkane** [comment]
thanks, @kgorr.

I don't think the Web Lit Map is the right choice for a few reasons. 1) It's out-of-context if the mention isn't specifically about it, 2) It will be very hard to read unless it's pretty big, and 3) It's really meant to be interactive.

Wondering if just the Mozilla wordmark is the right thing here. 

@xmatthewx - thoughts?

**Comment by KGorr** [comment]
+1 @hannahkane, please note that this request has a deadline of July 29 due to their printing publishing schedule.

**Comment by xmatthewx** [comment]
If possible, it would be helpful to have a scan of what a similar feature looks like in the magazine. Mozilla logo could work. Alternatively, a fragment of the weblit map, icons of our tools, screenshot of a visually oriented learning curriculum. 

@hannahkane – which team do you think owns this task?

**Comment by hannahkane** [comment]
It doesn't particularly fit any of the teams, so I'd say Design ops. If I had to choose from the goal-based teams, I'd say Go Global, since it's related to marketing/growing the network.

**Comment by xmatthewx** [comment]
Until we have design ops staff, we'll have to pick a team. Best to let them guide this conversation and decision.

**Comment by KGorr** [comment]
I asked the requester for an example with within minutes received this: 

"It will be a brief mention, like those on the attached pages (note: the one at the bottom right of the "FYI" sample is an ad, so it wouldn't be that large)."
[Learning SAMPLE p38 Soc St BTS '15.pdf](https://github.com/mozilla/learning.mozilla.org/files/381892/Learning.SAMPLE.p38.Soc.St.BTS.15.pdf)
[Learning FYI section BTS 2015.pdf](https://github.com/mozilla/learning.mozilla.org/files/381893/Learning.FYI.section.BTS.2015.pdf)

**Comment by hannahkane** [comment]
Oh wow. Now that I see those examples, the Mozilla logo will not work. :)

I'll put this on the agenda for the Going Global team's heartbeat planning meeting today.

**Comment by xmatthewx** [comment]
That's very helpful. Thanks @KGorr. Logos or screenshots for our Learning tools might work well. Maybe screenshot of a curriculum. @hannahkane – It'd be good to set a time goal for this. 2-3 hours?

**Comment by sabrinang** [comment]
Here are some ideas for hi-res images for the learning site:
<img width="1140" alt="screen shot 2016-07-25 at 1 31 45 pm" src="https://cloud.githubusercontent.com/assets/2492510/17116555/24b78d6c-526d-11e6-8dc4-5cd59066103e.png">
You can leave feedback on the redpen here too: https://redpen.io/p/jqed445bb387dc3fd3

**Comment by KGorr** [comment]
I think the screenshots will be too small to read based on the example they provided. I like the image with the computers, but same thing - it may be too small to be able to tell what is on the screen. Looking forward to hearing other thoughts!

**Comment by KGorr** [comment]
What about a screenshot (more zoomed in with more detail) of an activity overview from https://learning.mozilla.org/activities/web-lit-basics (for ex)?

**Comment by sabrinang** [comment]
@KGorr Thanks for your feedback! I attempted to crop some screenshots but found that it loses the context of the screen and if it is used on the small scale the screencap text would serve more of a visual purposes than to be read at that scale. I did include versions where the URL is paired with photography so they are large and legible.

Here are some of the images used in context of thumbnails:
![magazine-example](https://cloud.githubusercontent.com/assets/2492510/17186068/89704cfe-53e8-11e6-8a34-198d43dbc286.png)

[redpen](https://redpen.io/p/jqed445bb387dc3fd3) updated

Here is the folder where you can find various exported hi-res image: https://drive.google.com/a/mozillafoundation.org/folderview?id=0B4Q8pzCpDS_eejRyYllySndBRDg&usp=drive_web&ddrp=1#

**Comment by KGorr** [comment]
Thanks @sabrinang! Does anyone else want to weigh in on which I suggest for use before I send it to the mailbox.com contact? @ldecoursy @xmatthewx @hannahkane

**Comment by ldecoursy** [comment]
I vote for the straight-up blue mozilla logo + URL :)

**Comment by hannahkane** [comment]
I'll go with Lainie's choice. :)

**Comment by KGorr** [comment]
Perfect - sent the requester and they said they will send us a copy. Thanks for all the help!
