### ISSUE TITLE
Determine how to localize structured data and the other

### ISSUE THREAD

**Issue by alicoding** [mozilla/learning.mozilla.org#1977]
There are bunch of content within the site that we can't rely on Pontoon to do the translation, such as:

1. [Teaching activities](https://dl.dropboxusercontent.com/spa/n5v3bx9nnjkdpzf/hfgorsk1.png)
2. [Blog post](https://dl.dropboxusercontent.com/spa/n5v3bx9nnjkdpzf/gub9kld6.png)
3. [External banner](https://dl.dropboxusercontent.com/spa/n5v3bx9nnjkdpzf/72jb0a-y.png) / similar content type (image+cta+link)

Note: Link to screenshot

Now, the blog post was experimented using wp-calypso to write and fetch the data and we believe that continue with that flow wouldn't be a bad idea though the other two is still a bit tricky.

We've been discussing in London for how to localized what we identified as structure data (The teaching activity or External banner) and thought using django to solve that except I've discovered that this model might not work well for the issue number one, but it fits well for number three. For number three it can be easily stored in a database that handled by django and we would allow our staff or contributor with limited access to add/change the content of that banner, or similar content type.

The trickiest one is number one, and that is complicated because of few reasons.

1. Some of the content can't be directly translated and therefore we can't structure it the same way as the original content (English copy in this case)
2. We have to figure out the UI and UX for how to fetch/display the content based on the requested language
3. We need to find a way to allow people to translate/submit their own teaching activity with addition to curated them in the submitted language and display them once it has been approved.

In this ticket I'm interested in some thoughts on the UX (+**design**) and the technology we might be looking to allow the workflow to enable this to be localized (**frontend**+ **backend**) for the number one specifically and would love to hear from @kristinashu @gvn @Pomax @alanmoo @mmmavis @gideonthomas @sabrinang @flukeout and anyone that I might have missed (please mention them in the ticket)

Cc: @simonwex @hannahkane @xmatthewx

**Comment by mmmavis** [comment]
Curious about how other sites do this (localizing content, not just translating short text string). Any example site we can check out?

**Comment by alanmoo** [comment]
The format Pontoon provides (localizing in place) seems to be incredibly useful. Are the potential problems with this other type of data hidden in the UI or more in the 'figuring out where to/how to send this data so it's accessible to different locales'?

**Comment by alicoding** [comment]
@alanmoo the problem with these kind of structured data / teaching activities is that it needs more than just translation because sometimes it links to an external URL and have different content than the original one when it's being translated in other languages.

**Comment by alicoding** [comment]
I think this is what we're going to do to localize both Structured data and teaching activities.

1. For list of structured data that links to Web literacy or teaching activities we're going to use `django` to store the data that either was submitted or collected manually on github or whatever method that was used when we did published a blog post asking for people to help localized the activities and we'll fetch them accordingly on the site by allowing them to either filter the activities by locales or using their browser's preferences based on the best UX that we think.

2. For teaching activities itself we will continue allowing people to choose the technologies that's already been used (Thimble, github pages etc.) and just submitting them to us the same way they would do like the one above and we'll just link them the same way.

The only TODO here for us would be to create a backend that will allow us to collect structured data and create an end-point to fetch the data. I will file a follow-up ticket, but want to get final thought from other people before closing this ticket.

@hannahkane @alanmoo

**Comment by hannahkane** [comment]
+1 to the plan generally. I am not yet clear on the process for getting stuff into django. Should we have a conversation about that workflow and whether there's need for UX design?

**Comment by alicoding** [comment]
I think I'm also unclear as to how the team is collecting them right now, and yes let's have a conversation about that.

**Comment by alicoding** [comment]
Closing this ticket and will file another one once we have our backend implemented.
