### ISSUE TITLE
add all Mavis-knowledge to the wiki page!

### ISSUE THREAD

**Issue by Pomax** [mozilla/learning.mozilla.org#1979]
Let's make sure @mmmavis's vast knowledge on learning.mozilla.org is not lost but getting all of it written out over on https://github.com/mozilla/learning.mozilla.org/wiki!

**Comment by mmmavis** [comment]
hahahahha I will tackle this today

**Comment by mmmavis** [comment]
I dropped the env var section into the wiki yesterday. Nothing else comes to my mind at this moment as @Pomax has covered *everything* super well already. 🍻 (was gonna use 👍 but I realized this is probably not a good time to use that emoticon 😉 /cc @Pomax )

**Comment by mmmavis** [comment]
I think we can mark this one done. 😉
