### ISSUE TITLE
Hivelearningnetworks.org Content Updates

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning.mozilla.org#1982]
While the hivelearningnetworks.org site is still live, we would like the following changes to be made to reflect the active communities. 

- Remove the locations tab (that includes the map and contact details in each city)
- On the home page, remove the following cities from the list:

  - Bangalore
  - Denver
  - Mombasa
  - Vancouver
  - Vizag
  - Ottawa

CC: @ldecoursy @simonaramkisson @mcdermott415

**Comment by kristinashu** [comment]
@hannahkane updated label from Leaders to Going Global (I think that's right?).

**Comment by alicoding** [comment]
I've updated the site, but I don't see Ottawa in the list.
