### ISSUE TITLE
New Discourse URL updates on learning site

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning.mozilla.org#1984]
I noticed a few spots where the new forum.learning.mozilla.org URL needs to replace the old discourse.webmaker.org URL.

**Footer**

- Home page
- Leadership opportunities
- Mozilla Clubs
- Maker Party
- Tools 

**Activities page**
Learning Objectives intro paragraph for these kits:

- Web Lit Basics I
- Privacy Basics: Protect Your Data
- Quacking Javascript

SIDE NOTES: (I can file a separate ticket - let me know what is helpful!)
 
- Privacy Basics: Online Tracking, Remix My Schedule Teaching Kit,  School Around the World Teaching Kit have some wonky formatting going on
- Three Things I <3 teaching kit references teach.mozilla.org

CC: @chadsansing

**Comment by hannahkane** [comment]
I think all of the links to the forums redirect properly, so I think we're good on those points.

**Comment by KGorr** [comment]
@ldecoursy 

If it works for you, it works for me.

**Comment by ldecoursy** [comment]
👍

**Comment by KGorr** [comment]
@chadsansing - do you think these discourse links need updated in the teaching activities? If so, anything I can do to help? If we're OK with redirects on those as well, I'll close this ticket. Thanks!

**Comment by chadsansing** [comment]
Redirects seem okay - not sure how many newer activities have Discourse links to worry about; I *think* the 3 Things I <3 is in a Moz repo with the other Thimble activities. Right. @hannahkane?

**Comment by hannahkane** [comment]
Yes. I just updated the link to read "learning.mozilla.org" in the 3 Things I <3 activity, but it generated a new url for the Thimble project itself, so I just filed a PR to change the link to the activity on the site. (Sorry that's super confusing!)
