### ISSUE TITLE
Additions to mozilla.org/gigabit website

### ISSUE THREAD

**Issue by jenntbeard** [mozilla/learning.mozilla.org#1989]
Two tasks:
1. While waiting for consolidated website for Gigabit Hives, we need to add Austin to the existing site since they are now eligible to apply for funding. 
2. We also want to add two sample funded grant proposals for prospective grantees to be able to reference.

All links and changes are contained in [this document](https://docs.google.com/a/mozilla.com/document/d/181dR_Ldfnok0JvWwcWcsaMp74Nlh4NfAdA-UMGWyxeg/edit?usp=sharing). The only thing missing currently is the Hive ATX logo, which is supposed to be available today (I think). 

cc @LindseyFrost @hannahkane

**Comment by hannahkane** [comment]
Thanks @jenntbeard. I don't see the reference to Austin or the sample proposals in the doc, though. Can you clarify?

**Comment by hannahkane** [comment]
For reference, the Austin logo ticket is here: https://github.com/mozilla/learning-networks/issues/408 and will be part of the Local Impact team's work next heartbeat (will put at the very beginning of the heartbeat).

**Comment by alanmoo** [comment]
These changes are live.
