### ISSUE TITLE
Localize components

### ISSUE THREAD

**Issue by simonwex** [mozilla/learning.mozilla.org#1992]
@alicoding start at the top, @alanmoo start at the bottom. Check them off as you start them.

 * [x] /activity-section.jsx (ali)
 * [x] /badges/badge-horizontal-icon.jsx (ali)
 * [x] /badges/badge-vertical-icon.jsx (ali)
 * [x] /badges/badge.jsx (ali)
 * [x] /badges/CredlyLinkForm.jsx (SKIPPED)
 * [x] /badges/requirement-list.jsx (SKIPPED)
 * [x] /badges/social-share.jsx (SKIPPED)
 * [x] /blockquote.jsx (ali)
 * [x] /dev-ribbon.jsx (ali)
 * [x] /Divider.jsx (ali)
 * [x] /expander.jsx (ali)
 * [x] /footer.jsx (ali)
 * [x] /hero-unit.jsx
 * [x] /icon-button.jsx
 * [x] /icon-buttons.jsx
 * [x] /icon-link.jsx
 * [x] /icon-links.jsx
 * [x] /illustration.jsx
 * [x] /imagetag.jsx
 * [x] /link-anchor-swap.jsx
 * [x] /login/Login.jsx (ali)
 * [x] /login/LoginLink.jsx (ali)
 * [x] /login/LogoutLink.jsx (ali)
 * [x] /login.jsx (ali)
 * [x] /madewithcode-instructions.jsx (SKIPPED)
 * [x] /madewithcode-intro.jsx (SKIPPED)
 * [x] /madewithcode-sample-make.jsx (SKIPPED)
 * [x] /map.jsx (SKIPPED)
 * [x] /modal-clubs-remove.jsx (SKIPPED)
 * [x] /modal-clubs.jsx (SKIPPED)
 * [x] /modal.jsx
 * [x] /newsletter-signup/SignupForm.jsx
 * [x] /not-found.jsx (ali)
 * [x] /optimizely-subdomain.jsx
 * [x] /optimizely.jsx
 * [x] /page.jsx (ali)
 * [x] /sidebar/Sidebar.jsx (ali)
 * [x] /sidebar/SubItems.jsx (ali)
 * [x] /sidebar/TopLevelNavItem.jsx (ali)
 * [x] /sidebar/topLevelNavItems.jsx (ali)
 * [x] /sidebar.jsx (ali)
 * [x] /timeout-transition-group.jsx (ali)

**Comment by alicoding** [comment]
Sorry for those that I've taken @alanmoo since I have finished them before we split the work.

**Comment by alanmoo** [comment]
Wanna close this one now @alicoding?
