### ISSUE TITLE
Localize Pages

### ISSUE THREAD

**Issue by simonwex** [mozilla/learning.mozilla.org#1993]
@alicoding start at the top, @alanmoo start at the bottom. Check them off as you start them.

 * [x] /about.jsx (ali)
 * [x] /activities/ActivitiesPage.jsx
 * [x] /activities/ActivityKit.jsx
 * [x] /activities/HiveLink.jsx
 * [x] /activities.jsx
 * [x] /back-to-school-write-the-web.jsx
 * [x] /badges/badge-single.jsx
 * [x] /badges/badges.jsx
 * [x] /clubs-list/ClubList.jsx
 * [x] /clubs-list/ClubListItem.jsx
 * [x] /clubs-list/ClubLists.jsx
 * [x] /clubs-list/ClubsListPage.jsx
 * [x] /clubs-list.jsx
 * [x] /clubs.jsx
 * [x] /community/CommunityPage.jsx
 * [x] /community/Intro.jsx
 * [x] /community/VerticalCard.jsx
 * [x] /community-call-april-20.jsx
 * [x] /community-call-march-23.jsx
 * [x] /community-call-may-25.jsx
 * [x] /community-call.jsx
 * [x] /community.jsx
 * [x] /curriculum-workshop-april-12-2016.jsx
 * [x] /curriculum-workshop-june-16-2016.jsx
 * [x] /curriculum-workshop-march-8-2016.jsx
 * [x] /curriculum-workshop-may-10-2016.jsx
 * [x] /curriculum-workshop.jsx
 * [x] /event-resources/EventDetail.jsx
 * [x] /event-resources/EventItem.jsx
 * [x] /event-resources/eventitems.jsx
 * [x] /event-resources/EventsResources.jsx
 * [x] /event-resources/LogoAsset.jsx
 * [x] /event-resources/LogoAssetLink.jsx
 * [x] /event-resources/logoassets.jsx
 * [x] /event-resources/PageLinker.jsx
 * [x] /event-resources/RemixLink.jsx
 * [x] /event-resources/support.jsx
 * [x] /event-resources/tabs.jsx
 * [x] /event-resources/Tabulator.jsx
 * [x] /event-resources.jsx
 * [x] /events/EventsPage.jsx
 * [x] /events/MakerPartyExample.jsx
 * [x] /events/MakerPartyExamples.jsx
 * [x] /events.jsx
 * [x] /fixme.jsx (ali)
 * [x] /healthcheck.jsx (ali)
 * [x] /home/BlogSection.jsx (ali)
 * [x] /home/CaseStudies.jsx (ali)
 * [x] /home/FeaturedPost.jsx (ali)
 * [x] /home/HomePage.jsx (ali)
 * [x] /home/LatestPosts.jsx (ali)
 * [x] /home/ModalEmail.jsx (ali)
 * [x] /home/ThankYouModal.jsx (ali)
 * [x] /home.jsx (ali)
 * [x] /intermediate-web-lit-two.jsx
 * [x] /intermediate-web-lit.jsx
 * [x] /madewithcode/MadeWithCode.jsx
 * [x] /madewithcode/variants/FirstPage.jsx
 * [x] /madewithcode/variants/Meme.jsx
 * [x] /madewithcode/variants/Poster.jsx
 * [x] /madewithcode/variants/Variant.jsx
 * [x] /madewithcode-firstwebpage.jsx
 * [x] /madewithcode-meme.jsx
 * [x] /madewithcode-poster.jsx
 * [x] /madewithcode.jsx
 * [x] /maker-party-2015.jsx
 * [x] /makes.jsx
 * [x] /offline-icebreakers.jsx
 * [x] /opportunities/BigSection.jsx
 * [x] /opportunities/OpportunitiesPage.jsx
 * [x] /opportunities/sectionlist.jsx
 * [x] /opportunities/SubSection.jsx
 * [x] /opportunities.jsx
 * [x] /parapara.jsx - Won't localize here
 * [x] /placeholder.jsx - effectively a 404, won't localize
 * [x] /privacy-basics/PrivacyBasicsPage.jsx - Won't localize here
 * [x] /privacy-basics/sections.jsx - Won't localize here
 * [x] /privacy-basics.jsx - Won't localize here
 * [x] /protect-your-data.jsx - Won't localize here
 * [x] /tools/ToolsColumn.jsx (ali)
 * [x] /tools/ToolsIntro.jsx (ali)
 * [x] /tools/ToolsPage.jsx (ali)
 * [x] /tools/ToolsSection.jsx (ali)
 * [x] /tools.jsx (ali)
 * [x] /web-lit-basics-two.jsx
 * [x] /web-lit-basics.jsx
 * [x] /web-literacy/MakeLinksFromWebLitSkills.jsx
 * [x] /web-literacy/Skills.jsx
 * [x] /web-literacy/WebLiteracyPage.jsx
 * [x] /web-literacy/WebMap.jsx
 * [x] /web-literacy/webmaplisting.jsx - This one looks to be a dead file
 * [x] /web-literacy/WebMaps.jsx
 * [x] /web-literacy/WhitePaperLink.jsx
 * [x] /web-literacy.jsx
 * [x] /webmaker.jsx
 * [x] /wp-content.jsx

**Comment by alicoding** [comment]
Closing this ticket and will file new issue if we've missed anything.
