### ISSUE TITLE
Remove copy from clubs site immediately

### ISSUE THREAD

**Issue by jvallera** [mozilla/learning.mozilla.org#1995]
Hello! the copy in the screenshot below needs to be removed from https://learning.mozilla.org/clubs/ as quickly as possible. 

![screen shot 2016-07-22 at 3 11 18 pm](https://cloud.githubusercontent.com/assets/3729312/17068413/d253770c-501e-11e6-9148-38a0609054a9.png)

@gideonthomas @flukeout thanks! let me know if you need more info.

**Comment by flukeout** [comment]
cc @gideonthomas
