### ISSUE TITLE
X-Frame-Options needs to allow-from Pontoon

### ISSUE THREAD

**Issue by alicoding** [mozilla/learning.mozilla.org#2004]
Currently it sets to DENY (from all) and it needs to allow from pontoon.mozilla.org

**Comment by gideonthomas** [comment]
Take a look at this before adding that header: https://github.com/mozilla/thimble.mozilla.org/issues/1517#issue-166185830

**Comment by alicoding** [comment]
@cadecairos can you comment here regarding this issue as well? It doesn't seem like there's an easy way to add this with `helmet` at the moment...

**Comment by cadecairos** [comment]
Helmet uses a package called [frameguard](https://github.com/helmetjs/frameguard)

here's how you'd use it:

```javascript
app.use(helmet({
  frameguard: {
    action: 'allow-from',
    domain: 'http://example.com'
  }
}))
```

**Comment by gideonthomas** [comment]
@cadecairos frameguard only sets the `X-Frame-Options` header which according to that issue linked, should not be used. We need to set the CSP header instead so I think you need to add the following [here](https://github.com/mozilla/learning.mozilla.org/blob/develop/app.js#L147):
```js
securityHeaders.directives["frame-ancestors"] = ["https://pontoon.mozilla.org", "https://mozilla-pontoon-staging.herokuapp.com"];
```

**Comment by cadecairos** [comment]
X-Frame-Options is still good to use it for older browsers, but yeah, adding a frame-ancestors directive to the CSP should be easy
