### ISSUE TITLE
Obtain Assets for Clubs Pages design

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2020]
The designs in [Redpen](http://images.streetsideauto.com/images/blog/051515-mad-max-fury-road/monster-jump.jpg) make use of various photos and icons. We don't have ready to use assets for these and will need to create them. 

**About Mozilla Clubs**
* [x] Circle logo without map icons
* [ ] List Icons
  * Airplane
  * Book
  * Ribbon w/ Checkmark
  * Schoolhouse
* [ ] 3 Element images
  * Students at desk
  * Classroom with triangles
  * Person making notes

**Start a Club** 
* [ ] 4 Persona Photos
* [ ] Connected dot icons

**Running your Club**
* [ ] Teacher photo
* [ ] 3 line-art icons
  * Twitter logo
  * Connected people
  * Chat bubbles

cc @sabrinang - can you provide these or point me in the right direction?

**Comment by sabrinang** [comment]
circle logo without map icons: https://drive.google.com/a/mozillafoundation.org/file/d/0B4Q8pzCpDS_eUkdVZF9vQ2prWVU/view
list icons taken from: https://science.mozilla.org/programs/fellowships with colours changed
club photos are here: https://drive.google.com/a/mozillafoundation.org/folderview?id=0B4Q8pzCpDS_eRm5ubEw3QVZOOTQ&usp=drive_web&ddrp=1#
persona photos are here: https://drive.google.com/a/mozillafoundation.org/folderview?id=0B2irLVDJivhLLWhDYkxLOWZEbU0&usp=drive_web&ddrp=1#
3 line-art icons are here: https://drive.google.com/a/mozillafoundation.org/folderview?id=0B2irLVDJivhLenZLWHdKTHJQMkk&usp=drive_web&ddrp=1#

**Comment by sabrinang** [comment]
previous comment on https://github.com/mozilla/learning.mozilla.org/issues/1605#issuecomment-229470129 mentioned photos are all from one city and if photo diversity is needed here are additional photo sets: 
- Nairobi https://www.flickr.com/photos/amirad/albums/72157666127395174 
- Rio https://www.flickr.com/photos/soapdog/

**Comment by flukeout** [comment]
Got 'em all. :pokeball:
