### ISSUE TITLE
Update curriculum template styling

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2028]
Based on requests from @chadsansing, let's make sure that the curriculum template - [like this one](http://chadsansing.github.io/curriculum-testing/color-picker-challenge/session01-color-picker-challenge.html#overview) - can do the following...

* Has a print stylesheet that prints all of the steps at once
  * Should we include images in this?
  * We could set a special class for important thing like diagrams so they get printed, but leave out decorative imagers?
* Is responsive and works well on a mobile device
* Supports a low-bandwidth use-case
  * Not sure how to build this in yet, but one idea is to add a link or button that reloads the page without any images
* Includes a style & formatting for adding facilitator notes
  * Was thinking of using styling similar to a post it note

@chadsansing - A couple of requests...
* Can you add a link to the DSO curriculum/content that have the facilitator notes?
* When are these changes needed by?

**Comment by chadsansing** [comment]
http://chadsansing.github.io/curriculum-testing/kenya-dso-interventions/01-intervention-one.html#overview and http://chadsansing.github.io/curriculum-testing/kenya-dso-interventions/02-intervention-two.html#overview

**Comment by flukeout** [comment]
@chadsansing when are these due?

**Comment by chadsansing** [comment]
I think it's kind of rolling, but check w/ @secretrobotron?

**Comment by secretrobotron** [comment]
Definitely not urgent. Is just useful to have soon to put on blog (and eventually in final report). Definitely before Mozfest, and ideally within August so we can publish the 3rd curriculum with the same template.

@flukeout what's your bandwidth like?

**Comment by flukeout** [comment]
@secretrobotron I can make these changes next hearbeat - just getting a sense of priorities etc.

**Comment by secretrobotron** [comment]
👍 u DA man

**Comment by flukeout** [comment]
I'm not actually a District Attorney

**Comment by secretrobotron** [comment]
what about a Disciplined Archer?

**Comment by flukeout** [comment]
I'll take it

**Comment by flukeout** [comment]
Hey @secretrobotron and @chadsansing - are the changes listed in this issue still needed?

**Comment by chadsansing** [comment]
@flukeout - absolutely. We have communities apart from the Kenya DSO project that could use these styles on all of our curriculum. Thinking specifically of @amirad's Women & the Web colleagues in Africa here.

**Comment by amirad** [comment]
Oh yes! Would be super helpful for all club work actually @jvallera

**Comment by hannahkane** [comment]
@flukeout - are you working on this now? just trying to get a handle on what's covered in the template work you've been doing.

**Comment by flukeout** [comment]
We can close this issue, the main two points from the first comment are covered. The other two are lower priority and are reflected in the curriculum-final repo...

* Low-band: https://github.com/mozilla/curriculum-final/issues/13
* Teacher notes: https://github.com/mozilla/curriculum-final/issues/3
