### ISSUE TITLE
Draft an email to Pontoon localization teams about helping us

### ISSUE THREAD

**Issue by alicoding** [mozilla/learning.mozilla.org#2029]
We need to write to Pontoon localization teams asking them to help us translating the site and maybe even involving in the community management as we've discussed during the stakeholders call

@hannahkane can you help with this?

**Comment by hannahkane** [comment]
Yup. Assigning myself.

**Comment by hannahkane** [comment]
First draft is [here](https://docs.google.com/document/d/1sLugqI1WMZTHHbO9W31sY2zQACcp6G2R-niys3OjCS4/edit#bookmark=id.nesto8qsa4w)

Needs input from @alicoding.

**Comment by alicoding** [comment]
This is done :)
