### ISSUE TITLE
QA the site before push to production

### ISSUE THREAD

**Issue by alicoding** [mozilla/learning.mozilla.org#2030]
We need to make sure l10n didn't break anything before we push to production.

Things to look for:

1. No weird copy around the site (no_message_like_this_around)
2. No broken links
3. If clicking on links still taking you to somewhere as expected.

@hannahkane @xmatthewx @alanmoo @sabrinang @Pomax @flukeout @gideonthomas @gvn @mmmavis @cadecairos @acabunoc

**Comment by mmmavis** [comment]
@alicoding where are we supposed to do QA? Mind sharing the link?

**Comment by alicoding** [comment]
@mmmavis just on https://learning.mofostaging.net sorry about that

**Comment by gvn** [comment]
Shouldn't the "Dev Version" banner be hidden?

**Comment by alicoding** [comment]
@gvn hidden from where?

**Comment by gvn** [comment]
Like, hidden when you view it in a browser?

**Comment by xmatthewx** [comment]
Are there specific pages or sections? Does this include nav and banner?

**Comment by xmatthewx** [comment]
Should we test in any other specific languages?

**Comment by alicoding** [comment]
@xmatthewx pretty much anywhere here really... :P

**Comment by alicoding** [comment]
@xmatthewx just in English for now (only one language we currently support)

**Comment by alicoding** [comment]
@gvn that's actually expected to be there on staging.

**Comment by hannahkane** [comment]
Is this related to the l10n work? The ampersand is not encoded correctly on /web-literacy, though it appears correct on production: 
![screen shot 2016-08-01 at 1 52 24 pm](https://cloud.githubusercontent.com/assets/8389648/17308542/7953bc06-57ef-11e6-9d98-a60c1022fb18.png)

**Comment by hannahkane** [comment]
And this one on /opportunities?
![screen shot 2016-08-01 at 1 57 29 pm](https://cloud.githubusercontent.com/assets/8389648/17308635/ee1ab648-57ef-11e6-9ebf-9d7dc12fd362.png)

**Comment by hannahkane** [comment]
Went through entire site, and the above were the only problems I saw that seem like they might be related to l10n. 

Not sure if everything on staging is ready to go to production, though: the Clubs Resources page is, I believe, but not sure about Credentials page, or what looks like some significant changes to /clubs/list/ page that I only see on staging. Can we make sure we coordinate?

**Comment by alicoding** [comment]
The two bugs that you found seems to caused by l10n but it's a very easy
fix here. (Just misuse of react-intl API)

**Comment by alanmoo** [comment]
@hannahkane It looks like the `/clubs/list` route differs in terms of content, but that's probably just a staging/production API difference. I don't see Credentials on Prod, maybe @pomax or @gideonthomas can shed some light on that.

**Comment by gideonthomas** [comment]
Credentials = badges. It's enabled on staging but not on prod

**Comment by Pomax** [comment]
as per gideon's reply, credentials is locked behind a feature flag and only enabled on staging. Badges have not launched in production.

**Comment by alicoding** [comment]
it looks like this has been shipped to production... Thanks everyone!
