### ISSUE TITLE
Community Call Landing page update needed for August

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning.mozilla.org#2040]
There will not be a Mozilla Learning Community Call in August, so we want to put a teaser up for September's call as soon as possible so the page isn't outdated.

Items needed for update:
- [x] Sept's video embed code (Kristina)
- [x] Sept's Etherpad (Kristina)
- [x] Tentative date/time (TBD Call Curator)
- [x] Teaser paragraph for theme/content, will not include speakers (TBD Call Curator)

CC: @ldecoursy

**Comment by KGorr** [comment]
@hannahkane - if we're able to have all info needed to update the page by the end of the week, is next week a realistic time frame for your team to update the page?

**Comment by hannahkane** [comment]
@KGorr - yep. Can do next week if you provide by end of this week. Thanks!

**Comment by KGorr** [comment]
@hannahkane - here is the landing page copy. It's super generic because we don't have anything nailed down yet. I'm thinking that the text above the blue box can stay as-is, then the text I am providing can be put inside the blue box, then no text beneath the box. Does that work?

"September
Youth Activism
What is the best way to engage young people in current events and civic discussion? Join us as we rally around our youth to encourage their voices to be heard in relevant local, national, and global conversations, while also promoting web literacy and 21st Century Skills."

**Comment by hannahkane** [comment]
@kgorr - I think this works. Is the call going to be on September 16th? Do we have a time? If we don't have date and/or time, I think we should say "September (date/time TBD)" or something like that.

**Comment by KGorr** [comment]
@hannahkane - let's go with "September (date/time TBD)" if you think that is best. Thank you!

**Comment by KGorr** [comment]
@hannahkane, can you provide an ETA for this update when you get a chance? Thank you!

**Comment by hannahkane** [comment]
@KGorr - sorry for the delay. Just waiting for the next push to production.
