### ISSUE TITLE
Curriculum Workshop landing page update needed for August

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning.mozilla.org#2041]
There will not be a Mozilla Curriculum Workshop in August, so we want to put a teaser up for September's webcast as soon as possible so the page isn't outdated.

Items needed for update:
- [x] Sept's video embed code (Kristina)
- [x] Sept's Etherpad (Chad)
- [x] Tentative date/time (Chad or Kristina)
- [x] Teaser paragraph for theme/content, will not include speakers [Chad or Kristina]

**Comment by KGorr** [comment]
Here's the embed code: `<iframe width="560" height="315" src="//www.youtube.com/embed/wmbYaGYJplE" frameborder="0" allowfullscreen></iframe>`

**Comment by chadsansing** [comment]
Etherpad: https://public.etherpad-mozilla.org/p/curriculum-workshop-september-13-2016

**Comment by chadsansing** [comment]
9/13/16, 11 AM ET

**Comment by chadsansing** [comment]
@KGorr, @amirad - I can push placeholder content to @hannahkane today for a landing page update; let's figure out guests ASAP and revise the copy next week?

**Comment by chadsansing** [comment]
@hannahkane, here is the copy and here are the links for a landing page update. Please push this into production ASAP:

Upcoming episode
September 13th - Maker Party & Copyright
8AM PT, 11 AM ET, 3PM GMT, 6 PM EAT, 8:30 PM IST

Copy: Join co-hosts Amira Dhalla and Chad Sansing along with invited guests to dig into this year’s Maker Party campaign around copyright and political action, especially in the EU. Learn about the copyright reform issues at play in Europe and how they connect to - or might impact - your local community and others around the world. Help us develop teaching and learning materials that make copyright, open licensing, and public domain clear and compelling to learners wherever you live.

YouTube embed: <iframe width="560" height="315" src="//www.youtube.com/embed/wmbYaGYJplE" frameborder="0" allowfullscreen></iframe>
MoPad: https://public.etherpad-mozilla.org/p/curriculum-workshop-september-13-2016

cc @amirad, @KGorr, @ldecoursy

**Comment by chadsansing** [comment]
@KGorr, can you add comms info at the bottom here? https://public.etherpad-mozilla.org/p/curriculum-workshop-september-13-2016

**Comment by KGorr** [comment]
@chadsansing, will do as soon as we have comms info finalized. We are still waiting to solidify our MCC plans...
