### ISSUE TITLE
application form followup: clean up the "add club" modal use

### ISSUE THREAD

**Issue by Pomax** [mozilla/learning.mozilla.org#2045]
Right now there is a single modal that is used both for "add" and "change", which needs cleaning up. It does not interfere with the new application form, but it shouldn't overstay its welcome, either

**Comment by Pomax** [comment]
This one's actually tricky: the old "add club" modal is tied to the "edit club" modal, so ideally we rip out this code, including the edit modal, and figure out whether we want users to be able to edit their club at all, and if so, which fields, and then build a new edit form for that that users can reach through some `/clubs/edit/:clubid` URL instead of on the clubs list page.

@hannahkane thoughts on this?

**Comment by Pomax** [comment]
crosslink for https://github.com/mozilla/learning.mozilla.org/issues/2243

**Comment by hannahkane** [comment]
Will wait for feedback from stakeholders on #2243 before making any decisions

**Comment by hannahkane** [comment]
Closing this given new work being done on Clubs module
