### ISSUE TITLE
application form followup: tweak the UX when submitting the form

### ISSUE THREAD

**Issue by Pomax** [mozilla/learning.mozilla.org#2053]
Right now it's possible for the submission step to take a few seconds, which might make users think nothing is happening. We probably want to spend a bit of design effort on making sure the form somehow clearly indicates it's being submitted (maybe grey out the page?) before it transitions to the "you've submitted your application" screen.

**Comment by Pomax** [comment]
@xmatthewx who would be a good person to have a look at what a sensible UX is here?

**Comment by xmatthewx** [comment]
I'm sure Luke could tackle this with you quickly. Feel free to discuss with @hannahkane during stand. Is this form for clubs or badges or something else?

**Comment by Pomax** [comment]
club captain application form, so something we already landed. @flukeout is great, I can bug him lots =)
