### ISSUE TITLE
Gigabit content merger: IA and wireframes

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#2058]
Context and summary [here](https://docs.google.com/document/d/1pjKhkcqF3Pl5Q9T1HifwaUzoa2UCknhyPVZ-o8KrGR0/edit#heading=h.tmht8mkug1se)

@jenntbeard and @LindseyInCHA are the key stakeholders.

**Comment by LindseyFrost** [comment]
Hi all - I stupidly locked myself out of GitHub account so I'm
@LindseyInCHA going forward (I can only replay via email to the current
account) - thanks!

**Comment by hannahkane** [comment]
Consider localization as a factor. Do we localize this content? (Consider the application form in particular.) Do we provide a separate version of this content for people to localize?

**Comment by jenntbeard** [comment]
The application form includes all eligible cities - we try to create as much content across gig cities as possible - like Twitter, for example. Each city has it's own Hive, that's where the differences are more apparent. Does that help?

**Comment by sabrinang** [comment]
@jenntbeard @LindseyInCHA @hannahkane 
Here are some wireframes to get some feedback early in the process. See redpen: https://redpen.io/p/ku41f3c8ea603732e1

**WIREFRAME OVERVIEW**
![overview](https://cloud.githubusercontent.com/assets/2492510/17952578/c9f0f12c-6a20-11e6-9403-93f76d3af1e5.png)
*NOTE: The language on the mockups is adapted from the doc (https://docs.google.com/document/d/1E33Li8FRMvtiukAupaXZ_q6p7n0A4DshUmLGrVvddkk/edit#) to show approximate desired length of copy and type of content for placement only.*

**ABOUT TAB**
Going through the docs we can do a better job of transitioning from talking about Mozilla Gigabit Community Fund to Gigabit Cities so a recommendation for content flow to introduce the language on the first About page is to start by:
- first, introduce what Gigabit is
- then, explaining approach/connection to Hive and Mozilla
- lastly, describing the relationship together forming Gigabit Hive Cities

Overall, we can also clarify language in the copy and use it consistently to support the relationship between Gigabit and Hive we intend on showcasing. For example, it is unclear if "Mozilla Gigabit Cities" and "Gigabit Hive Communities” are the same or different but we should be more clear and deliberate with the copy we use to describe the relationships. Also, I am unsure how the relationship between fund and city wants to be represented so more feedback on this would be helpful.

For the blog, an idea is to showcase the most recent blog on *Featured Updates* and link to *see all blog posts* which would lead to the shared learning blog with Gigabit tag selected. (links to: https://blog.webmaker.org/tag/gigabit)

For events, I am unsure about the type of events, frequency and use case but a suggestion here is to perhaps use a third-party event service (which could be easier to update too) and *see all events* can link to that external link. We can showcase the latest event on the *Featured Updates* section as well.

**PORTFOLIO TAB**
This section is showcasing projects and I would like to hear more feedback on what filters would be useful to sort this content by? (for example, I saw on HiveCHA they used “rounds” but I’m unsure if this is intuitive to users who are unfamiliar with the gigabit cycles). This tab links to individual projects on individual pages and I have not resolved if this is represented in the navigation on our site for this type of content.

**APPLY TAB**
This is similar to what currently exists. We need to determine where the terms and conditions lives and it has been flagged with Hannah to discuss with legal and perhaps it could be merged with the learning sites t&c and could be linked to the one central place.

________________________

**PRODUCTION**
This site is geared towards users from the USA and flagging @alicoding  for feedback on how to approach localization for this Gigabit site. Also, @alanmoo if there are any recommendations or concerns to implement this specifically project pages in the portfolio tab.

**Comment by hannahkane** [comment]
Thanks, @sabrinang. I think this is a fantastic start. Left a couple comments on the pad, but mostly waiting for @jenntbeard and @LindseyFrost to weigh in, especially regarding your thoughts about how to handle the blog and events.

**Comment by jenntbeard** [comment]
This is looking fantastic! @LindseyinCHA and I are meeting tomorrow morning to discuss and I will share our collective thoughts immediately following. Thanks everyone!!

**Comment by alanmoo** [comment]
Two things:

1.) I commented this in the red pen, but that can be hard to find sometimes; I think the individual project pages should keep the tabs. Not only is it easier/cleaner to implement, but I think it keeps a sense of place within the site. Couple in a "back to all projects link" and there's no getting lost, even if you happen to land on that page from an external link.

2.) On the "events from an external location" idea- I like the way you're thinking, but I wonder if we want to go down that specific path. I can see having a general "MoFo events" API that we use across sites. For example, it's just a part of the science site API right now, but I wonder if something a bit more broad might be useful in extending our reach as an organization. (So, for example, we could have a single place to go for all Mozilla Events, like the network pulse project is exploring with Mozilla related projects.)

**Comment by jenntbeard** [comment]
Hi, Lindsey (@lindseyincha) and I just met to discuss the wonderful wireframes and made some comments in the red pen. In addition, here are a couple of other items related to the comments above that might be helpful: 

A Mozilla Gigabit city = Mozilla Gigabit Community Fund + Gigabit Hive
Example = Gigabit Hive Kansas City

Calendar issue: we anticipate using this for gigabit network events only (not a one-time local meetup in a city); we currently have an IoT Hack/Startup weekend in Chattanooga, KC Techweek events in September, and MozFest in October

We're excited to learn what color scheme we're getting! And THANK YOU ALL for your amazing contributions already, this is going to be such an asset to our work!

**Comment by hannahkane** [comment]
Re: @alanmoo's idea about an Events API. I like this direction, but I want to make sure we don't recreate the wheel. Does Mozilla already have an Events solution that Mofo events should be a part of? (Just found this: https://www.mozilla.org/en-US/contribute/events/) Or would we be better served by using an external third-party tool that has add'l features (e.g. handling event registrations)?

If we continue to build out what we have already, I wonder if it should actually be fully integrated into Network Pulse. cc @xmatthewx

**Comment by alanmoo** [comment]
Agreed, we might not need to build something; I just want to investigate the possibility of using the same thing everywhere.

**Comment by hannahkane** [comment]
Definitely leaning towards extending the Events API from Science to Learning site. Maybe we can talk through technical implications during Going Global stand tomorrow, and talk through product requirements with Lindsey and Jenn during our walk-through tomorrow.

**Comment by hannahkane** [comment]
Noting that if we could extend the Events API to support the Learning hub's events, including the [Mozilla Curriculum Workshop](https://learning.mozilla.org/en-US/community/curriculum-workshop) and [Learning Hub Community Call](https://learning.mozilla.org/en-US/community/community-call)—which have embedded YT videos—that would solve an additional problem, because currently those pages are not updatable by staff.

**Comment by sabrinang** [comment]
@jenntbeard @LindseyinCHA the new copy from the redpen for the "innovate and spread" section is a bit uneven compared to the rest. See screenshot below and consider shortening this section to help even out with the rest of the sections
<img width="977" alt="screen shot 2016-08-31 at 12 53 02 pm" src="https://cloud.githubusercontent.com/assets/2492510/18144116/e5ab1236-6f79-11e6-888d-e04919b04eb1.png">

Also, consider shortening this section, perhaps making it into one paragraph so the "Find a Project" section isn't sitting too low on the page
<img width="995" alt="screen shot 2016-08-31 at 12 51 24 pm" src="https://cloud.githubusercontent.com/assets/2492510/18144088/ce68354a-6f79-11e6-8464-fc9790f820a4.png">

**Comment by jenntbeard** [comment]
Yes, I see that. In favor of clarity, we chose the more text option to even things out (since we were losing that one section on the about page anyway). We're totally fine with making the Portfolio page content into one paragraph. All updated text can be found here: https://docs.google.com/document/d/1YYupTRF4VPBH20AhsmS22SlGU_cEdZLSoTiNHta1lvk/edit. Also, I am working on the 2017 RFP dates for the apply page and plan to have those to you by Friday this week.

**Comment by sabrinang** [comment]
Content has been updated in redpen: https://redpen.io/p/ku41f3c8ea603732e1

work in progress things:
- 3 icons
- Portfolio Tab (search features and project navigation to be unified with other mofo properties)

**Comment by hannahkane** [comment]
Looks awesome, @sabrinang!

Left a couple of comments on the redpen, mostly about copy feeling a little long. 

Withholding comments about search/filter functionality on the Portfolios page until you've had a chance to sync up with other designers about that.

**Comment by jenntbeard** [comment]
This is looking SO FINE! I have reviewed the new designs and @LindseyinCHA is doing the same currently. As always, thank you all for your fantastic efforts to help make the gigabit work open and accessible.

**Comment by xmatthewx** [comment]
Hi all. I posted a few comments in redpen as well. I think there are some copy changes we could make, to grab people's hyper limited attention and pull them in to the details. @jenntbeard 

I also wonder about how the table will appear on mobile. Do we have tables like this on other recent sites? @sabrinang

**Comment by xmatthewx** [comment]
To simplify, I propose that our searchbox includes the placeholder copy "Search for subject, location, or technology". We can drop the complex filter for the first iteration, get these pages out the door, and then revisit filtering in a future iteration if needed, when we have time to access the purpose/value and design more carefully.

**Comment by xmatthewx** [comment]
We don't believe we have a pattern for responsive tables on mobile. If we don't have it on the science or advocacy sites @alanmoo @sabrinang, let's consider switching this to 3 side-by-side boxes.

**Comment by hannahkane** [comment]
+1 to Matthew's suggested copy changes.

My sense is that browsing is the more important use case over searching when it comes to the portfolio, but would love for @jenntbeard and @LindseyFrost to way in on that, because that assumption might be wrong.

Will note that the table on https://www.mozilla.org/en-US/gigabit/apply/ works pretty well on mobile now, IMO.

**Comment by hannahkane** [comment]
I think we're going to need a temporary solution for Events, while we sort out the larger Mofo-wide Events API work. 

@jenntbeard / @LindseyinCHA / @LindseyFrost (Lindsey - what is the right handle to use for you?) - I left a comment in the redpen about getting the event details from you when we can. Would be good to know the # of events, and the particular information you want to detail.

**Comment by jenntbeard** [comment]
I am jumping back into the redpen now - sorry for the delay. Lindsey's correct Github handle is @LindseyinCHA.

**Comment by sabrinang** [comment]
need to mockup temporary events page from spreadsheet: https://docs.google.com/spreadsheets/d/1X3nmzwZkG0lJh-VfzBhuN6SQws2VM6WeR8Rybol8GTk/edit#gid=0

**Comment by sabrinang** [comment]
updated redpen with event mockup with content from spreadsheet: https://redpen.io/hy579b049588c835f9

@jenntbeard Are these events finalized?

**Comment by jenntbeard** [comment]
Yes, these are the most updated details that I have - I know we have more events coming but without nailed down dates and/or details. Thanks!

**Comment by sabrinang** [comment]
Refined design details and cleaned up type based on the feedback and sticking as close to the existing learning.mozilla.org styles that exist. 

Final design on redpen: https://redpen.io/p/ku41f3c8ea603732e1

sketch file (.sketch): https://drive.google.com/a/mozillafoundation.org/file/d/0B4Q8pzCpDS_eRmtDV1dmcTgxb1k/view

icons (.png .svg .ai): https://drive.google.com/drive/folders/0B4Q8pzCpDS_edlVPcVFUQzE0d2M

website assets (partner logo, photo): https://drive.google.com/drive/folders/0B4Q8pzCpDS_eYTV0NVVRbXlIVlU

Please refer to issue #2228 for implementation phase.
