### ISSUE TITLE
Provide content for new "Featured Updates" section.

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2061]
The about page in the new Clubs Pages desings - https://redpen.io/pbcb2eda696626f5e7 - includes a Featured Updates section, which we need content for.

**Each udpate needs**
* A "category"
* A title
* Short paragraph description or excerpt
* A URL

Please provide this content if you'd like it to be a part of the launch, and if not, let me know so I can remove it.

For reference...

![image](https://cloud.githubusercontent.com/assets/25212/17445409/a7807102-5af9-11e6-9c1a-287497be70b6.png)

**Comment by Carotejada** [comment]
Hola @flukeout! We do have content for this section but would like to know if we're going to be able to update it periodically? If the process is complicated so we prefer to get rid of that section.

cc @jvallera 

Thanks!!!!

**Comment by flukeout** [comment]
Eventually, the goal is for your team to be able to update these periodically in a similar manner to the Clubs Resources. That will take a little longer to set up, so in the meantime we can just add some content there to begin with and make it easier to update later. What do you think?

**Comment by jvallera** [comment]
ideally this sounds good @flukeout I am just concerned about the time it may take to update it and my capacity to remember to check in on it and send you updates in the meantime. I suppose it is ok if features are not updated that frequently because they won't necessarily be time specific.

**Comment by flukeout** [comment]
Okay, I'll leave it up to you then - if you'd like to have some initial content there when the pages launch, please provide it by end of Wednesday. Does that work?

Otherwise, I will remove the section for launch and work on making it dynamic in the next heartbeat.

Let me know if that is a good plan.

**Comment by flukeout** [comment]
Thanks @jvallera
