### ISSUE TITLE
Copy changes for /about page

### ISSUE THREAD

**Issue by alicoding** [mozilla/learning.mozilla.org#2062]
This was raised from l10n community

> In 2015, our goal is to foster and sustain web literacy activities in 500 cities around the globe. Join us by teaching, learning, sharing and imagining the full power of the web.

The 2015 is outdated here right?

@hannahkane ?

**Comment by hannahkane** [comment]
@ldecoursy or @mcdermott415 - can I assign this to one of you? Would you like to weigh in on updated copy for the now outdated About page?

**Comment by ldecoursy** [comment]
I believe @mcdermott415 is still working through some of this. In the meantime, I wonder if we should hide that page (I notice science doesn't have a separate "About Us" page), and instead update the language on the landing page with the Learning hub's purpose statement: 

Mozilla Learning rallies and connects leaders who want to advance the promise of the Internet for learning in a networked world. We do this by fueling new approaches to digital learning through Mozilla Hives, Clubs and our Gigabit cities.

I *think* that's it, but Meghan can confirm.

**Comment by mcdermott415** [comment]
That works!

**Comment by hannahkane** [comment]
@alanmoo - could you implement the solution @ldecoursy describes above?

**Comment by alanmoo** [comment]
- [ ] Hide https://learning.mozilla.org/about
- [ ] Change "We want more people to see themselves as citizens of the web. The Mozilla Learning Network offers programs and a global community dedicated to helping people learn the most important skills of our age: the ability to read, write and participate in the digital world. Learn more" to the text @ldecoursy suggested.

Is that right?

**Comment by hannahkane** [comment]
Yes. And just to clarify, will removing /about from the footer prevent that content from being translated in Pontoon? That is the goal.

**Comment by alanmoo** [comment]
Ah, good point. I think I'll have to remove the route and the strings from the file Pontoon uses.
