### ISSUE TITLE
Bug in locale negotiation

### ISSUE THREAD

**Issue by alicoding** [mozilla/learning.mozilla.org#2079]
My header:

```
Accept-Language:en,en-US;q=0.8,en-CA;q=0.6,bn;q=0.4
```

What I get when I visit https://learning.mofostaging.net

https://learning.mofostaging.net/en-GB/

What I expect when I visit https://learning.mofostaging.net

Either redirect me to https://learning.mofostaging.net/en/ or https://learning.mofostaging.net/en-US/

**Comment by alicoding** [comment]
cc @alanmoo

**Comment by alanmoo** [comment]
I'm not sure this is a bug. `en-GB` is a supported locale, and `en` is not. It seems like the node module I'm using to decide on a locale is just choosing `en-GB` from `en`. I could look into defaulting to US from a simple `en` but if that's not something that's easy to set, I don't know that it's worth building out.

**Comment by alanmoo** [comment]
It looks like `en-GB` gets picked over `en-US` because properties2json generates its json file in alphabetical order of locales. I'm going to fix #2080 first because that really seems like the bigger issue- once that's fixed, it won't matter as much if you're on en-GB vs en-US.

**Comment by alicoding** [comment]
I don't think you should rely on that json file to decide what locale to serve here. It should be based on the locale priority in the header itself.

**Comment by alanmoo** [comment]
I'm not, I'm relying on the language tag. [According to spec:](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.4) `A language-range matches a language-tag if it exactly equals the tag, or if it exactly equals a prefix of the tag such that the first tag character following the prefix is "-"`

Since you've got `en` as your default language, serving up any `en` variant is considered acceptable.

**Comment by alicoding** [comment]
@alanmoo yes and no. In practice if you have second preference language set in your browser (in my case is not the best here I would say) you should go to the second best option in the accept-language headers. I have encounter issue when we assumed that it's okay to serve xx-XX whatever `XX` we thought it was okay to served to the user, but it was not and it did create issue.

**Comment by alanmoo** [comment]
I would say come up with a solid example and put the issue on https://www.npmjs.com/package/accept-language, that's the package that's  But as far as I can see, if you've got `en` as your preferred language, any `en` will do.

**Comment by alanmoo** [comment]
https://tonicdev.com/57a20cbcd3d2381300d8c2aa/57ae30d7110bc9130085183d *may* be an example of a real bug (though I'm not sure how likely it is to happen/truly impact someone). And I'd still say its results are within spec.

**Comment by alicoding** [comment]
@alanmoo spec doesn't mean it's always right and I will tell you why.

Say for example you have these in your browser's language preferences:

```
es, es-MX, en-US
```

Now, based on that module and what you're saying about the spec if our website offers these locales `["es-ES", "en-GB", "en-US", "de"]` and I might get redirect to `en-ES` and that's just wrong.

There are slangs and much more when it comes to other language. English is a bad example here and I still think we shouldn't go with what the spec and that module is doing. I asked 3 people in the office about this behaviour as well and they all saying is not right and some even suggested geolocation to make it accurate, but we don't have to go that far.

**Comment by alanmoo** [comment]
I think you've got a typo in those lists, so I'm not entirely clear on the example

**Comment by alicoding** [comment]
@alanmoo what's the typo?

**Comment by alanmoo** [comment]
"en-ES" isn't on either list. Not sure if you mean en-US or es-ES

**Comment by alicoding** [comment]
@alanmoo my bad I meant `es-ES` and not `en-ES`

**Comment by alicoding** [comment]
Yeah, so this is wrong https://tonicdev.com/alicoding/57ae3510da2a331500899ccc

**Comment by alanmoo** [comment]
Ok, the link I can see why it's wrong. Your previous example I'm not convinced- if someone has a generic "es" as their first language in preferences, without a region, they shouldn't be upset if they get a different region.

**Comment by alicoding** [comment]
I would say even if they don't have region at first, don't try to give them whatever we think its right until we go through their list and then we can go with non-region locale as our last result.

**Comment by alanmoo** [comment]
I see where you're coming from, but I'm not convinced it's the right approach. I'd like to hear from some other multi-lingual speakers/see some data about how users have things set before going in that deep. Though I would be open to filing an issue on the original repo for your reduced case above and submitting a PR if/when it's the right time for us to address it.

**Comment by alicoding** [comment]
Flagging @ScottDowne here since he is also really interested in this and based on my experience and research over two years working at CDOT and been working closely with the community I would say the one I propose is common and most logical

**Comment by alanmoo** [comment]
Fair, and I will totally acknowledge that I'm coming at this from the "I only speak English" side of things. Please consider my hesitation as coming from an "I want to understand why it's worth the effort" angle rather than an "I think you're wrong/don't believe you" angle

**Comment by alicoding** [comment]
Totally understand and it's totally right to question this sort of stuff
rather than just go with whatever we think it's right.

**Comment by Pomax** [comment]
for multiple languages, you really want to go "exact match if possible, *then* try fallback", so because `['en','en-US']` has an exact match `en-US`, it should be resolving to the US locale; if it was ['en', 'en-CA'] then the kind of broader `en-*` match leading to `en-GB` would be fine.

**Comment by alanmoo** [comment]
But `en` is considered 1.0 in the absence of a value (see link to spec in previous comment), which, in addition to your final sentence, is why I think the original issue is "expected" behavior and not worth specifically fixing. It would sprinkle in magic logic for a functionality which the user has control over (and frankly, if their q-values are set that way, it's probably something they changed themselves). And of course, we're going to have a language selector, so it's not like they'll be locked in.

**Comment by alanmoo** [comment]
I'm going to keep an eye on https://github.com/tinganho/node-accept-language and try to help that get up to spec as I have time. Some of their disabled tests touch on our failing test cases, so making that package work should take care of a lot of our issues. I don't believe this is a critical enough issue to block anything; I can't help but feel some of these broken examples are a bit contrived. Besides, I think it would be more useful to direct energy into enabling a language switcher so that in the event we guess it wrong, a user is able pick which supported locale they want.

**Comment by ScottDowne** [comment]
Sounds like to me we're not arguing so much if something is correct or not. I think everyone agrees that the case of using en-US over en-GB is ideal and should be supported. When Alan says it's to spec to use en-GB, he's correct, as the spec does say en-GB is a sufficient replacement to en. Going through the whole list first though looking for an exact match is ideal, though.

It's completely logical that es-ES or en-US as a second option be taken over es-MX or en-GB, we all agree on that, but really, it's not a critical issue.

What it really looks like is we're trying to determine if it's worth building out support for this or not. My guess is if time is a factor, this is an acceptable technical debt. My reasoning is, it's kinda fringy, and donate doesn't even do fallbacks to the secondary language at all, and no one has complained.

**Comment by alanmoo** [comment]
Agreed. And technically to spec, there may be a case for using en-US instead in the original example, as the "quality" of en-GB isn't as high, especially if we're using currency/content differs dramatically. I'd suggest we close this as a won't fix for now, but I'm watching the other repo and will bump `MoFo-localize` as `accept-language` improves.

**Comment by alicoding** [comment]
I wouldn't close this ticket until we fix the issue example in that link?

**Comment by ScottDowne** [comment]
Right now es-ES is the first item is sent to es-MX?

**Comment by ScottDowne** [comment]
If so, I would suggest filing a new issue with just that as the issue, to drop all this noise in this ticket.

**Comment by alanmoo** [comment]
Ok, I've cleaned this up and clarified in #2088.

**Comment by alicoding** [comment]
I'm reopening this issue to see if this edge case exist at all in donate repo logs for EOY if not then we can totally ignore the issue and close this ticket.

**Comment by alanmoo** [comment]
So you'll check a log of all the "accept-language" headers?

**Comment by alicoding** [comment]
Yup :)

**Comment by alicoding** [comment]
So, this is my finding from looking at Google Analytics for donate.mozilla.org
NOTE: Google strips whatever locale after semicolon, meaning it will only pick up the first preferred locale. Read more here http://www.lunametrics.com/blog/2013/02/12/languages-report-google-analytics/

All sessions: 3,358,840

------------------------------------------
1,794,122(53.41%) of users requested `en-us`
124,888(3.72%) of users requested `en-gb`
6,782(0.20%) of users requested `en`
-------------------------------------------
215,642(6.42%) of users requested `es-es`
112,449(3.35%) of users requested `es-mx`
11,261(0.34%) of users requested `es`
--------------------------------------------

There are over 100 locales came in without region as part of the language request of all 443 of them.

**Comment by alanmoo** [comment]
How does GA get the locale? Also from the header? Or do they use navigator?

**Comment by alicoding** [comment]
@alanmoo they said they strip info after the first semicolon in the Accept-Language header.

```
Accept-Language:en-US,en;q=0.8,en-GB;q=0.6,fr-CA;q=0.4,fr;q=0.2
```

will be stored as `en-US`

**Comment by alanmoo** [comment]
Ah I'm sorry, you said that already. *sips more coffee*

So what can we take away from this?

**Comment by alicoding** [comment]
@alanmoo I think going with what @Pomax suggested as this UX is followed by other Mozilla projects including Mozilla.org IIRC. Going through their list first before assigning the next possible locale with region like the specs?

**Comment by alanmoo** [comment]
Mozilla.org doesn't work like that, I just tested. In Firefox, I set the following language:
<img width="487" alt="screenshot 2016-08-17 10 08 58" src="https://cloud.githubusercontent.com/assets/1682681/17739310/ad953d3a-6462-11e6-8f24-46dbdcf5da15.png">
Then emptied my cache. Visiting mozilla.org gave me `/en-US`. (Testing again by switching the order and emptying cache resulted in `/en-GB` when it was on top of the list)

**Comment by alanmoo** [comment]
That being said, I don't necessarily disagree. I just think it's lower priority and something we should work in via `accept-language` if they'll support it.

**Comment by alicoding** [comment]
@alanmoo it seems like they don't go through the rest of the locale, but the first locale they see in `navigator.language` there which is kinda sh*tty if you ask me haha. So, you are right this is not a priority right now and might not worth fixing now since we don't have that much locale support and traffic to get that problem, but I still do think when we start having more locale and traffic to the site this need fixing for sure.

**Comment by alanmoo** [comment]
Yeah, I just don't want to have to maintain a piece of code for this just for us- I'd rather incorporate this fix into the existing 3rd party component.
