### ISSUE TITLE
Bug in properties2json causes string to not display correctly

### ISSUE THREAD

**Issue by alicoding** [mozilla/learning.mozilla.org#2080]
For stuff that's not translated right now you will see something like this

![https://dl.dropboxusercontent.com/spa/n5v3bx9nnjkdpzf/gxk3hdnr.png](https://dl.dropboxusercontent.com/spa/n5v3bx9nnjkdpzf/gxk3hdnr.png)

It should actually merged any missing keys from default language (`en-US`) to other languages.
We actually have this behaviour in other repo, but not sure why this is not working as expected here.

**Comment by alicoding** [comment]
cc @alanmoo

**Comment by alanmoo** [comment]
Ah, I noticed this but didn't realize it was inconsistent with other repos. I'll look into it.

**Comment by alanmoo** [comment]
Based on the donate repo, it looks like this isn't a problem with properties2json, but with the way fallbacks work when a string identifier isn't found. (In there I see `el` is in the json file with no keys, navigating to donate.mozilla.org/el works as you describe)
