### ISSUE TITLE
Resolve model issues for Duration, Difficulty, and Age 

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#2084]
As per our discussion in Stand today, I reviewed all of the existing Activities and Modules on the Learning site, and looked at about 10 other websites for comparison, with an eye towards how to handle Duration, Difficulty, and (possible addition to the model) Age.

Notes and my recommendations are here: https://public.etherpad-mozilla.org/p/duration-age-difficulty

In addition to @alicoding, @alanmoo, @sabrinang, and @gideonthomas, I'd love input from @chadsansing and @zee-moz. 

Relevant background for Chad and Zannah especially:
 * We are currently designing what will be the beginnings of a curriculum database. The first step is designing the model to match the existing content on the Learning site, so we can migrate it all to a database. 
 * This process requires some thinking about how we want to standardize certain pieces of information common to all/most lesson plans and modules. Duration, Difficulty, and Age/Grade Level are three such pieces of information. In the etherpad linked above, I'm looking at how we currently capture information about those three facets across our existing curriculum (just looking at content on the learning hub site right now, but ideally this applies across the board), and making recommendations about how we might want to standardize them moving forward. 

Would love your thoughts! I'm primarily thinking about this from the perspective of someone who might be *searching* the database to find content, though it should also be sensical to someone who's *adding* content to the database.

**Comment by hannahkane** [comment]
Also, all on this ticket might want to review the following tickets and docs linked within them. This is work @sabrinang and @flukeout did on the concept of a curriculum database earlier in the year:
 * [Curriculum Database Research Findings](https://github.com/mozilla/learning.mozilla.org/wiki/Curriculum-Database-Research-Findings)
 * [Benchmark Curriculum Database](https://github.com/mozilla/learning.mozilla.org/issues/1443)

**Comment by chadsansing** [comment]
@hannahkane, commented on the MoPad.

**Comment by hannahkane** [comment]
Thanks, @chadsansing. Commented back!

Curious to know what others think, too.

**Comment by zee-moz** [comment]
For some of our materials, prerequisites are maybe more useful that beginner, intermediate, advanced. You can be "advanced" in your coding ability, but you might not have basic GitHub, be able to write R functions, know Python, etc. 

@hannahkane I wonder if it might make sense to review some of the materials from MSL in addition to what's on the learning site?

handouts from the WOW, listed on this page: http://mozillascience.github.io/working-open-workshop/index.html
lots of fellowship resources here: https://science.mozilla.org/resources
our SG folks also generate all this stuff:  https://github.com/mozillascience/studyGroupLessons

**Comment by alanmoo** [comment]
I threw some comments on the pad as well

**Comment by hannahkane** [comment]
Thanks to @chadsansing @zee-moz and @alanmoo for commenting so far. I feel like we're converging on a good solution, but could use more input from others before we finalize.

**Comment by hannahkane** [comment]
Also - "finalize" could mean we come up with a proposal to test (using some low-fi methods) with members of our target audience. cc @sabrinang @flukeout

**Comment by alicoding** [comment]
I added few comments in the pad.

**Comment by hannahkane** [comment]
Thanks, all. I'm feeling like a good next step is to move this into Design, with some wireframes. Will see if we can fit that into the next heartbeat.

**Comment by hannahkane** [comment]
Good discussion. Closing this ticket, but referencing in wireframe ticket: #2114
