### ISSUE TITLE
QA new Clubs Pages on Staging

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2087]
The New Clubs Pages are live on Staging....
https://learning.mofostaging.net/en-US/clubs

Thanks everyone for your help and creativity! Now, let's do some QA. Please look over the pages and leave comments in this issue if you find anything that needs to be changed. Please indicate which Tab you found the problem so it will be easier to track down.

cc @jvallera @hannahkane @sabrinang @amirad @gvn

**Comment by hannahkane** [comment]
Looks beautiful!

About tab: has "Recruit Members" listed twice in the "Elements of a Mozilla Club" section

**Comment by jvallera** [comment]
Thanks @flukeout Very excited for this. Here are a few comments:

1. Will the guides page still be available as a https://learning.mozilla.org/en-US/clubs/guides? I see that guides are included in the "running your club" tab and wondering which one you think is best. 
2. On the "about mozilla clubs" tab in the elements of a mozilla club section - can I give you different links to those? Not sure how I missed them until now, but I think we have better content to link to under each of the elements.

**Comment by hannahkane** [comment]
Two small typos:

"Start a Club" tab - in the "What support can you expect..." section, the third bullet point should include "tools" (plural) instead of "tool".
"Running Your Club" tab - in the Twitter CTA at the bottom, it reads "Connecte" instead of "Connect"

**Comment by hannahkane** [comment]
Last thing - I'm wondering if we want to keep the CTA in the hero block. I'm afraid our conversion rate will go down since the CC application form is only accessible from the middle tab.

**Comment by jvallera** [comment]
@hannahkane not sure exactly what that means, but I think I was thinking along those lines. Am a little worried the "apply" button will get lost in the middle tab.

**Comment by gvn** [comment]
Since the headshots are small you'll need `flex-grow: 1` on the wrappers and `width: 100%` on the images:

<img width="1399" alt="screen shot 2016-08-15 at 2 21 11 pm" src="https://cloud.githubusercontent.com/assets/206379/17680190/ce58c110-62f3-11e6-9ff9-0b6b8722385f.png">

**Comment by hannahkane** [comment]
Sorry, @jvallera - my comment was full of nonsense! I meant to ask if we'd want to keep the "Apply to Be a Club Captain" button under the title/tag line at the top of the page (regardless of the tab) so that we don't unintentionally reduce the number of people who click on it and fill out the form. The "conversion rate" I was referring to was # of people who visit the page and then go on to fill out the CC application form.

**Comment by jvallera** [comment]
Thanks @hannahkane. I understand now and think it is best to keep it under the title if possible.

**Comment by sabrinang** [comment]
The page is lookin good @flukeout 

small adjustments could be made on mobile view:
- center icon tabs on mobile <img width="503" alt="screen shot 2016-08-15 at 3 03 03 pm" src="https://cloud.githubusercontent.com/assets/2492510/17681317/e271338e-62f9-11e6-8a96-c80d51bb53dc.png">

- resize (language) to match smaller body copy on mobile
<img width="388" alt="screen shot 2016-08-15 at 3 08 03 pm" src="https://cloud.githubusercontent.com/assets/2492510/17681351/1c781f7a-62fa-11e6-890f-3c0ce39e4e98.png">

**Comment by flukeout** [comment]
Okay, looks like the plan will be roll this back and out master. Too many changes needed.

**Comment by flukeout** [comment]
@jvallera...

1. The guides will only be available in the 3rd tab of the new pages
2. Please provide the new links for the Elements section
3. The map sometimes appears funky for me too, but usually looks good after a refresh
  * It's unrelated to the new layout though, so we can tackle that as a separate issue.

**Comment by flukeout** [comment]
Keeping this issue open, but the critical issues that were found are addressed in this PR - https://github.com/mozilla/learning.mozilla.org/pull/2097

**Comment by jvallera** [comment]
@flukeout here are the new links for the elements section.

Recruit Members: http://mozilla.github.io/learning-networks/clubs/growing-community/#facilitation-tips

Find a Venue: http://mozilla.github.io/learning-networks/clubs/partnering-local/#partnering-with-local-businesses

Develop a Learning Plan (same as what you have already) : https://iteachtheweb.files.wordpress.com/2015/11/typical-session1.pdf

**Comment by flukeout** [comment]
Thanks @jvallera. Hey @gvn or @Pomax, would either of you be able to update the Example links in the Elements of a Club section (in the About tab) before (and if) this stuff goes live?
