### ISSUE TITLE
Add new activities to Web Lit Map

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#2095]
Since we published the Web Literacy Map, we've added lots of new activities. The map should be updated to reflect the new activities.

@alicoding - I'm pretty sure I can do this myself. Wondering if it would be disruptive if I do this now? Would you prefer this happens after the migration to the new model?

**Comment by alicoding** [comment]
@hannahkane I don't think it will disrupt any of the work I'm doing, so you can go ahead and update the Web Lit Map 👍
