### ISSUE TITLE
Update club form to use "name" instead of clubname and "owner" instead of name

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning.mozilla.org#2100]
There is only one "Name" field showing on the admin side of the applications, but 2 name fields in the application itself: "Name" and "Name your Club" I'm seeing applications with the name field listing both Club names and Club Captain names (either/or) on the admin side.

Can someone double check which name field is coming through on the admin site? If it is the "Name your club" field, perhaps we should rename to be "Club name" so those that are only reading the 1st word understand what we are looking for.

@hannahkane

**Comment by hannahkane** [comment]
@pomax - can you please look into this? Thank you!

**Comment by KGorr** [comment]
Checking in on this - the last 5 applications have their personal name listed in the club name section. If I approve them, the personal name shows up on the map and not their club name. I was able to check it against the old interview form, but now that has been discontinued I'm having to email each CC to get the name of their Club before approving.

**Comment by ldecoursy** [comment]
Ping @hannahkane @Pomax Just checking if you think this will be resolved this week? Sounds like new applications are coming in quickly and currently they require 1:1 follow-up and manual updating until we can get this sorted out. Thanks!

**Comment by Pomax** [comment]
hm, looking at the schema there is an "owner" and a "name", with the "name" supposed to be the club name, not the user's name. It's possible the club listing component is pulling the wrong field, or the club application form is posting the wrong field.

**Comment by Pomax** [comment]
Looks like the new form is using the wrong field names. It's using `name` for the user name, and `clubName` for the club's name, which would absolutely lead to this problem.
