### ISSUE TITLE
logic flaw in web lit map -> activity mappings

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#2107]
I just submitted a PR to add a bunch of new activities to the web lit map. I noticed that some of the activities aren't showing up when a corresponding skill is selected in the map. For example, the Project Playlist activity doesn't show up when you select "Compose" on the map, even though the activity has been properly mapped in the code. 

This situation happens at least eight times. I believe it happens because we assign 21st Century Skills (Problem-Solving, Creativity, Communication, Collaboration) to *both* individual Activities *and* to Web Lit Skills (e.g. Search, Remix, Revise). When the Activity's assigned 21st C Skills don't align with the 21st C skills associated with the Activity's Web Lit Skills, the Activity won't show up in the list. 

Example:
 * Project Playlist has Compose as a Web Lit Skill
 * Project Playlist has Creativity as its only 21st C Skill
 * The Compose skill has been mapped to Problem-Solving and Communication (21st C), but *not* Creativity
 * Therefore, Project Playlist does not show up when user selects "Compose" on the map

I don't think this is a bug in the code, but I think it's a bug in our logic around how the Web Lit Map works.  

It feels like the right answer is to either:

1) NOT map 21st C Skills to Web Lit Skills, but instead only map them to Activities. This would require fundamentally changing the design and UX of the map. (Boo. Hiss.)

2) (my preferred solution!) NOT map 21st C Skills to Activities, but to instead have the previously defined 21st C -> Web Lit skill mapping determine which 21st C skills apply to each Activity. So, if Project Playlist relates to the Compose web lit skill, then it automatically gets Problem-Solving and Communication as 21st C skills based on the relationship we've already defined between Compose and P-S / Comm. 

I realize this is super confusing. Happy to jump on a call about it. Should probably include @anmechung @chadsansing @alicoding @sabrinang @alanmoo @ScottDowne

**Comment by chrislarry33** [comment]
Great bug find @hannahkane Can we wait for @anmechung to get back from PTO before making a call here? I trend to option #2 as well for the record.

**Comment by anmechung** [comment]
@hannahkane +1 on picking this up, and I think I get it and am trending to option #2 as well, but would be great to jump on call after my PTO just to make sure I'm understanding clearly!

**Comment by alanmoo** [comment]
Option 2 makes sense to me. I'm not familiar with the code driving this though, so I couldn't guess at how much lift either option will be.

**Comment by ScottDowne** [comment]
I'm not yet following option 1 and 2, but I think I understand the issue, and I think I understand the solution, which might actually be what you're getting at in option 2?

Which 21st century skill we display in a selected web lit skill is hard coded in this file: https://github.com/mozilla/learning.mozilla.org/blob/master/pages/web-literacy/weblitdata.js#L13

In that file, it connects problem solving and communication with compose, so it doesn't display anything without problem solving or communication. In this case, it's just creativity. We could easily remove that file, and make it dynamic.

So instead, when compose is selected, it adds all activities with compose, then disables all 21st century skills not used in that list of activities. If a 21st century skill is added to the data in an activity that previously wasn't, the code should just figure it out, and add it.

**Comment by ScottDowne** [comment]
Also, yes, super confusing issue and data. The relationships between the data is not super clear or linear. I feel like I'm looking trying to look at a 4D cube.

**Comment by ScottDowne** [comment]
Trying something real quick.

**Comment by ScottDowne** [comment]
When I run my test, I get this as my map:

![weblit](https://cloud.githubusercontent.com/assets/197334/17814381/aa7bd644-65fd-11e6-9a79-31eecd7c034e.png)

What this exposes is contribute, protect and revise seemingly are not used in any activities here https://github.com/mozilla/learning.mozilla.org/blob/master/pages/web-literacy/activitydata.js?

**Comment by hannahkane** [comment]
@ScottDowne - that map will look different once https://github.com/mozilla/learning.mozilla.org/pull/2106 gets merged (currently failing, though). That PR adds a bunch of new activities, many of which are connected to Contribute, Protect, and Revise. 

Your solution makes sense to me, assuming the performance issues aren't a blocker. It looks like the 21st C Skill checkboxes will becomes slightly less meaningful, since it looks like each of the 21st C skills will be associated with most if not all of the web lit skills.

**Comment by ScottDowne** [comment]
Ah, I just took a look at your patch, my proposed changes shouldn't get in the way, as all my changes are in the weblistdata.js file, and your patch doesn't touch it. I can push it up if you want to take a look.

I think the check boxes interestingly become more useful as a filter, though. As I can select it now to remove things in the list. Example, if I click compose, then deselect creativity, I get an update list with projectplaylist removed.

Also I noticed another weird example my test doesn't consider. "Welcome to My Mixtape" has synthesize as a web lit skill, but its topic is write. Synthesize is listed under read. So "Welcome to My Mixtape" is not yet included in the synthesize filter.

**Comment by ScottDowne** [comment]
And the performance issue is fine, as I do the work once at build time.

**Comment by hannahkane** [comment]
Hadn't even considered the Topic piece. Do we need each activity to have a Topic? I was hoping we could avoid that. How is Topic used aside from providing the segment groupings in the visualization?

**Comment by alanmoo** [comment]
Let's keep in mind not just what the logic is and what we can do with the data, but how people might use this. We might add ways to parse the sessions that are consistent with the data but aren't actually useful if we're not careful.

**Comment by hannahkane** [comment]
Great point, @alanmoo. It might be good to revisit notes from the focus groups we did on the Web Lit Map last year. I'm curious to know, for example, if the "Read, Write, Participate" model offered value to people, or if that's something we built in because it was useful for our narrative.

**Comment by ScottDowne** [comment]
Synthesize is actually a web lit skill under read, write, and participate because there is an activity under each that has synthesize.

We only show it under read, which I think might be a fairly fundamental flaw in the circle. The circle wants to display tree like data, and our data isn't really a tree...

**Comment by hannahkane** [comment]
I checked in with @anmechung and @chadsansing about this earlier. Some notes:

 * @ScottDowne - your solution re: 21st C skills makes sense. Can we implement that for realsies?
 * Regarding the topics, An-Me says that users in our focus groups didn't ask for or particularly identify with these as filters. I'm wondering if we should just remove them from the framework entirely. Can you help me think through the repercussions of that? We'd have to remove that inner ring from the web lit map design; we'd have to remove content from the landing page, and we'd have to remove the Topic from each Activity. Are there other repercussions I'm not thinking of?

**Comment by hannahkane** [comment]
@alanmoo and I had a chance to talk through this in person. Just going to capture some notes here; no real specific action steps.

Value of web lit map is in showing our POV about web literacy, and providing pathways. But perhaps this doesn't require showing filtered activity lists as part of the map interaction. Given the work we're doing to make the [Teaching Activities more discoverable](https://github.com/mozilla/learning.mozilla.org/issues/2114), maybe we only need to point people to the Activities page, rather than reproducing some of that functionality on this page.

We could maintain the mapping of 21st Century Skills to Web Lit Competencies, without worrying about breaking our own logic with the Activities filters.

**Comment by alanmoo** [comment]
Should something be happening with this right now? I noticed it's open and in this milestone, but not sure why.

**Comment by hannahkane** [comment]
Thanks for the reminder, @alanmoo. I'm going to close this confusing ticket and open up a new one to address later. Doesn't feel urgent to resolve now.
