### ISSUE TITLE
Implement way to describe partially translated locales

### ISSUE THREAD

**Issue by alanmoo** [mozilla/learning.mozilla.org#2111]
For the Maker Party updates, we're going to need a way to indicate if the site has been partially (only Maker Party) or fully localized. Perhaps we do this with another env variable? @alicoding

**Comment by alicoding** [comment]
@alanmoo I suspect with the given timeline we won't be having any other locale on our site at all except for `en-US`, so maybe we don't really need to add extra checks?

**Comment by alanmoo** [comment]
Because we're not turning on l10n site-wide until we finish the work related to django/web lit maps?

**Comment by alicoding** [comment]
@alanmoo so maybe for now we can only hardcode for `en-US` to show the sidebar and the rest to disable them?

**Comment by alanmoo** [comment]
Follow up from call: We're going to hard code the desired locales' maker party page routes to the routes list. This way when the maker party page is requested, we can do our normal locale negotiation process. Then we'll add some logic to the page component which says "if this isn't one of the supported locales (using the env variable, only en-US for now), hide the sidebar" since we're not actually turning on other locales yet due to all the other work that needs to be done.

**Comment by alanmoo** [comment]
@valianttry What languages are we targeting for the Maker Party pages l10n?

**Comment by valianttry** [comment]
Our Tier 1 languages: English, French, German, Spanish, Polish

Tier 2: Italian, Dutch, Czech, Bulgarian

**Comment by alicoding** [comment]
@valianttry are we targeting more than one Spanish? Like es-ES and es-MX? Same question for the rest in the list here.

**Comment by valianttry** [comment]
This is the "EU Copyright Campaign" so... no. only es es.

**Comment by valianttry** [comment]
@ScottDowne already set up a similar Pontoon repo for advocacy.mozilla.org -- maybe ask him for guidance @alicoding 
example: https://github.com/mozilla/advocacy.mozilla.org/blob/master/locales/en-US/copyright-petition.properties

**Comment by alicoding** [comment]
@valianttry this is actually not for Pontoon, but will check with Scott tomorrow about locale code because we are trying to implement the logic for Marker Party stuff.

**Comment by hannahkane** [comment]
@alanmoo @alicoding - can one of you update this ticket, please? I've lost the thread on this.

**Comment by alanmoo** [comment]
I'm planning on confirming this PR tomorrow morning. Scott said it looks logical to him, so I'm just gonna make sure everything's still good after the recent build changes. 

On Tue, Aug 30, 2016 at 6:14 PM hannahkane

<
mailto:hannahkane <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

https://github.com/alanmoo https://github.com/alicoding
- can one of you update this ticket, please? I've lost the thread on this.

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/mozilla/learning.mozilla.org/issues/2111#issuecomment-243598724
, or
