### ISSUE TITLE
Organize handoff between Maker Party logic and page updates

### ISSUE THREAD

**Issue by alanmoo** [mozilla/learning.mozilla.org#2113]
I think this should be pretty cut and dry, let's just make sure we've got the plan documented for implementing the new Maker Party pages.

@ScottDowne you're building the pages, right? I imagine you should just be able to work on a branch off master and only make changes to the route set (including url redirect?) and the page components themselves. On a separate branch, I can work on the logic handling for l10n routing/sidebar hiding. Once you've merged your updates in (with l10n support), I can then merge the logic in for partial locale support. 

Does this all make sense?

**Comment by alanmoo** [comment]
I think we can close this, right @ScottDowne?

**Comment by ScottDowne** [comment]
Yup, closing! :rocket:
