### ISSUE TITLE
Create wireframes for /Activities page based on new model

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#2114]
We are migrating meta-data about our Activities to a database, so that we can:
 * standardize the data stored
 * better handle localization / remixing
 * display information about Activities in multiple places, without worrying about syncing issues
 * offer a better experience for users who are browsing/searching Activities

The model has been [designed](https://github.com/mozilla/learning.mozilla.org/issues/2031), but we're at the point where having wireframes for the front-end experience would help guide our decision-making moving forward.

Wireframes needed:
 - [x] The [Activities landing page](https://learning.mozilla.org/en-US/activities), which might be re-imagined with search/browse functionality
 - [x] The landing page for a collection of Activities (see https://learning.mozilla.org/en-US/activities/web-lit-basics/ as an example), which might be re-imagined to better display the meta-data stored (including, notably, links to localized or remixed variations  of each activity)

Out of scope for this ticket, but likely coming soon:
 - [ ] A workflow for adding or submitting content to the database
 - [ ] Adjustments to how the [Web Lit Map](https://learning.mozilla.org/en-US/web-literacy) displays filtered lists of Activities

Relevant background info:
 * [Discussion of Age, Difficulty, Duration](https://public.etherpad-mozilla.org/p/duration-age-difficulty)
 * [Curriculum Database Research Findings](https://github.com/mozilla/learning.mozilla.org/wiki/Curriculum-Database-Research-Findings)
 * [Benchmark Curriculum Database](https://github.com/mozilla/learning.mozilla.org/issues/1443)

**Comment by hannahkane** [comment]
Assigning to @flukeout as per agreement amongst designers, but cc @sabrinang @alanmoo and @alicoding who will be involved with the implementation

**Comment by flukeout** [comment]
@sabrinang I remember seeing some wireframes that you made for something very similar to this, would you mind dropping in a link?

**Comment by sabrinang** [comment]
I have the wireframes from a while back when we were brainstorming curriculum database ideas: https://drive.google.com/file/d/0B4Q8pzCpDS_eZXJPZjJaYVAzVHM/view

**Comment by flukeout** [comment]
@hannahkane What were the conclusions reached from the Age, Difficulty & Duration discussion?

**Comment by flukeout** [comment]
Getting the ball rolling with "Our first wireframe design, come on down...!"

![image](https://cloud.githubusercontent.com/assets/25212/18180911/d1bc2d36-703d-11e6-9d1e-299dd7a084e2.png)

**Comment by hannahkane** [comment]
Hooray. @flukeout - do you want feedback now, and, if so, what kind?

**Comment by flukeout** [comment]
No, not yet please - I'll nuke it for now and post when I'm ready for some feedback.

**Comment by flukeout** [comment]
Posted some ideas for a search & filter UI...
* https://redpen.io/md3f0bc915aafe3a05

From doing this so far the main thing I wonder is: Will people want to filter by just one option at a time for each filter type, or several options. For example...

* For difficulty...
  * Will people prefer to filter by a combination like, Beginner & Intermediate
  * Or just one category at a time

**Comment by flukeout** [comment]
**Round 1 Ready for Feedback**
I created two wireframes that contrast some approaches to search & filtering:

* Option A - https://redpen.io/vybcfa80a965273712
  * Expandable filtering options
* Option B - https://redpen.io/wmee515e9548b95820
  * Filtering options available below search

**Questions**
* The age filter is the one that needs the most attention I think, we need to decide what is useful to filter on.

**Next Up**
* Let's meet as a group to discuss these
* Based on that, we'll come up with another set of more wireframes
* We will use those wireframes to get feedback from more people and choose a final option

cc @hannahkane @chadsansing 


I think we can use these as a talking point with @chadsansing to figure out some

**Comment by hannahkane** [comment]
Thanks, @flukeout. Great place to stop and have a discussion with @chadsansing. I'll put something on the calendar.

Added some comments to redpen in the meantime.

**Comment by hannahkane** [comment]
@alicoding - you may want to follow along in this ticket to warn us of any repercussions for the db model.

**Comment by alicoding** [comment]
Title, Author, Age, Tag, Image, Duration. Nothing new added 👍

**Comment by xmatthewx** [comment]
@flukeout – @hannahkane suggested I join you to think through a testing plan. Glad help if needed.

**Comment by flukeout** [comment]
@alicoding do we get access to 'date created' or 'date added' or something like that?

**Comment by alicoding** [comment]
@flukeout they are not the same `date created` as to when the resources were created, but rather when it was added to the DB? if it's the same then we can totally expose that.

**Comment by flukeout** [comment]
I don't think it would be that useful, since when we migrate all of the activities will have the same date. I wonder if it is important to have a Date Created field to sort by, seems like it might. I'll check with @chadsansing

**Comment by alanmoo** [comment]
I know this is a wireframe, but I'd like to get ahead of any issues- @flukeout Do you have a plan for the inline filters? I'd like to throw in my vote for them being standard select elements, possibly styled when closed (but native when expanded, because customization ease)

**Comment by flukeout** [comment]
Hey @alanmoo - I hadn't thought that far ahead. Using the default elements would limit us to one selection per filter, correct? What has your experience been with using [bootstrap dropdowns](http://getbootstrap.com/components/#dropdowns)? Might be a good option since we are using bootstrap in various places now.

**Comment by alanmoo** [comment]
Ah, yes, though we could also then use checkboxes. It just gets a bit more complex wrt accessibility though we can figure it out.

**Comment by flukeout** [comment]
Feedback via @xmatthewx 

**Likes**
* It doesn't feel like a tech database, favoring plain, readable labels (teen) over something falsely more scientific (age 13-19). Others might disagree, but personally I'd push for this. 
* Lots of smart design choices in there I'd like to see elsewhere on the web! (e.g. easy to clear or turn off filters)
* I like the filter option that is there when you need it, unobtrusive when you don't.
* I like the flexibility of collections to feature things. 

**To consider**
* Remove author from the Collections, only Mozilla makes them for now.
* Consider the user who wants to see everything for an age group, regardless of topic. That approach to browsing isn't readily obvious.
  * Can test this need in the research / discussions.

**Comment by flukeout** [comment]
Feedback from @chadsansing ...

* Would like to see both Web Lit skills and 21C skills incorporated
  * Displayed within the results list
  * Ability to filter & search using them 
* Consider what happens to people who rely on the activities listed on the current Activities page
  * How will they find what they're used to finding?
  * Could we have a "featured activities" section or tab and keep them there
* Consider the various audiences that might be looking for content
  * For example Club Captains
  * Can we organize our landing page by audience versus topics?
* We won't have many activities aimed specifically at kids
  * We could replace the age filtering in the wireframes with a _suitable for kids_ checkbox instead
* Suggested talking to...
  * Julia about Clubs needs
  * An-me about web lit map integration


**Next Up**
* @hannahkane will schedule meetings with folks mentioned above
* I'll update the wireframes with...
  * Some way to filter & search by Web Lit & 21C skills
  * Different approach to filtering by age that takes into account that...
    * Teen & Adult content probably isn't different enough to bother with the distinction
    * We have very few activities for Kids

**Comment by chadsansing** [comment]
@flukeout, @hannahkane - I was remiss and I apologize for adding a next step, but we should include Hive and consult with Meghan about Hive needs for curriculum and contribution.

**Comment by hannahkane** [comment]
Thanks @chadsansing. Will also be sure to set up time to talk to @mcdermott415.

**Comment by flukeout** [comment]
Main feedback collection from meeting with An-Me and Julia...

* Liked the ability to filter and search with keywords
* Liked ability to group content into collections
* Wnated to see how users might filter by language
* Wanted to see ways how the web lit map (and skills) would be incorporated as part of the explore and filter experience

**Comment by flukeout** [comment]
I'm going to close this issue now and create another one to test the prototype I made based on this redpen - https://redpen.io/jn7216fea59754dfad
