### ISSUE TITLE
Club Captain Testimonial Fixes

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2130]
From an email by @amirad...

* [x] Update location for first two club captain testimonials to "South Africa"
* [x] Fix spelling of first club captain's name, it's "Asisipho"

**Comment by hannahkane** [comment]
@flukeout - I'm going to take a crack at resolving this, if that's alright. Don't want to forget about this.

**Comment by hannahkane** [comment]
@flukeout - actually, it turns out I don't know how to fix this. I thought it would require changing the contents of messages.properties, but that doesn't seem to have worked. Is this something you could look at today?

**Comment by flukeout** [comment]
Definitely - will work on it now.

**Comment by flukeout** [comment]
@hannahkane - You probably did the right thing, but changes to the locale files aren't reflected on the site until you restart your local server.

**Comment by hannahkane** [comment]
oh! good to know. thanks. :)

**Comment by flukeout** [comment]
Addressed in https://github.com/mozilla/learning.mozilla.org/pull/2213

**Comment by TheoChevalier** [comment]
You may want to fix this typo in the same PR https://github.com/mozilla/learning.mozilla.org/blob/master/locales/en-US/messages.properties#L170 Clup vs. Club
