### ISSUE TITLE
Content for Hive section of Learning site

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#2137]
Our roadmap includes a project where we'll sunset hivelearningnetworks.org after adding a Hive page to the Learning site.

If this is still desirable, we should start preparing for it now by developing a content document.

This project would be very similar to the Gigabit site work that's happening now. It might be good to take a look at the [wireframes](https://redpen.io/p/ku41f3c8ea603732e1) for that to see if we can follow a similar model.

Also, these are notes from an earlier email exchange with @ldecoursy (though I'd encourage us to revisit some of the decisions below based on recent updates to the Clubs page and upcoming updates to Gigabit):

Here’s what we’re thinking about including on a Hive page on teach.mozilla.org:
 * Updated copy about Hive, and its relationship with Mozilla
 * Links to Hive cities (individual websites and twitter)
 * Planet Hive blog (currently the #Hivebuzz tab on hivelearningnetworks.org) so there is some dynamic content

Key pieces we’d leave behind are
 * Map with contacts - originally we thought we’d have 30 cities, but now with fewer, the map seems less useful. Also, the contacts have been difficult for me to update, I’m thinking that information is better to live on the individual Hive city sites anyway
 * Resources - we’re evaluating which individual resources might go into a Hive affiliate kit instead of making them all open and available (with feedback and guidance from legal). 
 * Connect - outdated - Hive badge is old, and no longer doing separate Hive newsletter

@mcdermott415—is there someone you'd recommend I work with to develop the initial content document?

**Comment by mcdermott415** [comment]
Thanks for this update Hannah. I'll have an answer for who on content next
week. Lots of moving parts and decisions embedded in this straight forward
ask.

M

**Comment by hannahkane** [comment]
@mcdermott415 - I'm going to remove this from our queue until we have a stakeholder identified. If there's no rush on your end, there's no rush on ours.

**Comment by mcdermott415** [comment]
Cool - no rush. Thank you.

**Comment by hannahkane** [comment]
Closing this in light of conversation with @mcdermott415 about Learning site needs generally.
