### ISSUE TITLE
badges don't have a social share system atm

### ISSUE THREAD

**Issue by Pomax** [mozilla/learning.mozilla.org#2154]
Ran into this while fixing up the code based on eslint rules, the badge-single.jsx file in principal has places to put in social share code, but currently does not do that because souktel never implemented it and we deprioritized it at the time so it fell off the plate.

Not sure which labels, pipeline, and milestone this should be under.

/cc @gideonthomas @hannahkane

**Comment by hannahkane** [comment]
Adding as a candidate for the next milestone, but more as a reminder to discuss it than an actual commitment.

**Comment by Pomax** [comment]
We can use URL sharing for twitter and facebook, so we don't need to load "their buttons".
```
https://www.facebook.com/sharer/sharer.php?u=mozilla.org&t=omgchex
https://twitter.com/intent/tweet?text=<message>
```

Concern: make sure there's OG tags that determine the badge as being the opengraph major image thing.
