### ISSUE TITLE
Conduct interviews with potential curriculum localizers

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#2159]
- [ ] Write script. See outline in [this doc](https://docs.google.com/document/d/1sLugqI1WMZTHHbO9W31sY2zQACcp6G2R-niys3OjCS4/edit#)
 - [ ] Schedule
 - [ ] Conduct interviews
 - [ ] Conduct analysis, and draft report.

**Comment by hannahkane** [comment]
Thanks for the feedback on the [interview script](https://docs.google.com/document/d/1MqE1ZkCOAm_lXbVVdNnlKoFV046lavfK29AURqy82JA/edit#), @jvallera and @gideonthomas. I've incorporated your feedback. Want to give it one more look?

**Comment by jvallera** [comment]
It looks great! Glad it was helpful. Thanks for organizing.

**Comment by hannahkane** [comment]
Closing this. Will likely revisit once our Curriculum Localization Campaign plan is in place.
