### ISSUE TITLE
Gigabit pages UI

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#2172]
We almost have final wireframes for the new Gigabit pages on the Learning site. Let's move to the UI stage.

**Comment by xmatthewx** [comment]
Title says Github. Do you mean Gigabit?

**Comment by hannahkane** [comment]
Actually, I meant grubhub.

JK. Good call. :)

**Comment by hannahkane** [comment]
Passing on to implementation phase, some copy changes pending
