### ISSUE TITLE
Create separate localizable entry for Sign Up string

### ISSUE THREAD

**Issue by TonnesM** [mozilla/learning.mozilla.org#2173]
Apparently a localizable "Sign Up" entry is currently shared between the "Sign in or Sign Up" string on the main page and the button needed to sign up for the news letter on the community page. Since some locales may need to use different localizations for them (one is more like "registering", the other refers to "subscribing"), there is no chance this can be fixed at this point. (In general, it’s never a good idea to share localizable strings for this reason.)

Please create a separate entry for the signup button to make this possible. Unless community page content is about to change, since some of its strings do not appear to be localizable at all.

**Comment by peiying2** [comment]
@alicoding could you help answer this question?

**Comment by alicoding** [comment]
I can't find the word `Sign Up` in the learning site that's being shared with `Sign in or Sign Up` currently in this repo? Can you point me to where exactly you are seeing this?

**Comment by TonnesM** [comment]
The first occurence is on https://learning.mofostaging.net/en-US/ (top left) and the second on https://learning.mofostaging.net/en-US/community (yellow button) for the newsletter.
The Sign Up string appears one time in https://pontoon.mozilla.org/nl/mozilla-learning-network/all-resources/?search=sign+up&string=153551 for my locale. For some reason I don’t see a preview on Pontoon right now (nor a staging preview), but I’m sure both of them changed when editing this string only earlier.

**Comment by alicoding** [comment]
CC @alanmoo this is an interesting issue:

Top left of the learning site we have 3 strings `Sign up` `or` `Sign in`

The interesting part is that the word `Sign up` and `Sign in` is actually being shared as pointed out above and the problem here is that it could have been translated differently depend on the context of the page (paragraph or wherever its being used).

**Comment by TonnesM** [comment]
Exactly. Why not just add a second Sign Up entry for the newsletter section, copy their contents for all locales (if available) and notify localizers if need be in order to let them change either of them when needed?

While at it, the yellow Sign Up button currently "sticks" to the line ending with "privacy policy", and it uses auto-capitalization, which may be disliked by localizers. One could think of a) moving the button (e.g. to the right of, or below the email field) and b) letting localizers decide to capitalize where/when appropriate.

**Comment by alanmoo** [comment]
I believe I understand the initial problem and can address that.

With regards to the button sticking, I've created #2216.

@TonnesM: For the button capitalization, could the meaning change by using uppercase or is that a matter of stylistic preference?

**Comment by TonnesM** [comment]
Thanks. The meaning would not change for my locale, it’s stylistic preference allright. Not sure how it affects others, but think leaving them auto-capitalized would not be a real issue.

**Comment by alanmoo** [comment]
Ok, then we'll stick with the CSS as it is.
