### ISSUE TITLE
Two additions to existing Mozilla Gigabit site

### ISSUE THREAD

**Issue by jenntbeard** [mozilla/learning.mozilla.org#2174]
We have two items that need to be added to the existing [Mozilla Gigabit site](https://www.mozilla.org/en-US/gigabit/), to the [apply page](https://www.mozilla.org/en-US/gigabit/apply/). The deadline for Round 2 funding for our grantees is October 18, 2016. 

The following items should be added under the 'How to Apply' section:
The first item - a .pdf form link - should be added to item number 3 - …using our application form and [frequently asked questions document](http://mzl.la/GCF_FAQ).

Add a sixth item to the list with the text: "Watch [this video](https://vimeo.com/180975946) walking you through the full application process."

**Comment by hannahkane** [comment]
@alanmoo @mmmavis - are either of you available to do these small changes this week?

**Comment by mmmavis** [comment]
I'll try to have a PR up later today.

**Comment by mmmavis** [comment]
I filed a ticket on Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1301472

**Comment by mmmavis** [comment]
PR filed: https://github.com/mozilla/bedrock/pull/4333

**Comment by hannahkane** [comment]
Thanks, @mmmavis!

**Comment by mmmavis** [comment]
Hi @jenntbeard 

I wanted to check with you to see if there's a special reason to link the FAQ doc via a short link instead of https://drive.google.com/file/d/0B1Tu07mQk89LRTlCRHA1TjBYeGc/view (see [suggestion](https://github.com/mozilla/bedrock/pull/4333#discussion_r78155096))

**Comment by mmmavis** [comment]
Live now: https://www.mozilla.org/en-US/gigabit/apply/ ✨

**Comment by hannahkane** [comment]
Thanks, @mmmavis!

**Comment by jenntbeard** [comment]
Fantastic, thanks all!

--
Jenn Beard
Gigabit Fund Manager
Mozilla Learning Network
@jenntbeard
