### ISSUE TITLE
Remove Live Embed streams from MCW & MCC pages

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning.mozilla.org#2182]
Per https://github.com/mozilla/learning.mozilla.org/issues/2094, we need to remove the live stream embed section from the September community call and workshop landing pages and replace with a note that says, "We've moved to YouTube Live this month! Watch the live stream on our [YouTube Channel](https://www.youtube.com/channel/UC64W_SqCxhcTUwVpuSQWjEg). You can still participate with us on the etherpad below during the call."

The MCW is September 13, so that page needs to be updated ASAP.

cc: @hannahkane @ldecoursy @chadsansing

**Comment by hannahkane** [comment]
Filed a PR to make the above change. @KGorr - we aren't planning to do a push to production until this Thursday. Will that cause problems for you?

**Comment by KGorr** [comment]
Nope @hannahkane should be fine. Thanks!
