### ISSUE TITLE
Create M-less version of 21st Century Skill badges

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#2184]
We need to be able to share the graphics for the 21st Century Skill badges with partners who don't want to use the version with Mozilla branding.

Can we create versions of the four 21st Century Skill badges without the mozilla M, and put them in a publicly accessible place?

@anmechung - I'm looking at the [designs](https://redpen.io/nh3f2664418e559443), created last autumn, and it seems like we had four different possibilities for the Collaboration badge. Do you want to pick a winner?

**Comment by anmechung** [comment]
@hannahkane I think we picked the two hands shaking previously when @pomax put together demo for issuing 21C badges?

**Comment by anmechung** [comment]
@hannahkane when do you think these might be ready?  thx

**Comment by hannahkane** [comment]
Since I didn't hear about this until after the current heartbeat had started, I filed this for the heartbeat that ends September 30th.

Is there a more pressing deadline we need to know about?

**Comment by anmechung** [comment]
That will work!  Thanks

**Comment by hannahkane** [comment]
@anmechung - did we get this from Matt already?

**Comment by anmechung** [comment]
Yes!  Closing.
