### ISSUE TITLE
Clubs page tabs are broken on staging

### ISSUE THREAD

**Issue by alanmoo** [mozilla/learning.mozilla.org#2185]
https://learning.mofostaging.net/en-US/clubs - I think this broke with Mofo UI 1.6, as I wasn't seeing it locally until I did an `npm install`

**Comment by gvn** [comment]
Yes, this is because of bumping to 1.6 without adding the new `mui-` prefixes in our overrides (I have that in a pending PR here https://github.com/mozilla/learning.mozilla.org/pull/2170).

**Comment by gvn** [comment]
@Pomax I suggest we back the bump and let it get bumped in my PR w. the needed changes.

**Comment by gvn** [comment]
This should be resolved now...

**Comment by alanmoo** [comment]
If we were adding a prefix to mofo-ui shouldn't that have made it a major version change?
