### ISSUE TITLE
Link to Branding guidelines in Mozilla Clubs application form

### ISSUE THREAD

**Issue by jvallera** [mozilla/learning.mozilla.org#2210]
Legal let me know that many club names are in violation of the brand guidelines. I’ve been reaching out one by one to notify them, but wondering if there is a better way we can guide them to choose a name for their club. This is not super urgent but something we should try to follow through on for quality reasons.

Suggestion:

In the application form they are asked to provide a name for their club. I am wondering if we can provide a link to the brand guidelines and short sentence underneath the club name field that says something like ‘Please follow our brand guidelines in choosing your club name. For example, a properly branded club in Madrid, Spain could be called Mozilla clubs Madrid.’

branding guidelines here: http://mozilla.github.io/learning-networks/clubs/branding-guidelines/

cc @hannahkane

**Comment by hannahkane** [comment]
Thanks for this ticket, @jvallera.

This solution seems simple enough,  but I'd love some design thinking on this problem. @xmatthewx - any thoughts on how to help people quickly understand the relevant branding guidelines?

**Comment by jvallera** [comment]
I am checking with Abigail for confirmation, but essentially this seems like the most important detail for people to know when they choose their club name:

Club Captains have the option to use "Mozilla" in the title of their club, however, if they choose to do so it must be followed by the word "Club". Otherwise, you may not use "Mozilla in the title of your club.

- Acceptable examples: Mozilla Club Rio, Mozilla Club Jahangirnagar University, Cikarang Mozilla Club, Mozilla Club for the Chicago Librarians.

- Non-acceptable examples: Mozilla Germany, Mozilla Rawanda, Mozilla Brussels Club

**Comment by hannahkane** [comment]
That seems like a good edit. Let us know if it's confirmed, and we can make that change to the guidelines.

**Comment by jvallera** [comment]
@hannahkane looks like Abigail approves but has some concerns noted below. Do you think there is any way find a happy medium? If not, I think we can proceed with what we have and we can use follow up email after they've been approved to be sure they've seen and read everything. 

"We never considered the "Mozilla Brussels Club"-type club name and it's not specifically prohibited under the guidelines, but I think it's a good idea to have everything be "Mozilla Clubs" plus.

So your overview looks accurate, but actually I'm a bit wary of including it because I'm afraid people may be less inclined to click through to the full guidelines thinking that this is more or less the extent of it (which it isn't). I can't recall what the application looks like, but maybe there's a way contextually to encourage users to read them? "

**Comment by hannahkane** [comment]
@jvallera - I thought your suggestion was for a change to the guidelines themselves. Were you suggesting we put that copy on the form itself?

**Comment by jvallera** [comment]
@hannahkane I was suggesting adding a link to the application (preferably under the field where they add their club name) form that directs applicants to the branding guidelines. We can easily edit the guide itself to have clearer directions about choosing a name and will do that asap. 

But, I understood your suggestion to be including one two lines of text along with the link to the branding guidelines on the application, that clarify how to properly name a club. So, yes including a small amount of copy on the form itself. Is that correct?

Aside from that, Abigail has additional thoughts and suggestions about how we can pull copy from the guidelines into the form itself so we know that people are reading the content and not skipping over it. I have doubts we can fit that in here, but am talking to her more this afternoon.

**Comment by xmatthewx** [comment]
Great to see that we have these guidelines. I didn't know! I will try and look closely to review. Is this text in a doc for comments? Regardless...

 - I agree that `Mozilla Clubs` should be locked together with a name in between
 - MoCo also asks initiatives (even internal) to not use `zilla`, `moz`, or `fox`, in the names of things. While were at it, they should use `foundation` either, though I'm not sure anyone would want that.

**Comment by hannahkane** [comment]
Thanks, @xmatthewx.

I wonder if we should re-title this ticket to be something along the lines of "Reduce # of Club names that violate branding guidelines."

Then the challenge is to figure out how to better convey the guidelines (it's unlikely people will take the time to read them carefully), or perhaps even how to add some validation to the field. @xmatthewx - do you have thoughts on the best user experience for reducing the number of names that violate the guidelines?

**Comment by xmatthewx** [comment]
A comic strip that shows how a club name confuses someone might help. But hard to translate.

Process might work better than documentation alone. We might have clubs submit a proposed name (get added to our map as incentive? chance to win t-shirts?). Then we can give specific feedback and point to guidelines with context.

**Comment by jvallera** [comment]
I am open to any solution that works the best, but prefer to most speedy option. Essentially we need to say something like this asap:

You have the option to use "Mozilla" in the title of your club, however, if you choose to do so it must be followed by the word "Club". Otherwise, you may not use "Mozilla" in the title of your club.

Acceptable examples using the name Mozilla: Mozilla Club Rio, Mozilla Club Jahangirnagar University, Cikarang Mozilla Club, Mozilla Club for the Chicago Librarians.
Non-acceptable examples using the name Mozilla: Mozilla Germany, Mozilla Rawanda, Mozilla Brussels Club

**Comment by xmatthewx** [comment]
What you've got is great. I would just add a summary at the top for tl;dr.

  - Put good example names in green. Bad ones in red. 

# Brand Guidelines

### Summary 

Choose a name for your club that will attract members and help them understand it. You may optionally choose a name that shows a relationship with Mozilla, but if you do, it must follow a specific format to avoid confusion. 

| Good 👍           | Not allowed 👎    |
| :------------- | :------------- |
| Mozilla Club Rio      | Mozilla Rio Club |
| The Brooklyn Webbies       | Mozilla Webbies |
| Space Kittens United | MozKitten Foxes |

You CAN [green] use the Mozilla name, but it must have this format: `Mozilla Club` `[location or interest]`
You CANNOT [red] use moz, fox, zilla, or fire in your club name. It can confuse people about the Mozilla or Firefox brands. 

### Details

(1) Club name. You...

**Comment by hannahkane** [comment]
How about this:
 * Update the [Guidelines ](http://mozilla.github.io/learning-networks/clubs/branding-guidelines/) as per @xmatthewx's suggestion in the comment directly above
 * Add helper text to "Name your Club" field: "Please follow our [brand guidelines](http://mozilla.github.io/learning-networks/clubs/branding-guidelines/) in choosing your club name."
 * Add placeholder text to the "Name Your Club" field: "e.g. Mozilla Club Rio or The Brooklyn Webbies."

Does that work, @jvallera?

**Comment by jvallera** [comment]
That sounds great to me. Editing brand guidelines now.

**Comment by jvallera** [comment]
Branding guidelines are updated with more clarity and written by Abigail in legal. I like suggestion from @xmatthewx and checking with Abigail to see if it can be added to the guide, but after recent edits it might be duplicate info. If she thinks having the summary at the top is ok, will add it to guide. If not, do we want to add it as helper text next to the "name your club" field @hannahkane ?

**Comment by hannahkane** [comment]
It's kind of a lot of info to add to the form. Let's see what Abigail thinks about adding it to the guidelines.
