### ISSUE TITLE
Strange duplicated quotes on the Club Captain testimonial carousel...

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2212]
Visible on https://learning.mozilla.org/en-US/clubs/start

![image](https://cloud.githubusercontent.com/assets/25212/18559440/181a48c8-7b2c-11e6-9613-878bd4dd1645.png)

Not sure how those got in there.

**Comment by Pomax** [comment]
I ran into this before, where it was caused by the Learning site LESS and mofo-ui LESS somehow not compiling correctly.
