### ISSUE TITLE
Sign up button looks janky

### ISSUE THREAD

**Issue by alanmoo** [mozilla/learning.mozilla.org#2216]
https://learning.mozilla.org/en-US/community The `Sign up` button near the bottom of the page...needs more padding and margin? It's probably missing a class or something.

**Comment by alsk23** [comment]
The class `.center-block` is removing the button's padding, hence the janky look.

**Comment by alanmoo** [comment]
@alsk23 that does indeed look like the problem! Would you like to submit a PR to remove it or shall I?

**Comment by alsk23** [comment]
I got started with `mozilla-central` yesterday. I'm just looking around, checking some issues. If you'd like, I'll go ahead and fix it, though it'll take a while getting used to the CSS of the project :)

**Comment by alanmoo** [comment]
You shouldn't need to touch CSS, just remove the `center-block` class from the element.
