### ISSUE TITLE
/clubs/list/ page should have tabs

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#2224]
Taís and I were just reviewing the Clubs page and noticed that the Clubs List view doesn't have the tab structure at the top, making it difficult for the user to get back to where they were.

@sabrinang - is there a reason NOT to include the tabs on this page?

**Comment by sabrinang** [comment]
I don't think there was a reason in particular just that we didn't have patterns to deal with this tier of information (similar to how for gigabit we we're unsure if we wanted to include a breadcrumb or not but ultimately decided just having the tabs there is enough for the user to go back) so having it to default "About Mozilla Clubs" tab present when clubs list in view and having it selectable to go back to the About page would work.
