### ISSUE TITLE
Build Gigabit content merge (/gigabit)

### ISSUE THREAD

**Issue by gvn** [mozilla/learning.mozilla.org#2228]
**Staged**: https://learning-mozilla-org-s-pr-2298.herokuapp.com/en-US/gigabit

Redpen: https://redpen.io/p/ku41f3c8ea603732e1
Related: https://github.com/mozilla/learning.mozilla.org/issues/2058
Sketch: https://drive.google.com/a/mozillafoundation.org/file/d/0B4Q8pzCpDS_eRmtDV1dmcTgxb1k/view

**Comment by hannahkane** [comment]
Flagging the Events page which @sabrinang just added to the redpen (thanks!) as a point of discussion for @gvn and @Pomax, as it relates to the conversation we had about whether to use services or not. In this case, it seems like there will be a small number of events, so this can be a static page for at least a while.

**Comment by gvn** [comment]
Blocked by: https://github.com/mozilla/learning.mozilla.org/issues/2297

**Comment by hannahkane** [comment]
@lindseyInCha @jenntbeard - Gigabit work is up on staging! https://learning-mozilla-org-s-pr-2298.herokuapp.com/en-US/gigabit

Please go through with a fine-toothed comb when you have time, and report issues here on this ticket.

**Comment by hannahkane** [comment]
@lindseyincha - what should the copy be at the top of the Events page?

**Comment by hannahkane** [comment]
Event titles are clickable, but don't go anywhere. They should either go to the associated url, or not be clickable.

**Comment by LindseyInCHA** [comment]
Wrong Link on "Start a Gigabit City" - should direct to https://docs.google.com/forms/d/e/1FAIpQLSdDAQL4KlvHaDHPxsYsx4bbVJ1v_5MROrQ3uD18_Z7ghAL9Iw/viewform not RFP information page.

**Comment by jenntbeard** [comment]
This is looking AMAZING!! I have gone through all the Open issues and addressed the items that I could. I also filed a couple of minor things as well. Let me know if you need anything else from us! (cc: @lindseyinCHA)

**Comment by hannahkane** [comment]
Yay! 
@gvn - when will we push this to production?

**Comment by gvn** [comment]
We can push today!

**Comment by jenntbeard** [comment]
So exciting! Also - I have one update for the Apply page - the dates of the pilot period have just changed to Jan 30-May 19 due to PTO in the finance dept. Should I file a separate bug for that?

**Comment by hannahkane** [comment]
Please do file a separate bug, @jenntbeard. Thanks!
