### ISSUE TITLE
October Community Call Landing page update 

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning.mozilla.org#2229]
The community call is scheduled for October 13 at 8am PT/ 11am ET/ 3pm UTC. We hope to begin promotions next week.

**Landing page copy:**

Upcoming Call box:
October 13 at 8am PT/ 11am ET/ 3pm UTC
Ada Lovelace Day & Women in STEM
Celebrate Ada Lovelace Day and women in STEM with Mozilla Learning, the Mozilla Science Lab and our guest speakers: Kirstie Whitaker, Postdoc at University of Cambridge, UK and Mozilla Science Lab 2016 Fellow; Zannah Marsh, Curriculum Strategist for Mozilla Science Lab; Srushtika Neelakantam, Mozilla Clubs Captain

Beneath the box:
The presence and participation of women in STEM (science, technology, engineering, mathematics) is on the rise thanks to the efforts of many across the globe, but there are still obstacles and barriers to overcome. This month, Mozilla Learning and the Mozilla Science Lab are joining forces to explore current opportunities and supports for women in STEM around the world.

**Video Workshop Stream:** We are testing AirMo this month (for both community call and curriculum workshop) so you should be able to embed the live stream. @hannahkane - I cc'd you on some emails about working with the AirMo team to make this happen. Let me know if I can do anything to help.

cc: @ldecoursy @auremoser

**Comment by auremoser** [comment]
Awesome, thanks @KGorr !

**Comment by hannahkane** [comment]
@KGorr - can you please drop the etherpad link here?

For now, how about if I include this in the Workshop Video Stream?
"The livestream will be embedded here on the day of the call. You can also participate with us on the etherpad below during the call."

**Comment by KGorr** [comment]
@hannahkane - whoops! https://public.etherpad-mozilla.org/p/sciencelab-calls-oct13-2016

That lingo sounds great.
