### ISSUE TITLE
Update Mozilla Curriculum Workshop landing page for October 

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning.mozilla.org#2239]
Grab header info, copy, and embeds from [this document](https://docs.google.com/document/d/1Sq45T7brtNTAyYLdKWbPj36oY-eD5SIAr9RPMGFHqPA/edit#) to update the MCW landing page after 9/29/16. Additional speaker information forthcoming.

@hannahkane @KGorr

**Comment by hannahkane** [comment]
Just confirming, @chadsansing - you'd prefer these changes don't happen until after 9/29?

**Comment by chadsansing** [comment]
Yes - our September episode airs that morning (ET), so it would be great for the update to happen afterwards.
