### ISSUE TITLE
Test & gather feedback on Teaching Activity page prototype.

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2240]
In #2114, I made some wireframes and gathered some feedback. Based on that work, I created a prototype that simulates the search and filtering features for the new Teaching Activities landing page..
- Here it is - https://flukeout.github.io/curriculum-db-ui-test/

**Next steps**
- Gather feedback from interested parties
  - Internal: Chad, Julia & An-me (emailed)
- Identify external audience and reach out
  - Asked for help from internal audience to identify some folks.

cc @hannahkane 

PS - It's been through a couple of rounds of internal review by the design team as well.

**Comment by flukeout** [comment]
Feedback from educator:

* If I am looking for a certain age range, will the "difficulty" filter represent that age level.  What is "beginniger, immediate, or advanced" might defer between a kid, teen, and adult.
* In the past, found Read, Write & Participate useful for sorting through content. Thinks it might be helpful here too.

**Comment by hannahkane** [comment]
Closing, since I don't think we're going to pick this up any time soon
