### ISSUE TITLE
Clubs forms QA: Can't click to move text cursor within Location field

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2247]
If I make a typo like this, it won't let me click into the word to fix it, have to move it with my arrow keys...

![image](https://cloud.githubusercontent.com/assets/25212/18886943/f5c9533e-84a6-11e6-94f8-30c59e558674.png)

**Comment by Pomax** [comment]
Unfortunately nothing we can do anything about short of finding a new react-select component.  ("problem in not-our-code")

**Comment by hannahkane** [comment]
Closing this given new work being done on Clubs module
