### ISSUE TITLE
Clubs forms QA: Misaligned error glow on radio buttons.

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2248]
Looks weird...

![image](https://cloud.githubusercontent.com/assets/25212/18886996/2e22faaa-84a7-11e6-9b69-480678d0cb51.png)

**Comment by Pomax** [comment]
I blame CSS, but if you know how to fix it, please do. The club form has its own LESS file and this is the `.error` class so should be easy to find.

**Comment by hannahkane** [comment]
Closing this given new work being done on Clubs module
