### ISSUE TITLE
Clubs forms QA: How did you hear about field strange behaviour

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2249]
If you choose Other for "How did you hear about..." and start typing, it tries to search for what you're typing for - it shouldn't.

![image](https://cloud.githubusercontent.com/assets/25212/18887073/88d3c79a-84a7-11e6-83d4-f632c7a44f2c.png)

**Comment by Pomax** [comment]
this looks like missing top-margin on the `other` fields. Should be easy to fix with a tweak to the club form LESS code

**Comment by Pomax** [comment]
I take that back, autocomplete is not a CSS issue, but we did add in "move focus to 'other' field" behaviour so this should now be solved, I would think. If you agree let's close this.

**Comment by flukeout** [comment]
Yeah, good to close, the focus jumps where it should which was the main issue and it seems like a lot of the other weird UX is baked into that react-select thingy and not worth the effort at this point.
