### ISSUE TITLE
Clubs forms QA: Remove "error" glow when I start editing a field.

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2250]
After a failed "submit" if I go to fix a field with an error, let's remove the red error border. It looks strange with both the blue & red together and once I'm in there editing it, chances are it's not really in error anymore...

![image](https://cloud.githubusercontent.com/assets/25212/18887122/b48b83c8-84a7-11e6-90f4-b9892b33b465.png)

**Comment by Pomax** [comment]
bloody `outline` property... we should turn that off in the club-form LESS

**Comment by hannahkane** [comment]
Closing this given new work being done on Clubs module
