### ISSUE TITLE
Clubs forms QA: Unclear which field is (optional)

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2252]
Looking at this... it's hard to tell what is "optional". Seems like both questions are being required when you try to submit.

![image](https://cloud.githubusercontent.com/assets/25212/18887251/347bf298-84a8-11e6-9a30-85309f425bde.png)

**Comment by Pomax** [comment]
that looks like the label associated with the hidden field when you pick `Yes` is still showing. That's a bug in the `<Form>` code.
