### ISSUE TITLE
Clubs forms QA: Type to search prompt missing after clearing dropdown field.

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2253]
For the location field, select a valid city. Then click the little "X". The field remains focused but without the "Type to search prompt" that should be there...

![image](https://cloud.githubusercontent.com/assets/25212/18887379/b193b842-84a8-11e6-8de3-441a1653b01e.png)

**Comment by Pomax** [comment]
This is not our code, but a react component we're using off of npm - if you can turn this into a precide bug description, we can file it on their repo.

**Comment by hannahkane** [comment]
Closing this given new work being done on Clubs module
