### ISSUE TITLE
Clubs forms QA: Dropdown arrow on Location field doesn't do anything useful.

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2254]
Shows a clickable arrow, but only option is type to search. Can we remove the arrow until there are some useful choices? Like after typing in a valid city and clicking on the wrong one.

![image](https://cloud.githubusercontent.com/assets/25212/18887447/024527a8-84a9-11e6-98f5-e61badcb035b.png)

**Comment by Pomax** [comment]
This is not our code, but a react component we're using off of npm - if you can turn this into a precide bug description, we can file it on their repo.

**Comment by hannahkane** [comment]
Closing this given new work being done on Clubs module
