### ISSUE TITLE
Clubs forms QA: Very confusing UX on "other" option.

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2256]
It's very unclear that you're supposed to type in the field BELOW the original input box...

![image](https://cloud.githubusercontent.com/assets/25212/18887713/1f4775b2-84aa-11e6-9400-6ea4a02c316c.png)

If you select other, it should focus that field. Currently the initial input is focused, making it seem like you're supposed to type there.

**Comment by Pomax** [comment]
also some missing styling to put some white space between the two fields, but automatically moving focus is a good idea. This can be written into the `<Form>` component.
