### ISSUE TITLE
Clubs forms QA: Why field says minimum 50 words, form error says minimum 45 words.

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2257]
![image](https://cloud.githubusercontent.com/assets/25212/18887789/7b9a3b92-84aa-11e6-8c50-a3914ca47a4b.png)

![image](https://cloud.githubusercontent.com/assets/25212/18887793/82cc8a8c-84aa-11e6-956a-244c53f4f994.png)

**Comment by Pomax** [comment]
The validator uses `45` as cap, so the field's placeholder needs a string update to reflect that.
