### ISSUE TITLE
Clubs forms QA: Regional Coordinator name is optional, except it's not.

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2258]
Near the field, seems like it's optional.

![image](https://cloud.githubusercontent.com/assets/25212/18887882/ef0fa54e-84aa-11e6-9441-55c7dbdbed00.png)

Form thinks it's mandatory

![image](https://cloud.githubusercontent.com/assets/25212/18887893/076e1710-84ab-11e6-92a3-4588a2f6bca3.png)

**Comment by Pomax** [comment]
hm, this looks like a bug related to how the `<Form>` element treats unmetered fields. It might need an explicit `optional` value for field definitions rather than assuming that `metered===false` is the same as `optional`
