### ISSUE TITLE
Clubs forms QA: Inconsistent form field heights

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2259]
Let's make them all have the same height / padding? Looks a bit janky...

![image](https://cloud.githubusercontent.com/assets/25212/18887992/6bf7fff2-84ab-11e6-9bf2-dd10aef30eba.png)

**Comment by Pomax** [comment]
I don't quite know what you're seeing that looks wrong, can you add some details about what you're seeing that you think needs changing? (what should I be noticing in this screenshot?)

**Comment by flukeout** [comment]
The location field height is shorter than the other two fields. It's just a small styling tweak that would make things look more consistent.

**Comment by Pomax** [comment]
that should be easy to fix in the club-form LESS code

**Comment by hannahkane** [comment]
Closing this given new work being done on Clubs module
