### ISSUE TITLE
Clubs forms QA: After clicking Next on the first step, Submit button has a blue border.

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2260]
On the next step, the submit button is focused and has a blue border.
Seems strange, is this intended?

![image](https://cloud.githubusercontent.com/assets/25212/18888021/7fd3a40e-84ab-11e6-9f54-070234eff39a.png)

**Comment by Pomax** [comment]
that is absolutely not intended. I suspect it's CSS outline not being set to 0
