### ISSUE TITLE
Clubs forms QA: Clicking the Radio button labels don't select the associated option.

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2261]
Clicking these labels should select the radio buttons next to them...

![image](https://cloud.githubusercontent.com/assets/25212/18888068/a8122f44-84ab-11e6-9047-83d9c0f24fe8.png)

...but it don't.

**Comment by Pomax** [comment]
General issue with the `<Form>` component, labels do not wrap their associated input elements.
