### ISSUE TITLE
Clubs forms QA: Provide default selected option step 2?

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2262]
Seems like one of these (the first?) would probably be more likely, can we provide a default here? Or leaving intentionally unselected to get the applicant to think?

![image](https://cloud.githubusercontent.com/assets/25212/18888141/f0a9bb3c-84ab-11e6-9c2f-32fba47e186f.png)

**Comment by Pomax** [comment]
The latter. In addition to also being a control that generates a completely different form depending on the choice picked.
