### ISSUE TITLE
Clubs forms QA: Existing club information is shown even after "Start a New Club" is selected.

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2263]
On step 2, if I choose the "existing club" option additional form fields are revealed. If I then choose the "new" option, they're still visible. Should hide 'em.

![image](https://cloud.githubusercontent.com/assets/25212/18888250/5830f388-84ac-11e6-84c5-d848a5d913f7.png)

**Comment by flukeout** [comment]
Actually, looks like those fields are shown no matter which option I click.

**Comment by Pomax** [comment]
the two options should have virtually identical forms, but with different labels. If the labels don't change, that's definitely a bug.

**Comment by flukeout** [comment]
Okay, so then the labels feel wrong. If you're starting a new club, how would you know any of this stuff..

<img width="515" alt="image" src="https://cloud.githubusercontent.com/assets/25212/18888978/9cda8924-84af-11e6-8d71-0ca3ad4e1fbf.png">

**Comment by Pomax** [comment]
yeah they absolutely are. When you pick "Start" the labels should reflect that this is a new club. PR already up that'll fix this.
