### ISSUE TITLE
Clubs forms QA: "Full, valid URL" instructions aren't helpful enough.

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2265]
![image](https://cloud.githubusercontent.com/assets/25212/18888444/319496de-84ad-11e6-8f57-39c34ee9eae0.png)

If we want to force people to add `http:` or `https:` we should provide a hint our error message.

**Comment by Pomax** [comment]
We have no idea how people mess up URLs - we don't parse them, we only validate them. If you can think of good copy that effectively tells people to literally copy the URL from their browser, let's use that text.

**Comment by hannahkane** [comment]
Closing this given new work being done on Clubs module
