### ISSUE TITLE
Clubs forms QA: No "Success" message after submitting.

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2266]
After filling out the form I see this...

![image](https://cloud.githubusercontent.com/assets/25212/18888624/f675dee0-84ad-11e6-8569-580a0945f66d.png)

It still says "tell us more about you" making it seem like I'm still in the process. Can we add a "Thanks / Success" type of message with a clear call to action?

**Comment by Pomax** [comment]
looks like something we should improve the design on /cc @hannahkane
