### ISSUE TITLE
Clubs forms QA: Reloading form while signed in flashes the Sign in / Sign up UI.

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2267]
Looks weird, can we hide this until we know what state a person is in instead of showing it as a default?

![reload](https://cloud.githubusercontent.com/assets/25212/18888688/3e015c6c-84ae-11e6-8903-7821809ea697.gif)

**Comment by Pomax** [comment]
Thanks to how the teach-api works in conjunction with the login element, there is no easy way to fix that. Worth looking at when we have time later, though

**Comment by Pomax** [comment]
Having said that, the Teach-API might be able to fire pre-mount so that we know the login status before the component renders...

**Comment by hannahkane** [comment]
Closing this given new work being done on Clubs module
