### ISSUE TITLE
Add question to beginning of CC application to redirect Campus Clubs

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#2275]
The Participation team has recently launched a platform for [Mozilla Campus Clubs](https://campus.mozilla.community/), a program similar to Mozilla Clubs, but with a specific focus on college and university campuses. We will now begin referring people who are interested in starting a Mozilla Club on their college/university campus to this program.

Design (worked out in #2231) solution is to add a Yes/No question at the very beginning of the application form. Users who _are_ on a college or university campus, will be redirected to the Campus Clubs site:

<img width="794" alt="screenshot 2016-09-27 16 46 15" src="https://cloud.githubusercontent.com/assets/53411/18891141/f5ec2ce4-84d1-11e6-8b8d-b18ebdd5c80c.png">

Users who _are not_ on a campus, will see the rest of the form:

<img width="782" alt="screenshot 2016-09-27 16 46 22" src="https://cloud.githubusercontent.com/assets/53411/18891166/0b16b468-84d2-11e6-9317-5513313f96c2.png">

**Comment by jvallera** [comment]
Hi @hannahkane just checking back on this. Would be great to have in place soon.

**Comment by hannahkane** [comment]
@Pomax - I'm a bit out of the loop, so I don't know all that's on your plate this heartbeat. Advancing the shared services work and any urgent badges issues would be higher priority than this task. Given that, do you think you'll have bandwidth to do this item?

**Comment by gvn** [comment]
If not I can look at it

**Comment by hannahkane** [comment]
Thanks, @gvn. That would be great.

**Comment by gvn** [comment]
@jvallera @hannahkane This is now on [staging](https://learning.mofostaging.net/en-US/). If it looks good I can push to prod. Just let me know!

**Comment by jvallera** [comment]
Thanks @gvn i can't seem to login to the staging site to view the application. Does my current teach-api login work? or do I need to make a new account for staging?

**Comment by gvn** [comment]
Hmm. I'm using the same login. I did have some issues with PrivacyBadger blocking cookies. Are you using it by any chance?

**Comment by jvallera** [comment]
no, I don't think so. Not sure what Privacy Badger is.
I just made a new account through staging using the same info from the teach api  and that worked...

it looks great to me!

**Comment by gvn** [comment]
Ok, this is live!

**Comment by jvallera** [comment]
Great thanks!

**Comment by hannahkane** [comment]
Looks great. Thanks!
