### ISSUE TITLE
Add new "denial reason" field to Clubs application

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning.mozilla.org#2276]
Now that Clubs is split between Mozilla Clubs and Campus Clubs - we are finding that many people are applying to Moz Clubs but should be redirected to Campus Clubs. In this instance, we are denying their application and sending them a link to apply for Campus Clubs. To keep track of how many and who, it would be awesome to have "Campus Club" as a denial reason option. (We'd also like an automated email to be linked to this denial reason)

For now we are going to keep track manually, so this can be marked as low priority.

cc @jvallera @hannahkane

**Comment by hannahkane** [comment]
Closing this given new work being done on Clubs module
