### ISSUE TITLE
Consider different, non-map based solution for displaying Clubs

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#2277]
The Clubs Map has caused several problems.

From @KGorr: "Regarding the lat/longitude - over the span of this year I've had to go in and manually update about 15-20 club coordinates because they didn't populate correctly. Or because it looks like there are 5 clubs all at the same location when they are actually spread out around the city (usually RCs send these types of requests)."

The purpose of the map is to:
- Show the broad reach of Clubs
- Help people find a Club near them

Let's consider other ways we can achieve these goals, without necessarily relying on a dynamic map.

Would love some design input from @xmatthewx, but I'm wondering if we ought to move toward something like the regional groupings we have for the [Science Study Groups](https://science.mozilla.org/programs/studygroups).

**Comment by xmatthewx** [comment]
+1 to a simpler list with regional groupings like science. Placemarkers on a static map would need much less precision. And we could remove placemarkers and just put a total count on top of each region.

We could put analytics events on a list. Not sure we can do that for the map. It's hard to know if people use it, if they get stuck, if something breaks.

**Comment by hannahkane** [comment]
Closing this given new work being done on Clubs module
