### ISSUE TITLE
Add Web Literacy for Library Staff workshop to /activities

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning.mozilla.org#2279]
Page content here: https://docs.google.com/document/d/1kSxbSAXDb5pdXo_3x_Ag5Od5ziARtly4FL4Qw1Cckgk/edit#heading=h.nir6usoqepnq

@hannahkane, @anmechung

**Comment by hannahkane** [comment]
Sorry, Chad, didn't realize you'd filed this. Closing because I started a PR against https://github.com/mozilla/learning.mozilla.org/issues/2284
