### ISSUE TITLE
Clubs forms QA: First page of form is too short for the last dropdown.

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2281]
When I open the last dropdown, it's immediately obscured because it falls below the bottom edge of the page.

![2016-09-29 13 20 24](https://cloud.githubusercontent.com/assets/25212/18970804/a978d174-8647-11e6-84a7-95d0c08537ce.gif)

I'd recommend adding a bunch of padding under the form so that the page is longer, this is less likely to happen then.

**Comment by Pomax** [comment]
We can add some padding, but we can also see if we can scroll down the page a bit, because while the menu is open, the page *is* appropriately sized.

**Comment by flukeout** [comment]
I think adding padding would be way simpler, a scroll might be unexpected and jarring.

**Comment by Pomax** [comment]
Just thinking in terms of sensible generic forms, padding will work for our specific page so we can absolutely put that in, but an autoscroll might work better for when we move the form to mofo-ui, *or* if the dropdown allows opening such that it respects page dimensions that would be useful too.

**Comment by hannahkane** [comment]
@kristinashu and @Pomax and @alanmoo - we have a bunch of tickets in this repo with ["Clubs forms QA"](https://github.com/mozilla/learning.mozilla.org/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20%22Clubs%20forms%20QA%22) in the title. I'm wondering if I can close them all, given the work you all are doing with CoSS?

**Comment by Pomax** [comment]
I do not know how much the work with CoSS is intended to yield immediate replacements on our existing web properties, @kristinashu might have a better view on this but if any of the QA issues need to be addressed short term, I very much doubt CoSS work will cover that and we should probably schedule some time to wrap up those issues independent of the CoSS work.

**Comment by kristinashu** [comment]
We will eventually rebuild this form but I'm guessing it won't happen for a while (say 6 months, but don't quote me on that!). So probably not worth doing the nice-to-have QA tickets but maybe do the important ones?

**Comment by hannahkane** [comment]
Closing this given new work being done on Clubs module
