### ISSUE TITLE
Clubs forms QA: Missing "?" after "Where will you meet" label.

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2282]
This label reads like a question and other questions have a question mark after them. Let's add it here - OR - change the label to be a non-question like "Meeting Location" or something.

![image](https://cloud.githubusercontent.com/assets/25212/18972001/3529d4ee-864c-11e6-8c83-8e967f01037a.png)

**Comment by Pomax** [comment]
I'm leaning towards "questions should have question marks".

**Comment by Pomax** [comment]
closed thanks to @RPraneetha
