### ISSUE TITLE
Question - JSON structure for search and filter options.

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2292]
Hey @gideonthomas I'm working on the search and filter UI for the Teaching Activities page...\

![image](https://cloud.githubusercontent.com/assets/25212/19122769/cf448d7e-8ae0-11e6-8e98-e84c3a0730e9.png)

...and I'm loading in all of the options from some JSON, which I pasted below. Is it reasonable to expect that we can get this JSON from the server when we load the component based on our data structures?

Also, do you see any issues with the way it is structured? Should the filter options have simple lowercase names (or maybe numbers) as keys? 

```
var filterOptions = [
  {
    name: "duration",
    label : "Duration",
    options : {
      0 : "Any duration",
      1 : "About 15 minutes",
      2 : "15 minutes to 1 hour",
      3 : "1 to 2 hours",
      4 : "2 to 4 hours",
      5 : "4 hours +"
    },
    type : "slider"
  },
  {
    name : "difficulty",
    label : "Difficulty",
    optionGroups : [
      {
        label : false,
        options : ["Beginner", "Intermediate", "Advanced"]
      }
    ],
    type : "pills"
  },
  {
    name: "age-range",
    label : "Age Range",
    optionGroups : [
      {
        label: false,
        options: ["Kids", "Teens", "Adults"]
      }
    ],
    type : "pills"
  },
  {
    name: "web-lit-skills",
    label : "Web Literacy Skills",
    optionGroups: [
      {
        label : false,
        options: ["Design", "Code", "Compose", "Revise", "Remix", "Evaluate", "Sythesize", "Navigate", "Search", "Connect", "Protect", "Open", "Practice", "Contribute", "Share"]
      },
      {
        label : "21st Century Skills",
        options: ["Problem Solving", "Communication", "Creativity", "Collaboration"]
      }],
    type : "pills"
  }
]
```

**Comment by gideonthomas** [comment]
Hmm I think most of this is fine, but can I suggest some changes (to make some of the work on the back-end and admin interface easier)? Take a look at the following and let me know what you think:
```json
[{
   "name": "duration",
   "label": "Duration",
   "options": [ "Any duration", "About 15 minutes", "15 minutes to 1 hour", ... ],
   "interface_type": "slider"
}, {
   "name": "difficulty",
   "label": "Difficulty",
   "options": [ "Beginner", "Intermediate", "Advanced" ],
   "interface_type": "pills"
}, {
   "name": "age_range",
   "label": "Age Range",
   "options": [ "Kids", "Teens", "Adults" ],
   "interface_type": "pills"
}, {
   "name": "weblit_skills",
   "label": "Web Lit Skills",
   "options": [ "Design", "Code", "Compose", "Revise", ... ],
   "more_options": [{
      "name": "skills",
      "label": "21st Century Skills",
      "options": [ "Problem Solving", "Communication", "Creativity", ... ]
   }],
   "interface_type": "pills"
}]
```

Things to note:
- `options` has been flattened into an array
- The `name`s of the filters are changed to represent what is currently on the backend
- `optionGroups` has been replaced by `more_options` that is an array of multiple filter option objects (without the type). This is preferable since it's easier to set up the link between web lit skills and 21st century skills that way
- I'm a bit hesitant about including `type` (renamed to `interface_type`) in this data since we might need to maintain a preview of it in the back-end if we decide to use the admin interface to add more filters.

**Comment by flukeout** [comment]
Overall this looks great to me! My only suggestion would be that we find a way to show/hide the label as needed within the expanded menu per option-group. The structure above doesn't really let us do that, but we can just hide it by default except for anything in ``more-options`` which would do the trick.

I'll update my sample data structure to match this and update the components.

**Comment by flukeout** [comment]
We might want to add an optional ``default_option`` as well. This will help with the duration slider which starts out at "Any Duration".

**Comment by flukeout** [comment]
Okay @gideonthomas here's what I've done...

```
var filterOptions = [
  {
    name: "duration",
    toggleLabel : "Duration",
    optionLabel : "Time to complete",
    options : [
      "Any duration",
      "About 15 minutes",
      "15 minutes to 1 hour",
      "1 to 2 hours",
      "2 to 4 hours",
      "4 hours +"],
    default_option: "Any duration",
    interface_type : "slider"
  },
  {
    name : "difficulty",
    toggleLabel : "Difficulty",
    options : ["Beginner", "Intermediate", "Advanced"],
    interface_type : "pills"
  },
  {
    name: "age-range",
    toggleLabel : "Age Range",
    options: ["Kids", "Teens", "Adults"],
    interface_type : "pills"
  },
  {
    name: "web-lit-skills",
    toggleLabel : "Web Literacy Skills",
    options: ["Design", "Code", "Compose", "Revise", "Remix", "Evaluate", "Sythesize", "Navigate", "Search", "Connect", "Protect", "Open", "Practice", "Contribute", "Share"],
    more_options: [
      {
        name : "century-skills",
        optionLabel : "21st Century Skills",
        options: ["Problem Solving", "Communication", "Creativity", "Collaboration"]
      }],
    interface_type : "pills"
  }
]
```

* Kept the ``more_options`` structure
* Introduced a ``toggle_label`` and a ``option_label``
  * ``toggle_label`` - this goes in the pill that expands the filter
  * ``option_label`` - is optional and may appear in front of pill options when a filter is expanded
  * Now we can be explicit about each of them, and omit the ``option_label`` if we don't want it

**Comment by flukeout** [comment]
Closing - we can make changes in #2283

**Comment by gideonthomas** [comment]
Yep this structure looks good!
