### ISSUE TITLE
Adding Sticker Order Link to the Maker Party Website

### ISSUE THREAD

**Issue by LucyeoH** [mozilla/learning.mozilla.org#2293]
Detailed description of work:
@kelimuttu @couci have created a process for ordering stickers for Maker Party. https://github.com/mozilla/reps-regional/issues/64

The link is ready to go [here](https://docs.google.com/spreadsheets/d/1Fgyx7aozINB0gVx-0ckFcVG6qfsmKz4B-QF9qmhNw3g/edit#gid=0) and they would like it to appear on the website as well as in the host pack. 

Can we add it under "Logos & Assets" - https://learning.mozilla.org/en-US/events/resources

_Start date: Oct 5, 2016_ 
_Due date: Oct 8, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @hannahkane @ScottDowne

**Comment by hannahkane** [comment]
Closing since MP has passed
