### ISSUE TITLE
Gigabit QA: Missing icons for Gigabit tabs

### ISSUE THREAD

**Issue by gvn** [mozilla/learning.mozilla.org#2297]
I need SVG icons for the Gigabit tabs when they're in the "mobile" view:

<img width="398" alt="screen shot 2016-10-06 at 10 59 20 am" src="https://cloud.githubusercontent.com/assets/206379/19164288/313d1a90-8bb4-11e6-88f8-1a1de7c1ad7d.png">

Here's an example of them for the Clubs section:

<img width="201" alt="screen shot 2016-10-06 at 10 59 36 am" src="https://cloud.githubusercontent.com/assets/206379/19164302/3d3ddda2-8bb4-11e6-9265-c84402249b1f.png">

@sabrinang Can you provide me with them? Thx!

PS: Note that we added an "Events" tab:

<img width="719" alt="screen shot 2016-10-06 at 10 59 09 am" src="https://cloud.githubusercontent.com/assets/206379/19164345/6e2eba30-8bb4-11e6-9887-c52a1fcab16e.png">

#2228

**Comment by gvn** [comment]
Sounds like @taisdesouzalessa has some time to make icons.

**Comment by hannahkane** [comment]
@sabrinang - can you please confirm that we'll need icons for Portfolio, Apply, and Events, but we can use the About icon from the Clubs page?

@taisdesouzalessa - are you ok to work on this? Do you need anything to get started?

**Comment by sabrinang** [comment]
Yes, I think we should use the same About icon that is seen on the clubs page for visual consistency on how we represent About. 

I don't have the original files for the icons but I believe Luke made the about icon and the others club mobile icons were taken from the science site if that helps.

**Comment by taisdesouzalessa** [comment]
@hannahkane I am ok to work on this. +1 on keeping the "About" icon consistent through pages.
Could you let me know the deadline of this project?

**Comment by hannahkane** [comment]
I think it would be fantastic if we could release the Gigabit pages before Mozfest. @gvn - given that timeline, when would you need the icons by?

**Comment by gvn** [comment]
Could we shoot for EOD tomorrow?

**Comment by taisdesouzalessa** [comment]
@gvn - by EOD you mean I have the full day tomorrow, right? If so I can probably have the final deliverables by then.

**Comment by gvn** [comment]
Yep, thanks!

**Comment by taisdesouzalessa** [comment]
Hey @gvn I finished those earlier than I expected...yay!
Here are the svgs - I am sending them with strokes and also with expanded strokes (I was not sure about your preference on it). I cleaned up the svgs' code as well.
[svgs.zip](https://github.com/mozilla/learning.mozilla.org/files/530009/svgs.zip)

Here they are placed on the mockup:
![mockup-placed-icons](https://cloud.githubusercontent.com/assets/22157921/19395759/1baad212-91f4-11e6-91e7-f98c014f3a77.jpg)

I was wondering if the "apply" icon could be optically aligned to the center...if you align the whole icon to the center, it looks a bit unbalanced. Is there any way you can add relative margins (or something like that) so the sheet of paper is the element center aligned? Here is a better explanation:
![icons-aligment](https://cloud.githubusercontent.com/assets/22157921/19395802/67931dd8-91f4-11e6-91ef-ad4454450f9a.jpg)

Let me know if you have any questions. The "About" is the same as the Mozilla Clubs one. Please let me know if you want me to send it as well.

**Comment by gvn** [comment]
Fixed on staging

**Comment by hannahkane** [comment]
Confirmed! @taisdesouzalessa - do you want to do final approval? If this looks good to you [here](https://learning-mozilla-org-s-pr-2298.herokuapp.com/en-US/gigabit/about), please close this ticket.

**Comment by taisdesouzalessa** [comment]
It looks good to me! Closing the ticket then.
