### ISSUE TITLE
Gigabit QA: broken link in portfolio detail page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#2300]
Clicking on "Adagio" link from https://learning-mozilla-org-s-pr-2298.herokuapp.com/en-US/gigabit/portfolio/adiago leads to a 404. Checked several other portfolio detail pages, and the links work fine.

**Comment by hannahkane** [comment]
#2228

**Comment by gvn** [comment]
Fixed!

**Comment by hannahkane** [comment]
Verified
