### ISSUE TITLE
Gigabit QA: copy for Events page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#2301]
@lindseyincha - what should the copy be at the top of the Events page?

**Comment by hannahkane** [comment]
#2228

**Comment by jenntbeard** [comment]
"We offer global and local opportunities that facilitate group and in-person collaboration. Join us!"

**Comment by gvn** [comment]
Fixed

**Comment by hannahkane** [comment]
Verified
