### ISSUE TITLE
Gigabit QA: what should "Start a Gigabit City" link to

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#2303]
@linsdseyincha - just want to confirm, what should the "Start a Gigabit City" button on the About page link to?

**Comment by hannahkane** [comment]
#2228

**Comment by gvn** [comment]
Wrong Link on "Start a Gigabit City" - should direct to https://docs.google.com/forms/d/e/1FAIpQLSdDAQL4KlvHaDHPxsYsx4bbVJ1v_5MROrQ3uD18_Z7ghAL9Iw/viewform not RFP information page.

**Comment by gvn** [comment]
Fixed

**Comment by hannahkane** [comment]
verified
