### ISSUE TITLE
Gigabit QA: Should national partner logos link to websites? (not a blocker)

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#2304]
@lindseyincha - should NSF and USIgnite logos link to their respective websites? If so, what are the urls?

**Comment by hannahkane** [comment]
#2228

**Comment by LindseyInCHA** [comment]
Yes:

US Ignite: https://www.us-ignite.org/
NSF: https://www.nsf.gov/

**Comment by gvn** [comment]
Fixed!

**Comment by hannahkane** [comment]
Verified
