### ISSUE TITLE
Gigabit QA: location search bug

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#2305]
Looks like there are 12 portfolio projects in Kansas City. However, searching for "KC" only produces 1 result (perhaps to be expected, but it would be nice to have KC serve as a synonym for "kansas city"), "Kansas" only produces 4, and "Kansas City" produces 3.

**Comment by hannahkane** [comment]
#2228

**Comment by gvn** [comment]
FIxed!

**Comment by hannahkane** [comment]
Searching for "KC" works now, but "kansas" and "Kansas City" still produce fewer results than expected.

**Comment by gvn** [comment]
I'm going to need to set up a hash table to correlate the short codes to their long forms. However, I'm not sure what the convention being used is. I thought maybe airport codes, but KC isn't one.

In the data we have:
`CHA`, `KC`, and `Flint`.

Not sure what short code to use for Flint.

Also, are there just no projects currently in Austin?

**Comment by gvn** [comment]
We could also only use longforms for the cities, which might make more sense anyway.

**Comment by gvn** [comment]
@lindseyincha What is the preferred short code for Flint? Thanks!

**Comment by gvn** [comment]
Going to use longform city names in the orange tags as well.

**Comment by LindseyInCHA** [comment]
Hmmm...I believe it is FNT.  Thanks!

**Comment by gvn** [comment]
Fixed on staging

**Comment by hannahkane** [comment]
Verified
