### ISSUE TITLE
Gigabit QA: "Continue reading" broken

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#2308]
The "Continue reading" links at the bottom of the About page (corresponding to blog, portfolio, and event teasers) don't work. I would expect them to go to the specific blog post, event url, or portfolio detail page.

#2228

**Comment by gvn** [comment]
Do you have a URL for the blog post and the event?

**Comment by hannahkane** [comment]
@lindseyincha - are these the right blog post/portfolio/event to be featuring? If so, can you provide the right links? Thanks!

**Comment by LindseyInCHA** [comment]
@jenntbeard back in the country and back in charge!

**Comment by jenntbeard** [comment]
The most recent items to feature would be as follows:

Blog: Mozilla brings the IoT to Chattanooga, TN in a 48 Hour Launch [link: https://blog.mozilla.org/gigabit/mozilla-brings-the-iot-to-chattanooga-tn-in-a-48-hour-launch/]
Events: Mozilla Festival 2016 [link: https://mozillafestival.org/]
Projects: Raspberry Python Music Genie [link: https://learning-mozilla-org-s-pr-2298.herokuapp.com/en-US/gigabit/portfolio/raspberry-python-music-genie]

**Comment by gvn** [comment]
Fixed on staging

**Comment by hannahkane** [comment]
Verified
