### ISSUE TITLE
Gigabit QA: not sure where to link blog to

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#2309]
There's an [outstanding devops task](https://github.com/MozillaFoundation/mofo-devops/issues/300) to migrate Gigabit blog content to blog.webmaker.org (and another to change the url). 

Since that is still pending, I'm wondering what we should do in the meantime. @lindseyincha - should we link to https://blog.mozilla.org/gigabit/?

#2228

**Comment by LindseyInCHA** [comment]
Makes sense to me, @hannahkane

**Comment by jenntbeard** [comment]
Yes, this is the only blog that is still getting new content.

**Comment by gvn** [comment]
I believe this is resolved via #2308
