### ISSUE TITLE
Bug on Credentials - giant badge!

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#2312]
This is what happens when I click on "Credentials" in the main sidebar nav from one of the badge detail pages:

![screen shot 2016-10-06 at 9 13 15 pm](https://cloud.githubusercontent.com/assets/8389648/19178670/d4552074-8c09-11e6-99fe-f3f6abb6be14.png)

STR:
 * Go to https://learning.mofostaging.net/en-US/badges
 * Click on a badge to view the detail page
 * Click on "Credentials" in the main navigation

I had expected to land back on the Credentials landing page.

**Comment by gideonthomas** [comment]
This is a side-effect of https://github.com/mozilla/learning.mozilla.org/issues/2313. That issue throws an error which trickles down into react and breaks everything else (based on https://github.com/facebook/react/issues/4026). Fixing #2313 will fix this!
