### ISSUE TITLE
Gigabit QA: Social CTA icons are not clickable, but should be.

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2316]
On the the bottom of the about page, there are three social calls to action. The icon for each should be clickable, but isn't..

![image](https://cloud.githubusercontent.com/assets/25212/19203311/671c48ac-8c8b-11e6-9716-83041f283624.png)

For reference, the icons at the bottom of https://learning.mozilla.org/en-US/opportunities are clickable.

#2228

**Comment by gvn** [comment]
Fixed on staging

**Comment by flukeout** [comment]
Verified (tm)
