### ISSUE TITLE
Gigabit QA: Lead Org links on Portfolio page don't link to anything.

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2317]
Clicking the Lead Org: Adagio link just takes me to the top of the page.

![image](https://cloud.githubusercontent.com/assets/25212/19203398/dbbc2ff6-8c8b-11e6-85e7-c169f694d6b8.png)

#2228

**Comment by gvn** [comment]
Fixed on staging!

**Comment by gvn** [comment]
Note: some don't have links, so I left them unlinkified.

**Comment by flukeout** [comment]
Looks good! Found a broken one but filed separately.
