### ISSUE TITLE
Gigabit QA: Handle large / wide logos more gracefully on Portfolio Detail page.

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2318]
Case in point, check out the sizing and placement of the logo on the 3d Multi-School Learning page...

![image](https://cloud.githubusercontent.com/assets/25212/19203508/893acd4a-8c8c-11e6-8ddc-cbb396c775a4.png)

#2228

**Comment by gvn** [comment]
Since this is, I think, the only one with an issue we should just add padding to the image itself.

Otherwise we'll have to letterbox a lot of other images that look better as-is.

**Comment by gvn** [comment]
It'll also look better in the overview `/portfolio` if we do that.

**Comment by gvn** [comment]
Fixed on staging

**Comment by hannahkane** [comment]
aSteam Village logo looks good
