### ISSUE TITLE
Gigabit QA: Hide "Partner Org" heading if there are no partners on Portfolio Detail page

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2319]
For projects without partners, like the Minecraft Oculus Rift project, let's hide the heading.

![image](https://cloud.githubusercontent.com/assets/25212/19203566/ca2b28c2-8c8c-11e6-9676-c20d6a3ebb2d.png)

#2228

**Comment by gvn** [comment]
Fixed!

**Comment by flukeout** [comment]
Bonus points add "s" when there are multiple orgs. But, show/hide is fixed.
