### ISSUE TITLE
Gigabit QA: Add "no results" copy when searching and nothing matches.

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2321]
Just a little centered paragraph under the search field woudl be nice even.

![image](https://cloud.githubusercontent.com/assets/25212/19203932/e1a415e8-8c8e-11e6-9d95-568413efcf51.png)

#2228

**Comment by gvn** [comment]
Added!

**Comment by flukeout** [comment]
Indeed!
