### ISSUE TITLE
Gigabit QA: Typo on "Spartan Systems"

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2322]
Displayed as Spartin in the lead org link on the Portfolio page

![image](https://cloud.githubusercontent.com/assets/25212/19207167/3bd28608-8ca3-11e6-81b1-2cc18ec83c83.png)

#2228

**Comment by gvn** [comment]
Fixed!

**Comment by hannahkane** [comment]
Verified
