### ISSUE TITLE
Club form: Failed to update club

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/learning.mozilla.org#2324]
Looks like the user can't pass validation while updating their club info. The validation seems to fail on a field that they did not update. 

https://forum.learning.mozilla.org/t/can-not-update-my-club-info/1181

**Comment by Pomax** [comment]
hm, interestingly this is in old code (we have not updated the edit modal yet) - this will probably require a bit of code hunting and django log checking.

**Comment by hannahkane** [comment]
cc @KGorr
