### ISSUE TITLE
Gigabit QA: Incorrect # and text on Homepage

### ISSUE THREAD

**Issue by jenntbeard** [mozilla/learning.mozilla.org#2329]
#2228 

(Under the Expanding the Gigabit Community Fund section)
Copy should read 'two' not 'three' (in regards to the number of new cities) and the rest of the text was changed from the RedPen version.

Full copy should be: In partnership with the National Science Foundation and US Ignite, we're expanding the Gigabit Community Fund to two additional gigabit cities by 2018. Click below to submit your city.

**Comment by gvn** [comment]
Fixed on staging

**Comment by hannahkane** [comment]
Verified
