### ISSUE TITLE
Gigabit QA: Fix Facebook Link

### ISSUE THREAD

**Issue by jenntbeard** [mozilla/learning.mozilla.org#2330]
#2228 

On the homepage, can we change the link showing for CHA's Facebook page to just @HiveCHA that links to: https://facebook.com/HiveCHA? If that seems out of convention (with the Twitter handle right above it) maybe just use 'facebook.com/HiveCHA' instead.

**Comment by gvn** [comment]
The `@` convention is essentially a Twitter thing.

I'd recommend we either go with just `HiveCHA` or `facebook.com/HiveCHA`.

**Comment by jenntbeard** [comment]
Right, agreed, just figured we didn't need the https:// in there. Thanks!

**Comment by jenntbeard** [comment]
Let's use the facebook.com/HiveCHA.

**Comment by gvn** [comment]
Fixed

**Comment by hannahkane** [comment]
Verified
