### ISSUE TITLE
Mozilla Clubs - broken link

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/learning.mozilla.org#2331]
In the page: https://learning.mozilla.org/en-US/clubs/list/ the "Get Help" section takes the user to a 404 page (when user clicks on "Resources").
<img width="934" alt="screen shot 2016-10-11 at 11 15 21 am" src="https://cloud.githubusercontent.com/assets/22157921/19282632/0149fa62-8fa4-11e6-9472-b14bf6f5cc39.png">

**Comment by hannahkane** [comment]
Note: should link to https://learning.mozilla.org/en-US/clubs/running

**Comment by aayushsanghavi** [comment]
@hannahkane I'll take it up.

**Comment by hannahkane** [comment]
Thanks very much, @aayushsanghavi!
