### ISSUE TITLE
Create landing page and documentation for curriculum localization campaign

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#2337]
Let's use something lightweight like a wiki. Should include:
 * Call to action + a way to indicate your interest/locale (could be a google form)
 * Documentation describing the three ways to localize (copying gdocs, forking github repos, or remixing Thimble projects)
 * Instructions for how to submit localized activities
 * Information about the incentives
 * Information about the timeline of the campaign

**Comment by gideonthomas** [comment]
This is done: https://mozilla.github.io/curriculum-localization/
