### ISSUE TITLE
QA: Portfolio photos

### ISSUE THREAD

**Issue by jenntbeard** [mozilla/learning.mozilla.org#2342]
#2228

There are images provided for all but five of the projects in this spreadsheet: https://docs.google.com/spreadsheets/d/1Hd6DtgQpUd2rqCtI5TQIdHmvLlgOGa6Whf5BdHHUslM/edit#gid=1550807061 but it looks like images are missing for more than five of the projects on the website. If it's helpful, I can let you know which ones - I can also find alternate photos if the photos provided don't work for some reason.

**Comment by gvn** [comment]
It would be extremely helpful if you could provide the missing images. Thanks!

FYI / PS: We should consider the spreadsheet "locked" at this point. Edits should be requested via GitHub tickets here. I can't just export the spreadsheet again because we're now using a flat JSON file that has further edits done after I exported from Sheets. Basically, we can't do a "merge" from Google Spreadsheets to JSON without a lot of work.

**Comment by gvn** [comment]
CC @hannahkane ^

**Comment by hannahkane** [comment]
Want to make sure there's not some other issue here. Sounds like @jenntbeard was saying that some items *did* have an image in the spreadsheet, but aren't showing up on the site. Is that because they were added to the spreadsheet after the page was built?

**Comment by jenntbeard** [comment]
Right, that's what I was saying @hannahkane. If it's easier, post-production, I can always add in the missing images (since I need to gather ones for the five that don't have then anyways). I'm assuming we're still going to have access for portfolio/events through the django backend?

**Comment by gvn** [comment]
Right now there's no service fueling the Gigabit build. It's all based off a flat, static JSON file.

Eventually we will probably switch over to Django, but for now a dev (or someone comfortable with making a PR) will need to tweak the JSON file directly in this repo to make updates.

**Comment by hannahkane** [comment]
OK, I'm going to assume that the images got added to the spreadsheet after Gavin exported to the JSON file.

From now on, let's consider the spreadsheet locked, and let's file github issues for updates.

(Building out a service for this is on the roadmap for H1 of 2017)

**Comment by jenntbeard** [comment]
Sounds good - I wasn't sure when LF added the images to the sheet. Thanks!

**Comment by gvn** [comment]
@jenntbeard @hannahkane This is the last outstanding QA ticket. Is this a launch blocker?

**Comment by jenntbeard** [comment]
Wahoo! It's not a blocker for me...

**Comment by hannahkane** [comment]
me neither. Let's launch it!

**Comment by hannahkane** [comment]
Closing this issue. @jenntbeard - if you have images to add, please file additional tickets.
