### ISSUE TITLE
Finalize badges for Mozfest

### ISSUE THREAD

**Issue by Pomax** [mozilla/learning.mozilla.org#2346]
## This is a checklist for the work left to be done for badges before MozFest
- [x] add [X-Allow-Html header](https://developers.credly.com/best-practices#rich-text) for getting markup rather than plain text for reqs/evidence/desc

This allows us to use marked up badge criteria ("what they need to do") and evidence requirements ("what they need to show as proof of doing"), so that we don't need to do weird text parsing but can rely on uniformly reading in itemized lists. As a consequence it also means we can reliably sync the number of items in the criteria and evidence requirements lists.

PRs for this are open on learning.moz as https://github.com/mozilla/learning.mozilla.org/pull/2349 and on Teach-API as https://github.com/mozilla/teach-api/pull/75
- [x] fetch badge description non-truncated

The API seems to be giving us a 127 character description, which is not sufficient if we want to list the full badge description on the badge pages. The PR for this is https://github.com/mozilla/learning.mozilla.org/pull/2352
- [x] auto-fill the user's email address when linking accounts

Right now the field is left empty, which is counter productive and a good way to foster confusion in our users. PR filed: https://github.com/mozilla/learning.mozilla.org/pull/2347
- [x] verify that badge requests go through to credly

I noticed I can apply for a badge on localhost without the application actually making it into the credly system. Something's throwing a 404. **This currently "works but we don't know why", and so it might still break on staging, in which case we will have to investigate there.**
- [x] ensure that badge application data is preserved on a failed badge application

When a user applies for a badge and something goes wrong (due to either us, or Credly) we should make sure that the user's supplied evidence is restored rather than wiped. PR for this is https://github.com/mozilla/learning.mozilla.org/pull/2359
- [x] show the `achieved` date for an achieved badge, rather than the `created_at` date

Right now achieved badges do not merge in the "achieved" date for when a user claim was approved. This needs to come from the user's badge instance, not the "get_all_mozilla" list in the Teach-API. The PRs for this are https://github.com/mozilla/learning.mozilla.org/pull/2356 and https://github.com/mozilla/teach-api/pull/77
- [x] create the link to credly for a user's achieved badge(s)

We should give users a link to their badge "on credly" when they're viewing an achieved badge. The PR for this is https://github.com/mozilla/learning.mozilla.org/pull/2348
- [x] style of the twitter/facebook social links

Right now they're a default-styled unordered list. Semantically correct markup, visually incorrect presentation (that should be an inline set of links). The PR for this is https://github.com/mozilla/learning.mozilla.org/pull/2350
- [x] style attached files-as-evidence, currently they're inline blocks that just run off the line.

The PR for this is https://github.com/mozilla/learning.mozilla.org/pull/2351
- [x] clean up the "you've applied, return to the badge" button styling

It looks pretty weird, the button doesn't seem like it fits the text right now. PR for this is https://github.com/mozilla/learning.mozilla.org/pull/2357
## things we need but can wait until post-mozfest if we don't have time:
- [ ] admin view for credly that shows user + token + token age/expiration with a "renew" button and sort-on-days-till-expiration

This can easily be implemented as a stopgap to ensure users' tokens don't expire while we set up a crontab that talks with Django to automatically renew tokens that are near-expiry on a daily basis.

**Comment by Pomax** [comment]
# Badge Workflow 

## 1) Creating a badge

- Staff User goes to Credly; logs in with an account that has admin privileges for the shared Mozilla account
- User creates badge which involves uploading an image, adding a badge description, and adding criteria. ***To be resolved: details about how to properly format the criteria so that it shows up nicely on learning.m.o.*** (This is pending a response from Credly to a question Pomax asked them.)
- Badge is visible on learning.mozilla.org

## 2) Applying for and receiving a badge

- Applicant User goes to learning.mozilla.org and clicks on Credentials nav item
Views list of available badges, and clicks in to view details of a specific badge (image, description, criteria)
- Clicks on "Submit evidence to apply for this badge" button
- Completes text field and/or uploads as many files as they'd like
- Clicks "Submit"
- Sees dismissable success message 
- Until badge application is approved or denied, user will see "Pending" status on badge detail view
Once approved, user will see "Achieved" status as well as a link to view their badge on Credly (useful if user wants to see a record of the evidence submitted)

## 3) Reviewing badge applications

- Staff User visits Credly; logs in with an account that has admin privileges for the shared Mozilla account
- Views "Requests" tab ***To be resolved: can admin user adjust Credly settings to be notified when new requests are submitted?***
- Reviews evidence submitted
- Approves or denies application

***To be resolved: does applicant get notified in any way?***

## 4) Awarding a badge that has not been applied for (alternate workflow; may not be something we actually use)

- Staff user visits Credly; logs in with an account that has admin privileges for the shared Mozilla account
- Chooses a badge and proactively awards it to someone by entering their email address
***To be resolved: how does Credly handle this part? Does the badge recipient receive an email from Credly requiring that they create an account?***
- Recipient must go to Credly to claim the badge

**Comment by Pomax** [comment]
prerequisite PR that we need to land so we can do normal branches for all these fixes: https://github.com/mozilla/learning.mozilla.org/pull/2339

**Comment by Pomax** [comment]
We do need to improve the copy for when applications go wrong - and possibly the styling a bit, too. To keep things in line with the application modal, I'm currently using this:

![screenshot 65](https://cloud.githubusercontent.com/assets/177243/19499519/b967aaf2-954b-11e6-8564-e64da0de4041.png)

![screenshot 64](https://cloud.githubusercontent.com/assets/177243/19499081/490f6904-9549-11e6-8382-01fce6403018.png)

**Comment by Pomax** [comment]
@simonwex do you know what our production instance for credly is? Do we still want mozilla.credly.com?

**Comment by hannahkane** [comment]
I'm not Simon, but I'd say yes. :)

**Comment by Pomax** [comment]
@hannahkane that might need a few more words to further qualify what "yes" entails =)

**Comment by hannahkane** [comment]
yes to mozilla.credly.com.
