### ISSUE TITLE
Update Mozilla Curriculum Workshop Landing Page for MozFest

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning.mozilla.org#2358]
The Curriculum Workshop landing page needs to be updated to reflect the upcoming "Live from MozFest" broadcast:

**"Upcoming Workshop" blue call out box:**
 October 30th - 6am PT/ 9am ET/ 2pm BST/ 1pm UTC

@chadsansing - can confirm the times are correct above?

**Paragraph beneath callout box:**
Join co-hosts Amira Dhalla and Chad Sansing live from London as they talk with guests from around the world about all the learning and making going on at at the festival. Members of the Mozilla Clubs network will appear on the webcast, as well, to share their MozFest experiences throughout the network.

**For reference:** Air Mo landing page: https://air.mozilla.org/mozilla-curriculum-workshop-live-from-mozfest-2016-10-30 

Waiting on embed code from Air Mo team.

**Comment by KGorr** [comment]
Times confirmed correct.

**Comment by hannahkane** [comment]
@kgorr - do we have the embed code yet? I'll wait for that before making these updates.

**Comment by hannahkane** [comment]
@kgorr - sorry, just saw you included the link in the first comment.

**Comment by KGorr** [comment]
@hannahkane - can you access the embed code from that link? If not, let me know and I'll follow up with Richard.

**Comment by hannahkane** [comment]
Is there an etherpad link?

**Comment by KGorr** [comment]
https://public.etherpad-mozilla.org/p/curriculum-workshop-october-30-2016 Sorry for forgetting it!
