### ISSUE TITLE
Update Community Call Landing Page for Nov

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning.mozilla.org#2366]
Here is the November information to update the community call landing page:

Etherpad: https://public.etherpad-mozilla.org/p/mozcommunitycallnov16

AirMo link: https://air.mozilla.org/mozilla-learning-community-call-youth-leadership-2016-11-16/

"Upcoming Call" box
November 16 - 2:30pm PST/ 4:30pm CST/ 5:30pm EST/ 9:30pm UTC
Join Mozilla Hive Chicago, Mozilla Hive NYC, and other special guests to discuss youth leadership and empowering young people to get involved in local, national and global community issues that matter to them.

Text below box
Delete current content & do not replace with anything

Upcoming Calls
There will be no Community Call in December. Check back in 2017!

Let me know if you need anything else!

**Comment by hannahkane** [comment]
@kgorr - I'm going to go with "Youth Leadership" for the title. Let me know if you'd prefer something else.

**Comment by KGorr** [comment]
Perfect - thank you!

**Comment by hannahkane** [comment]
This is live now.
