### ISSUE TITLE
look at alternatives for mapbox (used on /clubs)

### ISSUE THREAD

**Issue by Pomax** [mozilla/learning.mozilla.org#2369]
based on https://github.com/mozilla/learning.mozilla.org/issues/2368 it might be worth looking at alternative mapping libraries that don't cost $500/mo

**Comment by ryanwarsaw** [comment]
It wouldn't hurt to send an email to Mapbox, explaining our use case and see if they have any special offerings for open source folks (like us :o)!

**Comment by alicoding** [comment]
@ryanwarsaw I think @cadecairos sent an email and they said open-source or non-porfit gets 10% off >.<

**Comment by jgmac1106** [comment]
You could just use a Google Map and ask club Captains to pin themselves. We
did this for #Walkmyworld one year:
https://sites.google.com/site/walkmyworldproject/maps

**Comment by hannahkane** [comment]
Also see https://github.com/mozilla/learning.mozilla.org/issues/2277

I like the simplicity of @jgmac1106's idea, though it would mean the information in each pin wouldn't be standardized.

**Comment by cadecairos** [comment]
> @ryanwarsaw I think @cadecairos sent an email and they said open-source or non-porfit gets 10% off >.<

yeah, the nonprofit subscription is still $450/month, which is insane for just a single map on a page.

>  Hey Christopher, thanks for reaching out! Can you point me to where the maps are on the page? Poked around but must have missed them. We do offer a 10% discount for nonprofits :) Looks like you're doing amazing work!

**Comment by alicoding** [comment]
>"Looks like you're doing amazing work!" LOL

**Comment by cadecairos** [comment]
yeah, compare that to the 99.75% non-profit discount on mattermost enterprise and the 100% non-profit discount from zenhub, and it really leaves you wanting more.

**Comment by Pomax** [comment]
we could do a google maps but rather than having users place pins, we might be able to use google's [custom overlays](https://developers.google.com/maps/documentation/javascript/customoverlays) functionality instead, so that we still control the data, but the underlying map functionality is managed by gmaps.

**Comment by hannahkane** [comment]
Closing this given new work being done on Clubs module
