### ISSUE TITLE
Update MCW landing page

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning.mozilla.org#2371]
@hannahkane, can you update the MCW landing page for our 11/17 episode using [this doc](https://docs.google.com/document/d/1Bvpwazs17AS1HJtjxo3amdD50ugKd4LHlo59UmvINno/edit)?

@KGorr, can you get the AirMo link?

cc @ohnopauloh, @amirad

**Comment by KGorr** [comment]
AIr Mo event link: https://air.mozilla.org/mozilla-curriculum-workshop-youth-leadership/ 

Let me know if you need anything else.
