### ISSUE TITLE
Finalize interactive curriculum role proposal.

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2373]
Here is the [current proposal](https://docs.google.com/document/d/1yLzpnaG-pYfiLCGt0PBaJAPGaPVY6puxCl9InLAvqd0/edit).

Based on latest discussions, need to make some updates...

* Identify state-change in the org as a result of undertaking this project.
  * What gets better, and how does it advance our goals?
* Identify core audience for the content
  * Self-directed learners, or...
  * Educators and leaders

**Comment by chadsansing** [comment]
- Promotes internet health by showing how powerfully the web can deliver new kinds of teaching and learning in open, innovative ways.
- FWIW, current way of dealing w/ audience is creating educator/leader-facing lesson plan + learner-facing tutorial.

**Comment by hannahkane** [comment]
@flukeout - ok if I close this?
