### ISSUE TITLE
"all badges" are returned in batches of 10 - that should be "all"

### ISSUE THREAD

**Issue by Pomax** [mozilla/learning.mozilla.org#2374]
right now the "all badges" list only gives us 10 badges, due to how the Credly API returns results. This should just be all badges in one go, with the Teach-API side making sure to get all the badges if there's more than one set to retrieve.

/cc @hannahkane

**Comment by Pomax** [comment]
https://github.com/mozilla/teach-api/issues/78

**Comment by IBGMozilla** [comment]
Yes, we need to display all 18 badges displayed (four 21st badges & 14 web literacy badges). @Pomax @gideonthomas

**Comment by Pomax** [comment]
PR filed, upping the result set for badge listings from 10 to 9999, which seems a far more reasonable number, even if we don't have 9999 badges *quite* yet =)
