### ISSUE TITLE
update "21 century" title

### ISSUE THREAD

**Issue by Pomax** [mozilla/learning.mozilla.org#2375]

**Comment by anmechung** [comment]
https://learning.mofostaging.net/en-US/badges Please change 21 Century skills Credentials to Web Literacy and 21st Century Skills Badges

**Comment by anmechung** [comment]
also, update text underneath from "Certain skills are critical to becoming a citizen of the web — like the ability to communicate, collaborate and create online. Hone these skills and earn badges that spotlight your expertise." to 

"Certain skills are critical to becoming a citizen of the web.  Hone these core web literacy and 21st Century skills and earn badges that spotlight your expertise."

**Comment by anmechung** [comment]
Change "Explorer all badges we offer and which ones you qualify for. Apply for badges by sharing your experiences. Then show your employers and friends you have the skills." to 

"Explore core web literacy and 21st Century skills badges, apply for these badges, and share with others the skills you have learned."

**Comment by Pomax** [comment]
"spotlight" or "highlight"? (as far as I'm aware the first is more used as noun)

**Comment by anmechung** [comment]
"highlight" is much better!

**Comment by Pomax** [comment]
updated the PR
