### ISSUE TITLE
fix the styling around badges not offering enough space to show the entire short description

### ISSUE THREAD

**Issue by Pomax** [mozilla/learning.mozilla.org#2376]
https://learning.mofostaging.net/en-US/badges currently shows badges in boxes that cut off the description text due to fixed height CSS, 

![screenshot 82](https://cloud.githubusercontent.com/assets/177243/20076449/474a7cf4-a4ed-11e6-85a8-0eec7a52bed1.png)

**Comment by IBGMozilla** [comment]
Can you update on the status of this @Pomax @gideonthomas. Thanks!

**Comment by Pomax** [comment]
PR filed, it now looks like this:

![screenshot 105](https://cloud.githubusercontent.com/assets/177243/21122334/55c41b28-c086-11e6-83e7-d3c7e415b196.png)

**Comment by IBGMozilla** [comment]
When I look at the staging site, I don't see these fixes and the text continues to cut off after a limited number of words.

**Comment by gideonthomas** [comment]
@IBGMozilla, this hasn't been fixed on the staging site so you will only see the fix after https://github.com/mozilla/learning.mozilla.org/pull/2396 has been merged into this repository and this issue is closed.
