### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/learning.mozilla.org#2381]
All the links in Portuguese for the following page are broken:
https://learning.mozilla.org/en-US/clubs/running

Please see examples with screenshots here:
![learning-dot-mozilla](https://cloud.githubusercontent.com/assets/22157921/20285518/3b8a2092-aa77-11e6-9f7e-5cf6f32dd3ef.png)

**Comment by Pomax** [comment]
Interesting. That looks like broken links on https://leaomozillaclubs.com, and I don't know who runs that. @hannahkane @KGorr any idea?

**Comment by hannahkane** [comment]
cc @jvallera

**Comment by jvallera** [comment]
Hmm, not sure. Looking into it with a community member who I think wrote them.

**Comment by jvallera** [comment]
Ok, looks like all the Portuguese links are broken, plus some in English. The Club that did these just moved their content to a new location. Sorry about that, can I help at all?

Here are the working links:

A Mozilla Club In Your Established Program: https://leaomozillaclubs.gitlab.io/mozillaclubsguides/existing-program/
Mozilla Club in a neighborhood with low connectivity: https://leaomozillaclubs.gitlab.io/mozillaclubsguides/neighborhood-with-low-connectivity/

EN-US
https://leaomozillaclubs.gitlab.io/mozillaclubsguides/creating-a-website-en-US/

PT-BR
https://leaomozillaclubs.gitlab.io/mozillaclubsguides/creating-a-website-pt-BR/
https://leaomozillaclubs.gitlab.io/mozillaclubsguides/community-meet-up/
https://leaomozillaclubs.gitlab.io/mozillaclubsguides/your-first-month-as-a-club-captain-without-rc/
https://leaomozillaclubs.gitlab.io/mozillaclubsguides/branding-guidelines/
https://leaomozillaclubs.gitlab.io/mozillaclubsguides/afterschool-program/

**Comment by jvallera** [comment]
Ok, looks like all the Portuguese links are broken, plus some in English. The Club that did these just moved their content to a new location. Sorry about that, can I help at all?

Here are the working links:

A Mozilla Club In Your Established Program: https://leaomozillaclubs.gitlab.io/mozillaclubsguides/existing-program/
Mozilla Club in a neighborhood with low connectivity: https://leaomozillaclubs.gitlab.io/mozillaclubsguides/neighborhood-with-low-connectivity/

EN-US
https://leaomozillaclubs.gitlab.io/mozillaclubsguides/creating-a-website-en-US/

PT-BR
https://leaomozillaclubs.gitlab.io/mozillaclubsguides/creating-a-website-pt-BR/
https://leaomozillaclubs.gitlab.io/mozillaclubsguides/community-meet-up/
https://leaomozillaclubs.gitlab.io/mozillaclubsguides/your-first-month-as-a-club-captain-without-rc/
https://leaomozillaclubs.gitlab.io/mozillaclubsguides/branding-guidelines/
https://leaomozillaclubs.gitlab.io/mozillaclubsguides/afterschool-program/

**Comment by Pomax** [comment]
Hm, I'm trying to figure out where these links actually live. If they're managed through Pontoon then they might need to be updated there and then a language resync would fix this without us doing anything in particular

**Comment by Pomax** [comment]
According to @gideonthomas these are strings that live in the Teach-API, and require going into the admin view for the club guides and updating them there. Do you have the perms to do this @jvallera?

**Comment by jvallera** [comment]
I thought I did @Pomax but when I am in admin on the Teach-api I don't see the glub guides anymore. All I see is the list of clubs and users. @gideonthomas is there somewhere else I should be looking? Thanks.

**Comment by gideonthomas** [comment]
Oh sorry @jvallera! Apparently the permissions to access club guides was not set for staff. Just fixed that so you should be able to see it now; let me know if you don't.

**Comment by jvallera** [comment]
@taisdesouzalessa all links should be fixed now.

**Comment by taisdesouzalessa** [comment]
@jvallera this is amazing, thanks for everything! So many people contributing to fix this issue here. Thank you for all your help, everybody. Really appreciate it!
