### ISSUE TITLE
Update Mozilla Curriculum Workshop Landing Page

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning.mozilla.org#2387]
Unfortunately, we had to cancel our curriculum workshop today due to guest illness. Can you please update the page to say "Postponed" where the current date and time reside?

Let me or @chadsansing know if you need any more info. Thanks!

**Comment by hannahkane** [comment]
@gvn - are you able to do this and push it out today?

**Comment by gvn** [comment]
Sure

**Comment by gvn** [comment]
This is live now: https://learning.mozilla.org/en-US/community/curriculum-workshop

**Comment by KGorr** [comment]
You guys are super fast - thank you!
