### ISSUE TITLE
Update placement of Letters to President and Build First Web Page modules on /activities 

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/learning.mozilla.org#2389]
Can we change the placement of the Letters to the Next President and Build Your First Web Page modules on learning.mozilla.org/activities? 

We initially bumped up the Next Pres module to the top of the page to help drive traffic leading up to the election, but that is now behind us :(

The new module seems like a good one to take it's place at the top!

I'd suggest moving Letters to the Next President to the bottom of the list, below Made with Code.

**Comment by hannahkane** [comment]
Covered in #2405
