### ISSUE TITLE
Remove past event from Gigabit Event Page

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/learning.mozilla.org#2393]
Filed by @jenntbeard

### Details

MozFest has passed, we'd like to remove it from our upcoming events page. (I know eventually we will be able to do this ourselves, but I don't think we can do this yet, correct?)

### Info & links

On https://learning.mozilla.org/en-US/gigabit/events, there is an event that has passed - MozFest. Please remove it. Thanks!

cc @hannahkane

**Comment by jenntbeard** [comment]
This is still showing up on the website....

**Comment by gvn** [comment]
This had been landed to `master`, but not deployed.

I just ran a build, so should be live on production now...
