### ISSUE TITLE
HOLD until further updates: Update Community Call & Curriculum Workshop Landing Pages

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning.mozilla.org#2397]
The community call and curriculum workshop landing pages need to be updated. Upcoming event times and details are still TBD for 2017, so suggestions for updating the copy is as follows:

Remove all upcoming info, live stream embed & etherpad embed so that only general description of event at the top of page, blue box blurb & archives remain. 

**Community Call Blurb in blue box:** "Thanks for your interest in the Mozilla Learning Community Call! Check back in 2017 for upcoming call details." 

**Community Call general description** adjust to "This community call provides the opportunity to connect in real time with Mozilla and to ask questions and interact with others in our community who are doing their part to #teachtheweb." 

**Curriculum Workshop Blurb in blue box**: "Thanks for your interest in the Mozilla Curriculum Workshop! Check back in 2017 for upcoming workshop details." 

CC: @chadsansing @ldecoursy

**Comment by KGorr** [comment]
@chadsansing - if this doesn't get updated before you have info for your February MCW, can you please provide new info for the landing page? Thank you!

cc: @hannahkane

**Comment by chadsansing** [comment]
Yah - hoping to move on invites this week, well ahead of 2/16/17 webcast date. Deadline?

**Comment by KGorr** [comment]
Thanks, Chad! Deadline will depend on when Hannah's team can update the page, so I'll let her dictate that. :)

Also, @hannahkane - you can put a hold on the community call page updates for now. We may be changing direction for what the page will look like during our "hold." Will let you know as soon as I can. Thanks!

**Comment by KGorr** [comment]
@hannahkane - we are considering two options for the community call landing page, since it looks like they will be on hold until further notice. Would love your input, especially for which is easiest to implement.

**Option 1:** Eliminate the Community Call Landing Page completely and add this blurb to the main Community landing page (maybe under the Connect with Others blurb): "View our community calls and curriculum workshop archives that cover topics ranging from youth leadership to women in STEM. [link: https://air.mozilla.org/channels/Mozilla-Learning]  

**Option 2:** Keep the Community Call submenu on the learning.mozilla.org site, but it links directly to https://air.mozilla.org/channels/Mozilla-Learning/ (just like the Hive & MozFest submenus)

Lainie and I discussed this morning, and believe option 1 is preferable since option 2 may call attention (and prompt questions) to the fact that we aren't doing them right now. Let us know what you think!

**Comment by hannahkane** [comment]
Hey @KGorr - we can do either, but doesn't https://air.mozilla.org/channels/Mozilla-Learning/ exclude a bunch of the community calls we've done?

**Comment by KGorr** [comment]
@hannahkane -nice eye :) It does exclude a handful from the beginning of the year. I plan to have them uploaded in the next few days, so the channel will be complete soon.

**Comment by KGorr** [comment]
And I'll also be making sure all of them have direct links to the etherpads used.

**Comment by KGorr** [comment]
@hannahkane - all videos (with the exception of one I am getting help with from AirMo) have been added to our channel. Option 1 can be implemented whenever your team is ready. Thank you!
