### ISSUE TITLE
Clarify gigabit language on landing page

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/learning.mozilla.org#2400]
### Details
We would like to replace the text under the 'What is Mozilla Gigabit?' header on the landing page in an effort to be more clear about what we mean, why we're doing the work and leave people wanting to know more (not less) about the wonderful world of the gig.

Old copy:
Mozilla Gigabit Community Fund provides catalytic funding in US communities to support pilot tests of gigabit technology and related curricula. We increase the participation in next-generation innovation to help support an Internet where all people are empowered, safe, and independent.

New copy:
The Mozilla Gigabit Community Fund provides grant funding in select U.S. communities to support pilot tests of gigabit technologies such as virtual reality, 4K video, artificial intelligence, and their related curricula. In so doing, our goal is to increase participation in technology innovation in support of a healthy Internet where all people are empowered, safe, and independent online.

### Info & links
The paragraph is on this page: https://learning.mozilla.org/en-US/gigabit 

@LindseyInCHA

cc @jenntbeard

**Comment by aayushsanghavi** [comment]
I'll take this up

**Comment by jenntbeard** [comment]
Has this been completed? It's not live on the site yet. Thanks!

**Comment by gideonthomas** [comment]
@jenntbeard there is a pull request with the changes for this. It needs to be fixed slightly and will be on the staging site after that. Once it's live on the main site, we will close this issue.

**Comment by jenntbeard** [comment]
We are currently pushing media to the site with our Round 2 grant announcement today - nearly a quarter million dollars is going out to 19 grantees. It would be great to have this language cleaned up for them. Thanks for your help!

**Comment by gideonthomas** [comment]
@jenntbeard this should be live now 👍
Closing...
