### ISSUE TITLE
Fix third criteria on Apply page

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/learning.mozilla.org#2401]
### Details
On the Apply page (https://learning.mozilla.org/en-US/gigabit/apply), the third funding requirement criteria should read: "Leverage next-generation technologies like virtual reality, 4K video, artificial intelligence, and their related curricula"

### Info & links
https://learning.mozilla.org/en-US/gigabit/apply

@LindseyInCHA 

cc @jenntbeard

**Comment by aayushsanghavi** [comment]
I'll take this up

**Comment by aayushsanghavi** [comment]
Could someone please review the PR
