### ISSUE TITLE
We need to update /activities

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning.mozilla.org#2405]
We should update [/activities](https://learning.mozilla.org/activities) to better organize our core offerings and curated offerings, as well as to use our most up-to-date versions of each core module/lesson/curriculum template.

We should update /activities in 2 steps.

# Better organize /activities

1. We should create a "core content" header at the top of our activities list an include these modules under it:

- Offline icebreakers
- Web Literacy Basics I
- Web Literacy Basics II
- Make Your First Webpage
- Privacy Basics: Protect Your Data
- Intermediate Web Literacy I: Intro to CSS
- Intermediate Web Literacy II: Storytelling with Scripts

2. We should create a "curated content" header after the core content section and list all remaining modules under that.

This gives users a quick and dirty way to filter our core content (which may also feature Mozilla-specific features like links to our badging work) from curated or community-generated content until we have a database or search UI.

# Link to updated activities for core content
@flukeout and @chadsansing should make sure the core modules in [this repo](https://github.com/mozilla/curriculum-final) are good to go, then we should link to these modules and activities from /activities.

This will give us a single repo for Mozilla content - and with Mozilla access - in the future.

cc @anmechung, @hannahkane, @ldecoursy, @Pomax

**Comment by hannahkane** [comment]
Thanks for the ticket, @chadsansing. A few questions/thoughts:

* Do you think it's best to do the re-arranging first, or can we reverse the order and finalize the core content first, then do the re-arranging?
* You said it would "give users a quick and dirty way to filter our core content from curated or community-generated content." Can you clarify what the users' mental model will be? Is it that users are looking for Mozilla-authored content? Or a sequence that makes up a defined curriculum for learners to progress through? Or something to indicate quality or vetting? Are the links to badge information important to the user here? (I'm not at all opposed to this re-arranging; I just want to understand the goal. Might impact copy choices, for example.)
*  The current page has a "More Resources" section that links to Hive Portfolios. Should those still appear on the page, or might we take this as an opportunity to remove them? (I think it's a little confusing as is.)

* Even though this seems pretty simple, I think we need a little bit of design work here—to advise on what styles to apply to the headers and maybe to help think about copy. I don't think "core content" and "curated content" will necessarily be meaningful to all users.

**Comment by chadsansing** [comment]
Oh, sure - let's finalize core content first. Sorry I transposed that! I think we're in pretty good shape; a @flukeout shakedown would be good. We should also be sure to settle on where we put badging information on activities before we make the change, but @anmechung and I are on the case and will have the matter resolved shortly.

I think the mental model will be, "Here is official, sequential Mozilla curriculum," and then, "Here are other modules curated from within Mozilla and from across its communities to complement/xtend/supplement the core curriculum." We will have groups like the IMLS pilot and Web Literacy Leaders who need quick, consistent access to the materials we train them to use while teaching others. I also think this will be a good stop-gap way to denote differently the stuff we make as part of an intended curriculum and the stuff we amplify as others share it. 

Badging cues will go inside activities; they won't show up here right now.

A note: I don't think we should use official vs. unofficial or Mozilla vs. community as some pieces of what we're calling "curated" curriculum come from people in Mozilla.

I would ask Meghan about the Hive links and whether or not the Hive cities can do without those links. 

I'd love to hear what others think we might use instead of "core" and "curated" - super open to suggestions. I agree that some design work would be helpful here.

**Comment by hannahkane** [comment]
Don't want to drop this.

How about something like "Core Web Literacy Curriculum" and "Additional Teaching Activities" for the headings?

**Comment by chadsansing** [comment]
@hannahkane - surely.

**Comment by hannahkane** [comment]
Cool. @chadsansing - are the core modules good to go?

**Comment by chadsansing** [comment]
Give me until Friday to make sure the core modules on https://github.com/mozilla/curriculum-final match our latest Thimble edits. Any other input here, @anmechung, @flukeout?

**Comment by anmechung** [comment]
@chadsansing and I checked in, and see two stages for updates: 1) updating organization of activities, and 2) updating content.  Working with @chadsansing to update some of content as part of organizing activities (this week and next), and with @ibgmozilla to update content based on recommendations from consultant. Content will take longer, and occur throughout the next few months.

**Comment by chadsansing** [comment]
Quick update: 

1. Once we "lock" badging language for now, Chad will update the IMLS curriculum and use those docs to update the activities in the https://mozilla.github.io/curriculum-final repo. 
2. Then he will let Hannah know those files are ready to be linked to as part of re-organizing https://learning.mozilla.org/activities into two categories: "Core Curriculum" and "Additional Teaching Activities."
3. Then An-Me, Iris, Chad, and any other people working on content can continue to update the activities as needed.

Make sense? The goal is to have the badging revisions done ASAP and to do those before Hannah reorganizes /activities.

cc: @hannahkane, @anmechung, @ibgmozilla

**Comment by chadsansing** [comment]
Let's also leave the old localized versions of the Web Literacy Basics I activities "alive" so we can link to them from the updated pages we'll use like so:

![screen shot 2017-02-17 at 7 55 57 am](https://cloud.githubusercontent.com/assets/4128600/23066074/b6aceb74-f4e6-11e6-9063-abcc192579f1.png)

**Comment by chadsansing** [comment]
@hannahkane, @flukeout, @anmechung, @ibgmozilla - I have updated the files in the curriculum-final repo to match what we're offering our IMLS pilot participants on Thimble.

https://github.com/mozilla/curriculum-final

I think we are ready to reorganize /activities and change the links for the modules named above on /activities.

**Comment by hannahkane** [comment]
Cool. Thanks, @chadsansing.

@flukeout - I can update the links and re-order the activities, but I won't be able to add Headers for "Core Curriculum" and "Additional Teaching Activities." At least not without some help. Can you advise?

**Comment by chadsansing** [comment]
@hannahkane,thank you for all the updates! So helpful! Can you update Web Lit Basics I with the new curriculum-final links, as well?

**Comment by hannahkane** [comment]
@chadsansing - yes, will do. 

@flukeout - when you have a moment, could you provide some guidance on how I can add some Headers to the Activities page? Thanks!

**Comment by flukeout** [comment]
Just chiming in that @hannahkane got it solved without me!

**Comment by hannahkane** [comment]
lol. yes, @flukeout, I am a genius for not realizing I just needed to add H2s. :) I can't remember what about this seemed more complicated to me.

Anyway...I put in a PR and assigned it to Chad to take a look.

**Comment by chadsansing** [comment]
@hannahkane - any idea what happened to the line on each activity right before the web literacy skills in the overview that said, "Follow this link to remix this activity on Thimble!"?

**Comment by chadsansing** [comment]
@hannahkane - nvm; fixed!
