### ISSUE TITLE
Remove Webmaker Branding

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/learning.mozilla.org#2407]
I'm not sure if this is something we need to do or not, but a lot of text on https://learning.mozilla.org/blog/ has references to "Webmaker" such as the description, "Planet Webmaker", etc.

Should we remove it?

**Comment by hannahkane** [comment]
Suggestion:

Replace "Webmaker helps people across the world become informed creators of a free and open web." with "Mozilla Learning helps people across the world become informed citizens of a free and open web."

Remove Planet Webmaker widget.

@ldecoursy - is the above alright?

**Comment by ldecoursy** [comment]
Great catch @gideonthomas  

Do we even need the sidebar description since there's a subhead at the top of the page? If so I might change it to "Mozilla Learning rallies and connects leaders who want to advance the promise of the Internet for learning in a networked world." (matches the statement on learning.mozilla.org)

+1 to removing Planet Webmaker

**Comment by hannahkane** [comment]
+1 to just removing the sidebar description

**Comment by aayushsanghavi** [comment]
@hannahkane I would like to take it up. Could you tell me what needs to be removed or changed.

**Comment by hannahkane** [comment]
Thanks for your interest, @aayushsanghavi. I'm not sure we have a good workflow set up to make these changes, as I think whoever fixes this needs to have access to our Wordpress account. Is that right, @gideonthomas?

**Comment by gideonthomas** [comment]
@hannahkane I think that's right. @aayushsanghavi this might not be a great bug for you to fix for the reason that is mentioned above. Maybe you might be interested in fixing https://github.com/mozilla/learning.mozilla.org/issues/2314 ?

**Comment by aayushsanghavi** [comment]
@gideonthomas I'll check it out. Thanks for the suggestion.
