### ISSUE TITLE
Enable gzip compression

### ISSUE THREAD

**Issue by gvn** [mozilla/learning.mozilla.org#2408]
Compressing the following resources with gzip could reduce their transfer size by about two thirds (~1.2 MB):

learning.mozilla.org/
could save ~14.2 KB
css
could save ~15.6 KB
bootstrap.min.css
could save ~78.9 KB
font-awesome.min.css
could save ~20.2 KB
tabzilla.css
could save ~564 B
mofo-ui.css
could save ~4.3 KB
styles.css
could save ~68.1 KB
en.js
could save ~4.7 KB
commons.bundle.js
could save ~530 B
client.bundle.js
could save ~1.0 MB

**Comment by ryanwarsaw** [comment]
@gvn Just to clarify, do we want to do asset compression through the express framework, or through the web server configuration (nginx / apache2)?

**Comment by gvn** [comment]
I think it'll have to be through Express.

**Comment by ryanwarsaw** [comment]
@gvn This issue should be resolved, can you verify this is the case?

**Comment by gvn** [comment]
Verified on prod. Nice! 👍
