### ISSUE TITLE
Add new Gigabit Events to Events Page

### ISSUE THREAD

**Issue by jenntbeard** [mozilla/learning.mozilla.org#2409]
We have an update to an existing project (SxSWedu) and a new project on 2/22 to be added to our Gigabit events page (https://learning.mozilla.org/en-US/gigabit/events). [We also had a bug filed to remove MozFest from this page - mozilla/learning.mozilla.org#2393 - but it still appears active, despite that bug being closed.]

For info, please use this worksheet:
https://docs.google.com/spreadsheets/d/1X3nmzwZkG0lJh-VfzBhuN6SQws2VM6WeR8Rybol8GTk/edit#gid=0

**Comment by hannahkane** [comment]
@gvn - can I assign this to you?

**Comment by gvn** [comment]
Sure thing

**Comment by gvn** [comment]
#2393 was fixed, but not deployed. It's live now.

**Comment by gvn** [comment]
I'm not seeing a link to a thumbnail for 2017 Education Innovation Showcase.

Can someone provide it please? Thanks!

**Comment by jenntbeard** [comment]
Can you pull in the image from the Eventbrite page? https://www.eventbrite.com/e/education-innovation-showcase-tickets-30495213003 
![https_cdn evbuc com_images_27298424_66734185051_1_original](https://cloud.githubusercontent.com/assets/17835013/22160630/0470b2aa-df0c-11e6-95bc-9c9aeae5d289.jpeg)
