### ISSUE TITLE
High Priority: add new Gigabit portfolio projects

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#2411]
@jenntbeard - do you have all of the data in a spreadsheet? Can you please link to it here. Thanks!

**Comment by jenntbeard** [comment]
https://docs.google.com/spreadsheets/d/15q7NbUmIj21PWPmWgBM-w3D3RkJICp7dkmODcdR2WQQ/edit#gid=1136518992

Okay, Lindsey preferred that we just update the two existing projects - Gigabots and ViatoR with the new info. I have included images and links for those that have them. For ones without specific images, you can just use the Gigabit Community Fund logo (file attached here). Also, for this round we didn't include the partnering orgs, can that just be muted for these projects (so it doesn't appear with the header and be blank)?

Also, some of the projects don't have a specific type of gigabit technology, so you will notice they are blank.

![index](https://cloud.githubusercontent.com/assets/17835013/22163283/ca2e0a82-df17-11e6-82a7-dc48880f8cd9.png)

**Comment by hannahkane** [comment]
Are these all for year 2016?
Is there no data for the "Outcomes" field?

**Comment by hannahkane** [comment]
To clarify - for Gigabots and ViatoR - do you want to *replace* the content that's there with new content, or *add* the new content?
