### ISSUE TITLE
Couple changes to Gigabit portfolio

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#2419]
Create With Me!
 * Change project name to Accelerate, Augmented Reality for Workforce Training
 * Change short description to "Accelerate, Augmented Reality for Workforce Training will leverage gigabit connectivity to design an augmented reality tool that supports entry level IT learning for adults."

Virtual Realities in Culture: Explorations of the African Diaspora
 * Update logo
 * Update url to http://www.VFormAlliance.org

**Comment by hannahkane** [comment]
cc @jenntbeard

**Comment by jenntbeard** [comment]
Thanks, Hannah!!
