### ISSUE TITLE
https://forum.learning.mozilla.org signup/signin buttons don't show content

### ISSUE THREAD

**Issue by Pomax** [mozilla/learning.mozilla.org#2422]
Our content:

![screenshot 148](https://cloud.githubusercontent.com/assets/177243/22384081/93864ffc-e481-11e6-8463-a2f3885aef6d.png)

What it looks like on discourse.org:

![screenshot 149](https://cloud.githubusercontent.com/assets/177243/22384093/a2fb737c-e481-11e6-9fcc-0a873a70fb6e.png)

No errors or warnings whatsoever in the console to help see what might be wrong =(

**Comment by hannahkane** [comment]
@Pomax - can you include steps to reproduce? I don't think I can reproduce this, but maybe I'm not understanding something.

**Comment by cadecairos** [comment]
Shouldn't it open a window to sign-up/log-in with id.webmaker.org? (that's what it does for me)

**Comment by Pomax** [comment]
18 days ago this was a problem, but (thankfully) this cannot be reproduced anymore. Chucking this up to whatever network glitches discourse may have had.
