### ISSUE TITLE
Problem with "Authorized issuer" on Credly badges

### ISSUE THREAD

**Issue by IBGMozilla** [mozilla/learning.mozilla.org#2424]
@Pomax @anmechung -- I have given several people access to Credly to issue badges that were applied for on the mozilla staging site. The goal is for these individuals to be able to view and issue badges. 

To do this, I have entered their names in as "authorized issuer" for each of the web literacy badges on Credly. 

When they log in using their credentials, they can see the web literacy badges that have been created. They cannot see any "pending" badges that are awaiting approval. 

When I tried to trouble shoot. They're not associated with an “organization” level so Mozilla is not listed on their accounts. There are no “pending” badges to view possibly because they are not connected to Mozilla's account and we don't have the information to shift or add them to the Mozilla account, if that is what's necessary. 

Perhaps they need to be added as authorized users to the Mozilla account?

**Comment by Pomax** [comment]
as far as I am aware, authorised users can give credit (i.e. immediately issue a badge to someone), but they cannot pending badge requests. I will try to get that confirmed by credly but things might be a bit slow as I'm in Berlin at the moment for a community support work week.

**Comment by IBGMozilla** [comment]
Hi Pomax, I'm not sure if Gideon is available to help trouble-shoot as I'm
a little confused here. We need the pilots to be able to issue badges based
on badge applications that were applied to through the mozilla staging
site.

If they cannot see any badges that are pending, they won't be able to
review the pending applications, evidence submitted, etc. They need to have
access to these.

Do we need to give them different "rights" on the credly site so they can
see the pending badges? Is there another way to go about this so they can
issue based on what's pending?

Thanks and happy to jump on a quick call if that's easier.
Iris

**Comment by hannahkane** [comment]
@gideonthomas's pretty busy with Thimble right now, but he said he recalls we resolved this. I don't think I was involved in that conversation. @anmechung - do you recall?

I assumed we'd give them the same privileges we have on the site.

**Comment by Pomax** [comment]
I thought we had too, but I emailed credly just to make sure we know the solution here and we can add it to a section in the wiki or the readme or summer elder that we can easily find it in the future.

**Comment by IBGMozilla** [comment]
We hadn't discussed giving them the same permissions we have to my knowledge, but if that's an option, it may be best. We don't want them to be able to edit the badges, but we would like them to be able to view pending and approve/issue or decline. How should we proceed?

**Comment by hannahkane** [comment]
@pomax - does credly allow fine-grained permissions? Have you confirmed yet whether auth'ed users can view/approve pending badge requests?

**Comment by Pomax** [comment]
I got a response from Credly, and I'm not super happy with what they're saying. It sounds like we'd need to invest a fair number of hours writing a portal for these type of users OR give them manager rights similar to  your rights (which means they can edit, delete, etc...). 

Quoting the email thread:

---

> Hi Mike, 
> 
> In this case, the members that you've authorized to issue the badges need to sign in and create
> claim codes under their account for those badges, then the requests will be routed to the
> authorized members instead of the badge creator. 
> 
> Best, 
> Corey

---

> Hmm, that isn't really an option, users only ever see one badge list, there 
> is no selective grant code injection so specific applications go to 
> specific people.
> 
> We basically need to be able to delegate vetting to people who we 
> inherently cannot trust with badge edit and creation access (they do not 
> work for us, they can't invent credit on our behalf) but can trust with 
> reviewing badge applications.
> 
> Could we feature request a new level of user that is like a manager, but 
> had no edit/create rights? 
> -- Mike

---

>Unfortunately the product just isn't built for this at this time.  It's a great product suggestion.
> I've submitted it to the product team to be prioritized and planned for in the future. In the
> meantime,  let's try and find a work around if that's of interest.  
>
> Even though you're not using the APIs at the moment, I wonder if if you have an internal tech
> resource who might be able to cobble together a tool within Mozilla to unlock this in the
> meantime.  We'd be happy to advise you on your implementation if you choose to go this route.
>
> Best, 
> Corey

**Comment by hannahkane** [comment]
Since this is a pilot, can we give them full access + training about how to avoid unintentionally editing or deleting badges?

**Comment by Pomax** [comment]
Certainly, that call is mostly up to you and an-me. If you're willing to give that level of access, then that's a quick and easy solution.

**Comment by hannahkane** [comment]
This seems like a decision for @IBGMozilla and @anmechung to make.

**Comment by anmechung** [comment]
@IBGMozilla and I will discuss and let you know!  Thx for the follow-up
