### ISSUE TITLE
Hide email sign-up links from homepage and community page

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/learning.mozilla.org#2426]
Let's remove the links for email-sign ups. 

One is on the homepage - the first CTA button. Another is on the Community page towards the bottom. Might be worth double-checking if there are any other links on the site to sign-up but I think those are the only two ;)

**Comment by hannahkane** [comment]
I would do this myself, but I think I'd need instructions from a dev. @mmmavis or @gvn or @alanmoo - could you please advise?

**Comment by mmmavis** [comment]
No worries @hannahkane I'll file a PR for this.

**Comment by mmmavis** [comment]
@ldecoursy are we temporary hiding these the email signups CTA from UI? I'm deciding if I should remove all the email signup bits from the codebase or just hide them for now if we are planning to show them again in the near future. 😉

**Comment by mmmavis** [comment]
oops closed this ticket by accident

**Comment by hannahkane** [comment]
ping @ldecoursy. thoughts on @mmmavis's question above?

**Comment by ldecoursy** [comment]
Sorry I missed this. Perhaps best to hide for now. Could be we want to end up linking them to the new network site when it launches.

**Comment by mmmavis** [comment]
Alrighty. PR filed.
