### ISSUE TITLE
Update the Mozilla Curriculum Workshop page to reflect changes for 2017

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning.mozilla.org#2427]
Changes to be made [here](https://learning.mozilla.org/en-US/community/curriculum-workshop/
).

- Change the sub-header that says "Join us on the second Tuesday of each month!" to "Join us for a new episode each quarter!"
- Change "along with producers Kristina Gorr and Paul Oh" in the first paragraph to "along with producer Paul Oh."
- Under the "Upcoming workshops" subheader beneath the etherpad, change "March" to "Q2, 2017."

**Comment by jgmac1106** [comment]
Can we come up with something besides q1, q2, q3, and q4? Those terms and
dates are too familiar in education spaces.

I have no idea what a better option would be.

**Comment by chadsansing** [comment]
That would work; I would like to get everything set and delivered for the 2/16/17 episode and then set dates with the team for the rest if the shows. Then we can update again with dates. This terminology is temporary.
