### ISSUE TITLE
Where did the blog go?

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#2429]
Blog posts are no longer appearing on the homepage.

**Comment by Pomax** [comment]
Did we use the WP connector for this? Do that connector still work? @mmmavis might know more.

**Comment by mmmavis** [comment]
Nope it's not related to the CMS integration we tried to accomplish last year. 

https://github.com/mozilla/learning.mozilla.org/blob/master/lib/blog-feed-loader.js Maybe some API has been deprecated? I haven't touched this part for 2 years but I can take a look today/tomorrow.

**Comment by mmmavis** [comment]
Ah, Google Feed API has been deprecated since December 15th, 2016. https://developers.google.com/feed/ 😢 

Time to switch to another solution.

**Comment by hannahkane** [comment]
Hmm...maybe this is a good point to check in with @KevZawacki to see what the future of the [Learning blog](https://learning.mozilla.org/blog/) is. Kevin - are we planning to retire this blog in lieu of the Medium collections?

If so, our solution for pulling content onto the homepage should be about Medium, rather than Wordpress.

**Comment by KevZawacki** [comment]
I'm hesitant to say we're officially retiring our WordPress blogs... but more and more people are posting to [Read, Write, Participate](https://medium.com/read-write-participate) and [Mozilla Internet Citizen](https://medium.com/mozilla-internet-citizen). 

Plus, it's these two Medium blogs, and not WordPress, that will feed into the forthcoming Network site.

It's something I can talk through with @Lottarao.

**Comment by hannahkane** [comment]
Okay, I'm going to suggest we hold off on fixing this bug until we hear back from Kevin and Lotta.

Thanks!
