### ISSUE TITLE
maxAge for "Strict-Transport-Security" header is set to 90,000 days

### ISSUE THREAD

**Issue by mmmavis** [mozilla/learning.mozilla.org#2430]
😂 

https://github.com/mozilla/learning.mozilla.org/blob/master/app.js#L60-L62

I believe we want it to be 90 days instead. I will file a PR.

/cc @Pomax @cadecairos

**Comment by cadecairos** [comment]
hahahahaha nice find. browsers that have already visited will have this header for a loooong time.

**Comment by mmmavis** [comment]
PR merged:

removed HPKP since it's not safe to use; updated maxAge for HSTS to be 18 weeks
