### ISSUE TITLE
Remove language from front page of Gigabit

### ISSUE THREAD

**Issue by jenntbeard** [mozilla/learning.mozilla.org#2434]
Hi, on https://learning.mozilla.org/en-US/gigabit/ we need to take down the language and link/button to the new city application. We have no new slots available (for now).

Remove: Expanding the Gigabit Community Fund
In partnership with the National Science Foundation and US Ignite, we're expanding the Gigabit Community Fund to two additional gigabit cities by 2018. Click below to submit your city.
Start a Gigabit City [button]

Thanks!

**Comment by hannahkane** [comment]
This is deployed.

**Comment by jenntbeard** [comment]
Thank you!!
