### ISSUE TITLE
We should review MCW landing page update process as network update happens

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning.mozilla.org#2436]
It looks like we have a static image instead of a video embed from AirMo here for today's (2/16/17) webcast:

https://learning.mozilla.org/en-US/community/curriculum-workshop/

Since Kristina is no longer producing the show, we should review what @chadsansing and @ohnopauloh need to share to get the image linked to the right AirMo page in the future or to get an AirMo embed on the page. 

@hannahkane

**Comment by hannahkane** [comment]
Not sure I follow. When I go to that page, I see the video player. Can you clarify? Maybe I'm looking at the wrong thing.

**Comment by chadsansing** [comment]
Oh cool - it got added post webcast. That might be the review I needed of what happens post-on-air time :)

**Comment by hannahkane** [comment]
Yeah, I think it's just magic! (Why isn't there a magic emoji?)

**Comment by jgmac1106** [comment]
✨ 
    🍢
