### ISSUE TITLE
Clubs event reporter site not updating 

### ISSUE THREAD

**Issue by jvallera** [mozilla/learning.mozilla.org#2442]
Hello, I just noticed that the Mozilla Clubs event reporter is not updating properly. I have been approving events on the [spreadsheet](https://docs.google.com/spreadsheets/d/1QHl2bjBhMslyFzR5XXPzMLdzzx7oeSKTbgR5PM8qp64/edit#gid=1045576576), but they are not appearing in the [website](http://mozilla.github.io/clubs-events/#).  There are 167 approved and only 137 are showing up.  It seems the site may have stopped updating in early February. 

CC @flukeout @hannahkane

**Comment by flukeout** [comment]
Checking into it @jvallera

**Comment by flukeout** [comment]
So there should be 149 total showing up. There are 167 lines in the spreadsheet, but the first 15 are blank and there are several that are rejected / not approved in the list as well.

The last event in the spreadsheet isn't showing up on the list, even though it's approved. Another weird thing is that the second last event is dated as Jan 19, but shows up as Jan 20 on the list.

**Comment by flukeout** [comment]
Ha, okay found it... so the first item here is the last one to show up on the page...

![image](https://cloud.githubusercontent.com/assets/25212/23318420/32429914-fa87-11e6-94c7-257c1e2bf614.png)

the ones after it dont. Can you guess why? 



I only made the code check for "Approved" with a capital "A", so "approved" wasn't being picked up. Yikes! Anyway, I've changed the spreadsheet and filed an issue! A few of the dates are messed up in the reports too, like someone's even tis from December of 2017.
