### ISSUE TITLE
Add new event to gigabit website

### ISSUE THREAD

**Issue by jenntbeard** [mozilla/learning.mozilla.org#2456]
Can we add the following event:
Date: April 19, 2017
Time: 12:30-4pm
Location: Westport Commons
300 E. 39th St.
Kansas City, MO 64110 
Link to image: https://drive.google.com/open?id=0B5jxGZykGTyFSE10UFpUcl9Gb2ZMLUQ4bTFwQmdmb0pmV2sw
Event: Gig 101 Workshop
Event link: https://gig101workshopkc.eventbrite.com
Description: Join us for an interactive workshop for educators focused on demystifying high-speed internet! Since Google Fiber launched in Kansas City, we've seen one technology innovation after another taking advantage of this advanced high-speed network. But, what exactly is a 'high-speed internet network'? How does it work? What does 'gigabit' mean? What can you do with it? And, how can you actually use these connections to create new opportunities for your students or your community? Join us at this interactive workshop to learn more.

Can we preschedule this to be taken down on April 20, 2017 as well?

**Comment by hannahkane** [comment]
We don't have a way to schedule expiry, but I'll put it on the calendar to remove this on the 20th.

**Comment by jenntbeard** [comment]
Great, thank you!!

**Comment by hannahkane** [comment]
@jenntbeard - this is live now
