### ISSUE TITLE
Broken links on /activities Intermediate Web Lit I landing page

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning.mozilla.org#2458]
On this page, https://learning.mozilla.org/en-US/activities/intermediate-web-lit/, activities 3-8 have broken links. 

They should be:

- CSS Fonts Extension: https://mozilla.github.io/curriculum-final/intermediate-web-lit-one/session03-css-fonts-extension-activity.html#overview
- CSS Circles: https://mozilla.github.io/curriculum-final/intermediate-web-lit-one/session04-css-circles.html#overview
- CSS Blocks: https://mozilla.github.io/curriculum-final/intermediate-web-lit-one/session05-css-building-blocks.html#overview
- CSS Decoration: https://mozilla.github.io/curriculum-final/intermediate-web-lit-one/session05-css-building-blocks.html#overview
- Webotron: https://mozilla.github.io/curriculum-final/intermediate-web-lit-one/session07-webotron-and-the-scrambled-divs.html#overview
- External Tutorials: https://mozilla.github.io/curriculum-final/intermediate-web-lit-one/session08-external-css-tutorials.html#overview

@hannahkane

**Comment by aayushsanghavi** [comment]
@chadsansing I've opened a PR for this issue

**Comment by chadsansing** [comment]
@aayushsanghavi - thank you!
