### ISSUE TITLE
We need to update upcoming episodes on the Mozilla Curriculum Workshop page

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning.mozilla.org#2460]
@hannahkane, on the [MCW landing page](https://learning.mozilla.org/en-US/community/curriculum-workshopt ), can we replace the copy under "Upcoming Workshops" with this instead?

> **Spring**: Join us on Thursday, May 11th, 2017, at 10 AM ET, to talk about teaching and learning in response to the Fake News phenomenon.
> 
> **Summer**: Join us on Thursday, August 10th, 2017, at 10 AM ET, to revisit privacy and security. What resources can we make together to help learners understand the choices they have about online safety?
> 
> **Fall**: Join us on Thursday, November 16th, 2017, at 10 AM ET, to work on prototype teaching and learning resources that help promote digital inclusion and equity throughout our networks.

cc @ohnopauloh @amirad

**Comment by hannahkane** [comment]
@chadsansing - this is live

**Comment by chadsansing** [comment]
Thank you, @hannahkane!
