### ISSUE TITLE
Add Mozilla Gigabit video to homepage

### ISSUE THREAD

**Issue by jenntbeard** [mozilla/learning.mozilla.org#2472]
We would like to add our Mozilla Gigabit video to the main page of our website, right under the fox and intro paragraph. The video is on our MozGig Vimeo channel (https://vimeo.com/204621980) and the Mozilla YouTube channel (https://youtu.be/jRa4kB7LYoU). We also have a 4K file (https://drive.google.com/open?id=0B7bxS7MT-Apqd0VTTTNqV2ZnZDg) you can download and embed. Please feel free to use whichever format works best for you.

cc: @lindseyinCHA

**Comment by hannahkane** [comment]
@mmmavis - do you think you'd have time to do this soon?

**Comment by mmmavis** [comment]
@hannahkane I just submitted a PR for this: https://github.com/mozilla/learning.mozilla.org/pull/2486
