### ISSUE TITLE
Update Gigabit Terms & Conditions

### ISSUE THREAD

**Issue by jenntbeard** [mozilla/learning.mozilla.org#2475]
Note: changes are highlighted in the doc linked below, however, as the changes are extensive due to a brand new grants management system, it would be advisable to cut and paste the full text in case any changes were missed in the manual highlighting process. This is a legally binding document that has been reviewed/approved by our internal legal council. 

Update 2016 Terms & Conditions to this version of the 2107 Terms & Conditions found in this document: https://docs.google.com/a/mozilla.com/document/d/1v4ORY4d3hvp1P8XH2x0b2KkxKbFcqihEIaxV2Fd-9m4/edit?usp=sharing

Thanks!

cc: @lindseyinCHA

**Comment by jenntbeard** [comment]
Do you know when this might be done? We are waiting to promote our next application round until this has been updated. Thanks!

**Comment by hannahkane** [comment]
Sorry, didn't realize this was blocking outreach. 

I'll prioritize for today.

**Comment by jenntbeard** [comment]
Thank you! :)

**Comment by mmmavis** [comment]
live now! https://learning.mozilla.org/gigabit/apply/terms

**Comment by jenntbeard** [comment]
Fantastic, thank you!
