### ISSUE TITLE
Copy Changes to WINS mockup/site

### ISSUE THREAD

**Issue by jenntbeard** [mozilla/learning.mozilla.org#2476]
A few copy edits emerged from our back and forth w/NSF. They can be viewed through the tracked changes in this doc - https://docs.google.com/document/d/1f6YdVzGJ2_uj9ZI2ImjOgMjFL16ROHT7bSReKfxpuJE/edit#. Or, I have highlighted the individual changes below by section. Thanks!

Challenges Tab: 
- Challenge 1 question statement is now - "How can we leverage wireless technology to keep people connected to each other and to vital information sources in the aftermath of a disaster where Internet access is unavailable or compromised?" (Previously was - "How can we leverage wireless technology to keep people connected to each other and to vital information sources in the aftermath of a disaster?")
- Challenge 2 question statement is now - "How can we leverage existing infrastructure to provide robust wireless Internet connectivity in communities that need greater access?" (Previously was - "How can we leverage existing infrastructure to provide reliable wireless Internet connectivity in communities that need greater access?") 

Submit Tab:
- Judging criteria - two labels are changing. 'Creativity' should now be 'Differentiation' and 'Adaptability' should now be 'Scalability'. 

cc: @mehan

**Comment by hannahkane** [comment]
Thanks, @jenntbeard! I should have mentioned that these tickets can be filed in the NSF WINS repo. I just copied this ticket there (https://github.com/mozilla/nsf-challenge/issues/75), so will close it here.
