### ISSUE TITLE
Updates to Web Literacy 2.0 Paper

### ISSUE THREAD

**Issue by anmechung** [mozilla/learning.mozilla.org#2477]
For the web literacy 2.0 paper (https://mozilla.github.io/content/web-lit-whitepaper/), please add:  

1. Authors: An-Me Chung, Iris Bond Gill, Ian O'Bryne under the title (Web Literacy 2.0)
2. Read Mozilla’s blog about web literacy, or contribute a guest blog post.  Read, Write, Participate https://medium.com/read-write-participate.  Add this as the last paragraph in the conclusion section.

**Comment by hannahkane** [comment]
Done!
