### ISSUE TITLE
Update gigabit social graphics

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#2488]
- [Social Share Apply By](https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_ebFJPQ09INEgtekU/view?usp=sharing) - needs new logo and update due date to August 1
- [Social Share FB](https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eSElnSTJUTUVVcUU/view?usp=sharing) - needs new logo
- [Social Share Twitter](https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_edl9TOEZtd2xXZ1k/view?usp=sharing) - needs new logo

**Comment by hannahkane** [comment]
@sabrinang - I believe you created these last year. Can you please point to the original art files, for whomever ends up picking this up? Thanks!

**Comment by hannahkane** [comment]
cc @jenntbeard

**Comment by sabrinang** [comment]
The .ai file is here: https://drive.google.com/open?id=0B4Q8pzCpDS_eczByekhSN1VYTnc

**Comment by jenntbeard** [comment]
Can we get a .jpeg or .eps file too?

**Comment by flukeout** [comment]
Okay, starting on this today.

**Comment by flukeout** [comment]
There is quite a range of designs and sizes in the source files...

![image](https://cloud.githubusercontent.com/assets/25212/26557907/aea81c7e-4459-11e7-99a7-fe252af329ad.png)

@hannahkane - do we just need the specific ones you called out in this issue updated?

**Comment by hannahkane** [comment]
@flukeout - yeah, just the ones mentioned. thanks!

**Comment by hannahkane** [comment]
hey @flukeout - did this land?

**Comment by flukeout** [comment]
OH SHOOOOOOOT NO

**Comment by flukeout** [comment]
Did not land, putting on top of pile now.

**Comment by flukeout** [comment]
So, the old designs don't really fit with the new branding it all, so I took at stab at it with some of our new colors & style...

![image](https://user-images.githubusercontent.com/25212/26856117-9d05e54a-4ad6-11e7-81e1-fe9420a25061.png)

cc @hannahkane thoughts on this? Can you cc the Gigabit folks that would be interested? Thanks! I'll wait to continue on the rest until I hear back.

**Comment by jenntbeard** [comment]
Looks great to me, thanks!

**Comment by hannahkane** [comment]
Thanks, @flukeout. Looks good to me. I think @jenntbeard's approval is all we need.

**Comment by flukeout** [comment]
Okay, here is the set based on the links @hannahkane requested...

![627x627](https://user-images.githubusercontent.com/25212/26907940-2e6be068-4bac-11e7-9bde-0aed49394940.png)

![1024x512](https://user-images.githubusercontent.com/25212/26907942-2e839212-4bac-11e7-8894-d54df025d0d4.png)

![1200x717](https://user-images.githubusercontent.com/25212/26907941-2e6e68a6-4bac-11e7-94b0-c12a0e645830.png)

**Comment by jenntbeard** [comment]
Awesome, looks great to me - thank you so much!

**Comment by flukeout** [comment]
Okay, great - @jenntbeard @hannahkane the final banners and source file are in here:

* https://drive.google.com/open?id=0B_CPRh4f3yyqTHJDT0NSZjdBY00

Let me know if you have any problems getting to them or want any changes. Cheers!

**Comment by flukeout** [comment]
@jenntbeard - just noticed you were also looking for specifically for ``.jpg`` and ``.eps`` formats. Let me know if that is still the case, the ``.png`` I exported should work well for social but if you have any other anticipated uses that need different file formats, let me know.

**Comment by jenntbeard** [comment]
@flukeout What you sent was perfect as is, thanks!

Can we get a similar set for the WINS Challenges @hannahkane? It would be awesome to have the color scheme similar to the WINS website header (https://wirelesschallenge.mozilla.org/) and the due date for submission is October 15, 2017. Thanks!

cc @mehan

**Comment by hannahkane** [comment]
added a ticket for that [here](https://github.com/mozilla/nsf-challenge/issues/91)

Could use feedback from @jenntbeard and @mehan there.
