### ISSUE TITLE
Updated Terms & Conditions for Gigabit Site

### ISSUE THREAD

**Issue by jenntbeard** [mozilla/learning.mozilla.org#2489]
Hi! Sincerest apologies but Fluxx is ever changing - one could say "in flux" (ba dum dum)- and requires some tweaks to our Terms and Conditions for the next RFP round. Since people are currently accessing and submitting Letters of Intent, we need these updates to go live as soon as possible to avoid confusion. (People are preparing their full apps off the clarified questions that need to be updated.)

The changes are on this page: https://learning.mozilla.org/en-US/gigabit/apply/terms
Please delete the stricken text and replace with the text in the doc that is currently in blue - https://docs.google.com/document/d/1kTxyqYkwOugre2F2lr_sg1TgwtJyKoOMGwTchwQtpE0/edit#

Muchos gracias!!

cc: @LindseyFrost

**Comment by mmmavis** [comment]
Live! Thanks @hannahkane for making all the changes! https://learning.mozilla.org/en-US/gigabit/apply/terms

**Comment by jenntbeard** [comment]
Thanks, y'all!!
