### ISSUE TITLE
Allow for multiple links on the Gigabit portfolio detail pages

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#2510]
In a given Gigabit Portfolio item detail page (see [an example](https://learning.mozilla.org/en-US/gigabit/portfolio/virtual-reality-stem-lessons)), there is a button at the bottom, labeled "website" that takes the user to an external site.

Some projects have up to three links to point to, so we need to allow for that in the UI.

Looking for a relatively quick solution that accommodates 0, 1, 2, or 3 links. Ideally, we'd be able to control the label on the button, but that's not a requirement.

**Comment by hannahkane** [comment]
cc @jenntbeard

**Comment by gvn** [comment]
You can now add as many links (with labels) as you want by editing `portfolio.json`.

All `Links` properties can either be `null` or an array of links, following this schema:

```json
    "Links": [
      {
        "url": "http://www.example.org/",
        "label": "label goes here"
      }
    ],
```
