### ISSUE TITLE
Remove past Key Date from Gigabit Apply Page

### ISSUE THREAD

**Issue by jenntbeard** [mozilla/learning.mozilla.org#2518]
On this page - https://learning.mozilla.org/en-US/gigabit/apply - please remove the first Key Date that has now past - "August 1, 2017 Round 3 Applications Due". Thanks!!

**Comment by hannahkane** [comment]
@jenntbeard - do you want it removed entirely, or maybe to add copy saying something like, "Please note: this deadline has passed"?

**Comment by jenntbeard** [comment]
Let's just move it entirely - people sometimes think they can apply late and we are definitely past that point. Thanks for checking!
