### ISSUE TITLE
Add CC license to Learning site

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#2529]
Abigail points out that the Learning site footer doesn't include a link to a CC license.

Can we add a link to: CC BY 4.0 (https://creativecommons.org/licenses/by/4.0/)?

**Comment by hannahkane** [comment]
@alanmoo - I believe this is a small thing. Is it something someone who's not attending Mozfest could do this week?

**Comment by alanmoo** [comment]
@gvn can you take care of this today?

**Comment by gvn** [comment]
Sure thing
