### ISSUE TITLE
Change to Grantee name on Gigabit Portfolio Page

### ISSUE THREAD

**Issue by jenntbeard** [mozilla/learning.mozilla.org#2535]
Hi, the lead org on one of our new Gigabit grants has changed their name and would like to go from “Integrated Arts” to “Harmonic Laboratory" on this page https://learning.mozilla.org/en-US/gigabit/portfolio/city-synth

Can we also use their new logo as well?
[FINAL_LOGOS.pdf](https://github.com/mozilla/learning.mozilla.org/files/1483551/FINAL_LOGOS.pdf)

@alanmoo feel free to let me know if I submitted this incorrectly.

**Comment by alanmoo** [comment]
Perfect, and thanks for the tag. That PDF has two logos- which one should be used, and do you happen to have it in SVG format?

**Comment by jenntbeard** [comment]
Ah yes, can you use the top one (just black and white, not the one with grey)? I have asked for an SVG format, might not be until Monday until I hear back. Thanks for your help!

**Comment by alanmoo** [comment]
Cool. Post that when you get it and @mmmavis can use that as a cue to start the work.

**Comment by jenntbeard** [comment]
@alanmoo - Github doesn't support SVG files (just so you know)

@mmmavis you can locate the file at this GDrive link - https://drive.google.com/open?id=13cHLmkrtT_zmV1qXZc9qumKXDcT8ZPMM

**Comment by mmmavis** [comment]
Done!
