### ISSUE TITLE
Add resource to one of the grantee portfolio pages and update application due date

### ISSUE THREAD

**Issue by jenntbeard** [mozilla/learning.mozilla.org#2537]
Hi @alanmoo, we have three minor updates needed to the Gigabit website.

1) On this Portfolio page (https://learning.mozilla.org/en-US/gigabit/portfolio/urban-farming-guys-smart-greenhouse) we want to add this video (youtu.be/SXaHo8yI_88) as a resource button. It should show up as a second 'VIDEO' button and link to the video.

2) On the Apply page (https://learning.mozilla.org/en-US/gigabit/apply) change the Round 4 application deadline to Monday, January 22 in the 'Key Dates' box. 

3) Remove the following items from the 'Key Dates' box:
October 15, 2017     Round 4 Application Window Opens
December 1, 2017   Round 4 Letter of Intent Form Due for All Projects

**Comment by mmmavis** [comment]
Changes are live! 

https://learning.mozilla.org/gigabit/apply
https://learning.mozilla.org/gigabit/portfolio/urban-farming-guys-smart-greenhouse

**Comment by jenntbeard** [comment]
Awesome, thanks @mmmavis!
