### ISSUE TITLE
Add banner about sunsetting programs

### ISSUE THREAD

**Issue by alanmoo** [mozilla/learning.mozilla.org#2539]
From https://github.com/MozillaFoundation/mofo-devops/issues/564

Details

The language has been approved but does not include Gigabit.. We are still getting emails to teachtheweb email address and would like to minimize confusion

The approved language is below :

Mozilla has made a strategic decision to sunset its local digital literacy programs including Hive and Mozilla Clubs over the course of 2017/2018. You have been, and will continue to be, leaders within this movement for Internet health, and Mozilla will continue to find ways to support you and concrete ways for people from our local communities to plug into this work. We will honor all current commitments to our grantee partners and donors. Content on this site, including curriculum and other resources, will continue to be available and archived here for your use. Visit foundation.mozilla.org for more information or contact mozillaclubs@mozillafoundation.org with any further questions.

Something along the lines of this:
<img width="1226" alt="screen shot 2017-12-19 at 12 49 11 pm" src="https://user-images.githubusercontent.com/1682681/34171080-1ba4ff70-e4bb-11e7-9b54-4787194caa85.png">

From @ldecoursy:
I think a color to highlight it is useful as an important call-out. I think it's ok just on the homepage for now. I did put together this audit doc, there are other small changes that would be great at some point (not before Thursday) https://docs.google.com/document/d/1tG9Au4CM17GOM6Op1PIoWEFeQevRY7f5YImgae2kGok/edit

**Comment by sabrinang** [comment]
![mozilla learning - sunset notice](https://user-images.githubusercontent.com/2492510/34174600-6205cefc-e4ae-11e7-859e-2c9b51e300d4.jpg)

I’ve used bootstrap alert-warning colours:
#faf2cc (background colour)
#8a6d3b (text colour)

I also used font awesome icon near the title:
fa-hand-o-right

It uses the same h2 and p sizes as the rest of the site.

@alanmoo Please review or let me know if you have feedback for this.

**Comment by sabrinang** [comment]
Title should be **Important Update** (sorry I wrote notice in the mockup)

**Comment by xmatthewx** [comment]
Thanks @sabrinang looks great. Thanks @gvn for the speedy work.
