### ISSUE TITLE
Remove past event from Gigabit site

### ISSUE THREAD

**Issue by jenntbeard** [mozilla/learning.mozilla.org#2541]
Hi, can you remove the MozFest block from this page: https://learning.mozilla.org/en-US/gigabit/events? Thank you! @alanmoo

**Comment by alanmoo** [comment]
Will the events section header still be there, just empty?

**Comment by jenntbeard** [comment]
Not for long - we have some events to add. I will file them tomorrow - I can add to this string if that's easier. Just waiting on some details. Thanks!

**Comment by alanmoo** [comment]
Yeah, add them in here when you get them and I'll assign the set of work to someone to knock out all at once since they'll need to be in that codebase anyway.

**Comment by jenntbeard** [comment]
Please add the two upcoming events highlighted in this sheet in yellow: https://docs.google.com/spreadsheets/d/1X3nmzwZkG0lJh-VfzBhuN6SQws2VM6WeR8Rybol8GTk/edit#gid=0. Thank you!
