### ISSUE TITLE
Add event to Mozilla Gigabit Events Tab

### ISSUE THREAD

**Issue by jenntbeard** [mozilla/learning.mozilla.org#2545]
@alanmoo Hi, sorry, one more event to add to https://learning.mozilla.org/en-US/gigabit/events. It's highlighted in yellow in this sheet: https://docs.google.com/spreadsheets/d/1X3nmzwZkG0lJh-VfzBhuN6SQws2VM6WeR8Rybol8GTk/edit#gid=0

Thanks!!

**Comment by jenntbeard** [comment]
Just checking on this status.

If it's still open, I would like to make one additional request. On this page - https://learning.mozilla.org/en-US/gigabit/portfolio/kvasir-vr-teacher-guided-shared-virtual-worlds - the button should be directing to this link instead of it's current location - https://vrlab.cmix.louisiana.edu/category/news/mozilla-gigabit-blog/).

Thanks!!

**Comment by alanmoo** [comment]
@mmmavis or @gvn if one of you gets blocked by something this would be a good ticket to knock out.

**Comment by gvn** [comment]
I can take it

**Comment by gvn** [comment]
Just pushed this to production...

**Comment by jenntbeard** [comment]
Thanks @gvn !
