### ISSUE TITLE
Add automated integration tests

### ISSUE THREAD

**Issue by toolness** [mozilla/learning.mozilla.org#913]
As Ross mentioned in https://github.com/mozilla/teach.webmaker.org/issues/806#issuecomment-102016494, it might be good idea for us to write automated selenium/webdriver-based tests that ensure our site properly integrates with all the services it depends on (teach-api, id.webmaker.org, etc).

We could potentially use a tool like [Mailinator](http://mailinator.com/) to ensure that email works too.

Such integration tests would be particularly useful in verifying that our acceptance tests work. It'd probably be useful to coordinate with the id.webmaker.org folks on this, since Teach is closely coupled to it and I imagine those folks would like to have some integration tests too.

@hannahkane and @wex, I'm curious how important you think this is. It's definitely doable and useful--so long as the tests aren't too fragile.

**Comment by Pomax** [comment]
based on the build work we want to do in 2016, this issue may or may not stay relevant. Leaving open for now.

**Comment by alicoding** [comment]
It feels like this might make sense to be closed and revisit once we have a final plan of our learning site re-write? @Pomax ?

**Comment by Pomax** [comment]
agreed.
