### ISSUE TITLE
woff2 files are not uploaded to S3

### ISSUE THREAD

**Issue by mmmavis** [mozilla/learning.mozilla.org#959]
https://teach.mozilla.org/vendor/bootstrap/fonts/glyphicons-halflings-regular.woff2 is now a 404

![screen shot 2015-05-28 at 11 09 22 pm](https://cloud.githubusercontent.com/assets/2896608/7877337/9e52bfb6-058e-11e5-9e47-3ce241f9276e.png)

**Comment by toolness** [comment]
ruh-roh, i'm confused as to why our [link checker](https://github.com/mozilla/teach.webmaker.org/pull/809) didn't notice this... huh.

**Comment by mmmavis** [comment]
<img width="1216" alt="screen shot 2015-07-09 at 1 48 51 pm" src="https://cloud.githubusercontent.com/assets/2896608/8606561/45518608-2641-11e5-914f-b6e38bc2e2ed.png">

ummm https://teach.mozilla.org/vendor/font-awesome/fonts/fontawesome-webfont.woff2?v=4.3.0 is 404 as well

**Comment by mmmavis** [comment]
Note these 404 errors were found on Chrome v43 on OS X 10.9.5 but not FF v38.  http://caniuse.com/#feat=woff2 explains why. 

`.woff` were loaded on Chrome as [fallback](https://github.com/twbs/bootstrap/blob/master/dist/css/bootstrap.css#L267) that's why the site still looks fine. I googled a bit for solution... it seems like users will have to [add MIME type `woff2` to IIS](https://www.queryxchange.com/q/27_29842583/bootstrap-woff2-font-not-getting-loaded-correctly/) (I don't know what the equivalents are on non-Window OS) on their own devices. Not sure what else we can do on our side to resolve this issue.  :eyes:

**Comment by toolness** [comment]
Oh, IIS is just the Windows-based web server, it's only needed if we were hosting our site using IIS (but we use S3). The instructions at the link you mentioned is a thing that webmasters who use IIS to host their site need to do--not that users who browse need to do.

It actually looks like our `gulp s3` command isn't uploading the woff2 file to S3 for some reason, so I'll look into that and hopefully issue a PR that fixes things.

**Comment by toolness** [comment]
Ack, it looks like this is due to a bug that https://github.com/nkostelnik/gulp-s3/pull/34 fixes. The unfortunate thing is that the last commit to gulp-s3 was over a year ago, and that PR was filed in October 2014... So in order to fix this we may need to poke @nkostelnik (the maintainer of gulp-s3), or just fork the repo and use our patched version.

**Comment by mmmavis** [comment]
> Oh, IIS is just the Windows-based web server, it's only needed if we were hosting our site using IIS (but we use S3). The instructions at the link you mentioned is a thing that webmasters who use IIS to host their site need to do--not that users who browse need to do.

Ah yea, that was my first guess too. I tried googling instructions for adding MIME type on S3 but had no luck.  That's why in the end I thought IIS was something live on end users' end.  :grin:

**Comment by mmmavis** [comment]
> So in order to fix this we may need to poke @nkostelnik (the maintainer of gulp-s3), or just fork the repo and use our patched version.

I prefer maintaining fewer repos on our own.  How about we wait for a few days first since we can still rely on the fallback `.woff` for now.  :stuck_out_tongue_winking_eye:

**Comment by alicoding** [comment]
Closing this since it has been resolved.
